import '../habitat_tint.dart';
import 'furniture_def.dart';
import 'furniture_tags.dart';

/// Central catalog of furniture blueprints.
///
/// Add new pieces here (+ assets under `furniture/<id>/`). Prefer tags/use over
/// scattering `switch (kind)` across the codebase.
abstract final class FurnitureRegistry {
  static final Map<String, FurnitureDef> _byId = {
    for (final d in all) d.id: d,
  };

  /// Legacy save / API ids → registry ids.
  static const Map<String, String> aliases = {
    'chair': 'dining_chair',
    'table': 'table_2x2',
    'lamp': 'lamp_standing',
    'plant': 'plant_pot',
  };

  static String resolveId(String kind) => aliases[kind] ?? kind;

  static FurnitureDef? tryGet(String kind) => _byId[resolveId(kind)];

  static FurnitureDef get(String kind) {
    final d = tryGet(kind);
    if (d == null) {
      throw StateError('Unknown furniture kind: $kind');
    }
    return d;
  }

  static bool hasTag(String kind, FurnitureTag tag) =>
      tryGet(kind)?.hasTag(tag) ?? false;

  static Iterable<FurnitureDef> withTag(FurnitureTag tag) =>
      all.where((d) => d.hasTag(tag));

  /// Placeable kinds shown in the editor (registry + a few procedural leftovers).
  static List<String> get placeableIds => [
        for (final d in all) d.id,
        // Cosmetic procedural leftovers (no RW sprite in Furniture/).
        'painting',
        'rug',
        'vase',
        'boardgame',
        'instrument',
        'tv',
        'heater',
        'cooler',
        'gatheringSpot',
      ];

  static const List<FurnitureDef> all = [
    // —— Seats ——
    FurnitureDef(
      id: 'armchair',
      label: 'Poltrona',
      footprint: (1, 1),
      drawSize: (1.4, 1.4),
      facingMode: FurnitureFacingMode.cardinal,
      tags: {FurnitureTag.sit, FurnitureTag.comfort},
      use: FurnitureUse.sit,
      beauty: 4,
      defaultTint: StuffPalettes.clothBlue,
    ),
    FurnitureDef(
      id: 'dining_chair',
      label: 'Cadeira',
      footprint: (1, 1),
      drawSize: (1.0, 1.0),
      facingMode: FurnitureFacingMode.cardinal,
      tags: {FurnitureTag.sit},
      use: FurnitureUse.sit,
      beauty: 1,
      defaultTint: StuffPalettes.woodDark,
    ),
    FurnitureDef(
      id: 'stool',
      label: 'Banquinho',
      footprint: (1, 1),
      drawSize: (0.85, 0.85),
      facingMode: FurnitureFacingMode.cardinal,
      tags: {FurnitureTag.sit},
      use: FurnitureUse.sit,
      beauty: 0,
      defaultTint: StuffPalettes.wood,
    ),
    FurnitureDef(
      id: 'couch',
      label: 'Sofá',
      footprint: (2, 1),
      drawSize: (2.0, 1.15),
      facingMode: FurnitureFacingMode.cardinal,
      tags: {FurnitureTag.sit, FurnitureTag.comfort, FurnitureTag.joy},
      use: FurnitureUse.sit,
      beauty: 6,
      defaultTint: StuffPalettes.clothRed,
    ),

    // —— Beds ——
    FurnitureDef(
      id: 'bed',
      label: 'Cama',
      footprint: (1, 2),
      drawSize: (1.0, 2.0),
      facingMode: FurnitureFacingMode.cardinal,
      tags: {FurnitureTag.sleep},
      use: FurnitureUse.sleep,
      beauty: 2,
      hasBeddingMask: true,
      defaultTint: StuffPalettes.clothBlue,
    ),
    FurnitureDef(
      id: 'double_bed',
      label: 'Cama de casal',
      footprint: (2, 2),
      drawSize: (2.0, 2.0),
      facingMode: FurnitureFacingMode.cardinal,
      tags: {FurnitureTag.sleep},
      use: FurnitureUse.sleep,
      beauty: 4,
      hasBeddingMask: true,
      defaultTint: StuffPalettes.clothBlue,
    ),
    FurnitureDef(
      id: 'royal_bed',
      label: 'Cama real',
      footprint: (2, 2),
      drawSize: (2.0, 2.0),
      facingMode: FurnitureFacingMode.cardinal,
      tags: {FurnitureTag.sleep, FurnitureTag.beauty},
      use: FurnitureUse.sleep,
      beauty: 12,
      hasBeddingMask: true,
      defaultTint: StuffPalettes.gold,
    ),
    FurnitureDef(
      id: 'hospital_bed',
      label: 'Cama hospitalar',
      footprint: (1, 2),
      drawSize: (1.0, 2.0),
      facingMode: FurnitureFacingMode.cardinal,
      tags: {FurnitureTag.sleep},
      use: FurnitureUse.sleep,
      beauty: -1,
      hasBeddingMask: true,
      defaultTint: StuffPalettes.steel,
    ),
    FurnitureDef(
      id: 'bedroll',
      label: 'Saco de dormir',
      footprint: (1, 2),
      drawSize: (1.0, 2.0),
      facingMode: FurnitureFacingMode.cardinal,
      tags: {FurnitureTag.sleep},
      use: FurnitureUse.sleep,
      beauty: 0,
      hasBeddingMask: true,
      defaultTint: StuffPalettes.clothGreen,
    ),
    FurnitureDef(
      id: 'bedroll_double',
      label: 'Saco duplo',
      footprint: (2, 2),
      drawSize: (2.0, 2.0),
      facingMode: FurnitureFacingMode.cardinal,
      tags: {FurnitureTag.sleep},
      use: FurnitureUse.sleep,
      beauty: 1,
      hasBeddingMask: true,
      defaultTint: StuffPalettes.clothGreen,
    ),
    FurnitureDef(
      id: 'sleep_spot',
      label: 'Vaga de sono',
      footprint: (1, 2),
      drawSize: (1.0, 2.0),
      facingMode: FurnitureFacingMode.cardinal,
      tags: {FurnitureTag.sleep},
      use: FurnitureUse.sleep,
      beauty: -2,
      blocksWalk: false,
      defaultTint: StuffPalettes.natural,
    ),
    FurnitureDef(
      id: 'double_sleep_spot',
      label: 'Vaga dupla',
      footprint: (2, 2),
      drawSize: (2.0, 2.0),
      facingMode: FurnitureFacingMode.cardinal,
      tags: {FurnitureTag.sleep},
      use: FurnitureUse.sleep,
      beauty: -1,
      blocksWalk: false,
      defaultTint: StuffPalettes.natural,
    ),

    // —— Tables ——
    FurnitureDef(
      id: 'table_1x2',
      label: 'Mesa 1×2',
      footprint: (1, 2),
      drawSize: (1.15, 2.15),
      drawAlign: HabitatPropAlign.center,
      facingMode: FurnitureFacingMode.cardinal,
      tags: {FurnitureTag.table},
      use: FurnitureUse.sitAtTable,
      beauty: 2,
      defaultTint: StuffPalettes.wood,
    ),
    FurnitureDef(
      id: 'table_2x2',
      label: 'Mesa 2×2',
      footprint: (2, 2),
      drawSize: (2.2, 2.2),
      drawAlign: HabitatPropAlign.center,
      facingMode: FurnitureFacingMode.single,
      tags: {FurnitureTag.table},
      use: FurnitureUse.sitAtTable,
      beauty: 3,
      defaultTint: StuffPalettes.wood,
    ),
    FurnitureDef(
      id: 'table_2x4',
      label: 'Mesa 2×4',
      footprint: (2, 4),
      drawSize: (2.2, 4.2),
      drawAlign: HabitatPropAlign.center,
      facingMode: FurnitureFacingMode.cardinal,
      tags: {FurnitureTag.table},
      use: FurnitureUse.sitAtTable,
      beauty: 5,
      defaultTint: StuffPalettes.wood,
    ),
    FurnitureDef(
      id: 'table_3x3',
      label: 'Mesa 3×3',
      footprint: (3, 3),
      drawSize: (3.2, 3.2),
      drawAlign: HabitatPropAlign.center,
      facingMode: FurnitureFacingMode.single,
      tags: {FurnitureTag.table},
      use: FurnitureUse.sitAtTable,
      beauty: 6,
      defaultTint: StuffPalettes.wood,
    ),
    FurnitureDef(
      id: 'end_table',
      label: 'Mesa de cabeceira',
      footprint: (1, 1),
      drawSize: (0.95, 0.95),
      drawAlign: HabitatPropAlign.center,
      facingMode: FurnitureFacingMode.cardinal,
      tags: {FurnitureTag.storage},
      use: FurnitureUse.none,
      beauty: 1,
      defaultTint: StuffPalettes.woodDark,
    ),

    // —— Storage ——
    FurnitureDef(
      id: 'dresser',
      label: 'Cômoda',
      footprint: (2, 1),
      drawSize: (2.0, 1.05),
      facingMode: FurnitureFacingMode.cardinal,
      tags: {FurnitureTag.storage},
      use: FurnitureUse.none,
      beauty: 2,
      defaultTint: StuffPalettes.wood,
    ),
    FurnitureDef(
      id: 'shelf',
      label: 'Prateleira',
      footprint: (2, 1),
      drawSize: (2.0, 1.1),
      facingMode: FurnitureFacingMode.cardinal,
      tags: {FurnitureTag.storage},
      use: FurnitureUse.none,
      beauty: 1,
      defaultTint: StuffPalettes.wood,
    ),
    FurnitureDef(
      id: 'shelf_small',
      label: 'Prateleira pequena',
      footprint: (1, 1),
      drawSize: (1.0, 1.0),
      facingMode: FurnitureFacingMode.cardinal,
      tags: {FurnitureTag.storage},
      use: FurnitureUse.none,
      beauty: 1,
      defaultTint: StuffPalettes.wood,
    ),
    FurnitureDef(
      id: 'bookcase',
      label: 'Estante',
      footprint: (2, 1),
      drawSize: (2.0, 1.15),
      facingMode: FurnitureFacingMode.cardinal,
      tags: {FurnitureTag.storage, FurnitureTag.joy, FurnitureTag.beauty},
      use: FurnitureUse.recreate,
      beauty: 5,
      defaultTint: StuffPalettes.woodDark,
    ),
    FurnitureDef(
      id: 'bookcase_small',
      label: 'Estante pequena',
      footprint: (1, 1),
      drawSize: (1.0, 1.0),
      facingMode: FurnitureFacingMode.cardinal,
      tags: {FurnitureTag.storage, FurnitureTag.joy},
      use: FurnitureUse.recreate,
      beauty: 3,
      defaultTint: StuffPalettes.woodDark,
    ),

    // —— Light ——
    FurnitureDef(
      id: 'lamp_standing',
      label: 'Luminária',
      footprint: (1, 1),
      blocksWalk: false,
      drawSize: (1.0, 1.15),
      drawAlign: HabitatPropAlign.center,
      facingMode: FurnitureFacingMode.single,
      tags: {FurnitureTag.light},
      use: FurnitureUse.toggleLight,
      lightRadius: 8,
      beauty: 1,
      defaultTint: StuffPalettes.steel,
    ),
    FurnitureDef(
      id: 'flood_light',
      label: 'Refletor',
      footprint: (1, 1),
      blocksWalk: false,
      drawSize: (1.3, 1.3),
      drawAlign: HabitatPropAlign.center,
      facingMode: FurnitureFacingMode.single,
      tags: {FurnitureTag.light},
      use: FurnitureUse.toggleLight,
      lightRadius: 14,
      beauty: 0,
      defaultTint: StuffPalettes.steel,
    ),
    FurnitureDef(
      id: 'wall_lamp',
      label: 'Arandela',
      footprint: (1, 1),
      blocksWalk: false,
      drawSize: (0.7, 0.7),
      drawAlign: HabitatPropAlign.center,
      facingMode: FurnitureFacingMode.cardinal,
      tags: {FurnitureTag.light, FurnitureTag.wallMounted},
      use: FurnitureUse.toggleLight,
      lightRadius: 5,
      beauty: 1,
      defaultTint: StuffPalettes.steel,
    ),

    // —— Decor ——
    FurnitureDef(
      id: 'plant_pot',
      label: 'Vaso de planta',
      footprint: (1, 1),
      blocksWalk: false,
      drawSize: (1.0, 1.15),
      tags: {FurnitureTag.plant, FurnitureTag.beauty, FurnitureTag.joy},
      use: FurnitureUse.recreate,
      beauty: 6,
      defaultTint: StuffPalettes.clothGreen,
    ),
    FurnitureDef(
      id: 'column',
      label: 'Coluna',
      footprint: (1, 1),
      drawSize: (0.85, 1.6),
      drawAlign: HabitatPropAlign.south,
      tags: {FurnitureTag.beauty},
      use: FurnitureUse.admire,
      beauty: 4,
      defaultTint: StuffPalettes.stone,
    ),
    FurnitureDef(
      id: 'grand_stele',
      label: 'Estela grandiosa',
      footprint: (2, 2),
      drawSize: (2.2, 2.2),
      drawAlign: HabitatPropAlign.center,
      tags: {FurnitureTag.beauty},
      use: FurnitureUse.admire,
      beauty: 20,
      defaultTint: StuffPalettes.stone,
    ),
    FurnitureDef(
      id: 'pen_marker',
      label: 'Marco',
      footprint: (1, 1),
      blocksWalk: false,
      drawSize: (0.7, 0.7),
      drawAlign: HabitatPropAlign.center,
      tags: {FurnitureTag.beauty},
      use: FurnitureUse.none,
      beauty: 1,
      defaultTint: StuffPalettes.steel,
    ),
    FurnitureDef(
      id: 'large_stele_a',
      label: 'Estela A',
      footprint: (2, 2),
      drawSize: (2.0, 2.0),
      drawAlign: HabitatPropAlign.center,
      tags: {FurnitureTag.beauty},
      use: FurnitureUse.admire,
      beauty: 14,
      defaultTint: StuffPalettes.stone,
    ),
    FurnitureDef(
      id: 'large_stele_b',
      label: 'Estela B',
      footprint: (2, 2),
      drawSize: (2.0, 2.0),
      drawAlign: HabitatPropAlign.center,
      tags: {FurnitureTag.beauty},
      use: FurnitureUse.admire,
      beauty: 14,
      defaultTint: StuffPalettes.stone,
    ),
    FurnitureDef(
      id: 'large_stele_c',
      label: 'Estela C',
      footprint: (2, 2),
      drawSize: (2.0, 2.0),
      drawAlign: HabitatPropAlign.center,
      tags: {FurnitureTag.beauty},
      use: FurnitureUse.admire,
      beauty: 14,
      defaultTint: StuffPalettes.stone,
    ),
    FurnitureDef(
      id: 'large_stele_d',
      label: 'Estela D',
      footprint: (2, 2),
      drawSize: (2.0, 2.0),
      drawAlign: HabitatPropAlign.center,
      tags: {FurnitureTag.beauty},
      use: FurnitureUse.admire,
      beauty: 14,
      defaultTint: StuffPalettes.stone,
    ),
    FurnitureDef(
      id: 'large_stele_e',
      label: 'Estela E',
      footprint: (2, 2),
      drawSize: (2.0, 2.0),
      drawAlign: HabitatPropAlign.center,
      tags: {FurnitureTag.beauty},
      use: FurnitureUse.admire,
      beauty: 14,
      defaultTint: StuffPalettes.stone,
    ),
    FurnitureDef(
      id: 'large_stele_f',
      label: 'Estela F',
      footprint: (2, 2),
      drawSize: (2.0, 2.0),
      drawAlign: HabitatPropAlign.center,
      tags: {FurnitureTag.beauty},
      use: FurnitureUse.admire,
      beauty: 14,
      defaultTint: StuffPalettes.stone,
    ),
  ];
}
