import 'dart:math' as math;

import 'google_timeline.dart';

class GazetteerCity {
  const GazetteerCity({
    required this.name,
    required this.countryCode,
    required this.latitude,
    required this.longitude,
  });

  final String name;
  final String countryCode;
  final double latitude;
  final double longitude;
}

abstract final class CityGazetteer {
  static GazetteerCity? nearest(GeoPoint point, {double maxKm = 80}) {
    GazetteerCity? best;
    var bestD = maxKm;
    for (final city in cities) {
      final d = distanceKm(point, GeoPoint(city.latitude, city.longitude));
      if (d < bestD) {
        bestD = d;
        best = city;
      }
    }
    return best;
  }

  static double distanceKm(GeoPoint a, GeoPoint b) {
    const r = 6371.0;
    final dLat = _rad(b.latitude - a.latitude);
    final dLng = _rad(b.longitude - a.longitude);
    final h = math.sin(dLat / 2) * math.sin(dLat / 2) +
        math.cos(_rad(a.latitude)) *
            math.cos(_rad(b.latitude)) *
            math.sin(dLng / 2) *
            math.sin(dLng / 2);
    return 2 * r * math.asin(math.sqrt(h.clamp(0.0, 1.0)));
  }

  static double _rad(double deg) => deg * math.pi / 180;

  static const countriesPt = <String, String>{
    'BR': 'Brasil',
    'CN': 'China',
    'US': 'Estados Unidos',
    'GB': 'Reino Unido',
    'NL': 'Países Baixos',
    'HU': 'Hungria',
    'FR': 'França',
    'DE': 'Alemanha',
    'IT': 'Itália',
    'ES': 'Espanha',
    'PT': 'Portugal',
    'JP': 'Japão',
    'KR': 'Coreia do Sul',
    'IN': 'Índia',
    'AR': 'Argentina',
    'MX': 'México',
    'CA': 'Canadá',
    'AU': 'Austrália',
    'NZ': 'Nova Zelândia',
    'ZA': 'África do Sul',
    'EG': 'Egito',
    'TR': 'Turquia',
    'RU': 'Rússia',
    'PL': 'Polónia',
    'CZ': 'Chéquia',
    'AT': 'Áustria',
    'CH': 'Suíça',
    'BE': 'Bélgica',
    'SE': 'Suécia',
    'NO': 'Noruega',
    'DK': 'Dinamarca',
    'FI': 'Finlândia',
    'IE': 'Irlanda',
    'GR': 'Grécia',
    'TH': 'Tailândia',
    'VN': 'Vietname',
    'ID': 'Indonésia',
    'MY': 'Malásia',
    'SG': 'Singapura',
    'AE': 'Emirados Árabes Unidos',
    'SA': 'Arábia Saudita',
    'IL': 'Israel',
    'CL': 'Chile',
    'CO': 'Colômbia',
    'PE': 'Peru',
    'UY': 'Uruguai',
    'PY': 'Paraguai',
    'BO': 'Bolívia',
    'EC': 'Equador',
    'VE': 'Venezuela',
    'CU': 'Cuba',
    'MA': 'Marrocos',
    'NG': 'Nigéria',
    'KE': 'Quénia',
    'TZ': 'Tanzânia',
    'GH': 'Gana',
    'PH': 'Filipinas',
    'TW': 'Taiwan',
    'HK': 'Hong Kong',
    'MO': 'Macau',
    'IS': 'Islândia',
    'RO': 'Roménia',
    'BG': 'Bulgária',
    'HR': 'Croácia',
    'RS': 'Sérvia',
    'UA': 'Ucrânia',
    'LT': 'Lituânia',
    'LV': 'Letónia',
    'EE': 'Estónia',
    'SK': 'Eslováquia',
    'SI': 'Eslovénia',
    'LU': 'Luxemburgo',
    'MT': 'Malta',
    'CY': 'Chipre',
    'QA': 'Catar',
    'KW': 'Kuwait',
    'JO': 'Jordânia',
    'LB': 'Líbano',
    'PK': 'Paquistão',
    'BD': 'Bangladeche',
    'LK': 'Sri Lanka',
    'NP': 'Nepal',
    'MM': 'Mianmar',
    'KH': 'Camboja',
    'LA': 'Laos',
    'MN': 'Mongólia',
    'KZ': 'Cazaquistão',
    'UZ': 'Uzbequistão',
    'GE': 'Geórgia',
    'AM': 'Arménia',
    'AZ': 'Azerbaijão',
    'IR': 'Irão',
    'IQ': 'Iraque',
    'AF': 'Afeganistão',
    'ET': 'Etiópia',
    'SN': 'Senegal',
    'CI': 'Costa do Marfim',
    'CM': 'Camarões',
    'AO': 'Angola',
    'MZ': 'Moçambique',
    'ZW': 'Zimbábue',
    'NA': 'Namíbia',
    'BW': 'Botsuana',
    'MG': 'Madagáscar',
    'MU': 'Maurícia',
    'TN': 'Tunísia',
    'DZ': 'Argélia',
    'LY': 'Líbia',
    'SD': 'Sudão',
    'CR': 'Costa Rica',
    'PA': 'Panamá',
    'GT': 'Guatemala',
    'HN': 'Honduras',
    'SV': 'El Salvador',
    'NI': 'Nicarágua',
    'DO': 'República Dominicana',
    'PR': 'Porto Rico',
    'JM': 'Jamaica',
    'TT': 'Trindade e Tobago',
  };

  static String countryName(String code) => countriesPt[code] ?? code;

  /// Major cities + Brazilian metros from the Maps screenshots.
  static const cities = <GazetteerCity>[
    GazetteerCity(name: 'Xangai', countryCode: 'CN', latitude: 31.2304, longitude: 121.4737),
    GazetteerCity(name: 'Pequim', countryCode: 'CN', latitude: 39.9042, longitude: 116.4074),
    GazetteerCity(name: 'Hangzhou', countryCode: 'CN', latitude: 30.2741, longitude: 120.1551),
    GazetteerCity(name: 'Suzhou', countryCode: 'CN', latitude: 31.2989, longitude: 120.5853),
    GazetteerCity(name: 'Cantão', countryCode: 'CN', latitude: 23.1291, longitude: 113.2644),
    GazetteerCity(name: 'Shenzhen', countryCode: 'CN', latitude: 22.5431, longitude: 114.0579),
    GazetteerCity(name: 'Chengdu', countryCode: 'CN', latitude: 30.5728, longitude: 104.0668),
    GazetteerCity(name: 'Chongqing', countryCode: 'CN', latitude: 29.4316, longitude: 106.9123),
    GazetteerCity(name: 'Nanjing', countryCode: 'CN', latitude: 32.0603, longitude: 118.7969),
    GazetteerCity(name: 'Wuhan', countryCode: 'CN', latitude: 30.5928, longitude: 114.3055),
    GazetteerCity(name: 'Xi\'an', countryCode: 'CN', latitude: 34.3416, longitude: 108.9398),
    GazetteerCity(name: 'Hong Kong', countryCode: 'HK', latitude: 22.3193, longitude: 114.1694),
    GazetteerCity(name: 'Macau', countryCode: 'MO', latitude: 22.1987, longitude: 113.5439),
    GazetteerCity(name: 'Taipé', countryCode: 'TW', latitude: 25.0330, longitude: 121.5654),
    GazetteerCity(name: 'Tóquio', countryCode: 'JP', latitude: 35.6762, longitude: 139.6503),
    GazetteerCity(name: 'Osaka', countryCode: 'JP', latitude: 34.6937, longitude: 135.5023),
    GazetteerCity(name: 'Quioto', countryCode: 'JP', latitude: 35.0116, longitude: 135.7681),
    GazetteerCity(name: 'Seul', countryCode: 'KR', latitude: 37.5665, longitude: 126.9780),
    GazetteerCity(name: 'Singapura', countryCode: 'SG', latitude: 1.3521, longitude: 103.8198),
    GazetteerCity(name: 'Banguecoque', countryCode: 'TH', latitude: 13.7563, longitude: 100.5018),
    GazetteerCity(name: 'Hanói', countryCode: 'VN', latitude: 21.0278, longitude: 105.8342),
    GazetteerCity(name: 'Ho Chi Minh', countryCode: 'VN', latitude: 10.8231, longitude: 106.6297),
    GazetteerCity(name: 'Jacarta', countryCode: 'ID', latitude: -6.2088, longitude: 106.8456),
    GazetteerCity(name: 'Kuala Lumpur', countryCode: 'MY', latitude: 3.1390, longitude: 101.6869),
    GazetteerCity(name: 'Manila', countryCode: 'PH', latitude: 14.5995, longitude: 120.9842),
    GazetteerCity(name: 'Nova Deli', countryCode: 'IN', latitude: 28.6139, longitude: 77.2090),
    GazetteerCity(name: 'Mumbai', countryCode: 'IN', latitude: 19.0760, longitude: 72.8777),
    GazetteerCity(name: 'Bangalore', countryCode: 'IN', latitude: 12.9716, longitude: 77.5946),
    GazetteerCity(name: 'Dubai', countryCode: 'AE', latitude: 25.2048, longitude: 55.2708),
    GazetteerCity(name: 'Abu Dhabi', countryCode: 'AE', latitude: 24.4539, longitude: 54.3773),
    GazetteerCity(name: 'Istambul', countryCode: 'TR', latitude: 41.0082, longitude: 28.9784),
    GazetteerCity(name: 'Tel Aviv', countryCode: 'IL', latitude: 32.0853, longitude: 34.7818),
    GazetteerCity(name: 'Cairo', countryCode: 'EG', latitude: 30.0444, longitude: 31.2357),
    GazetteerCity(name: 'Cidade do Cabo', countryCode: 'ZA', latitude: -33.9249, longitude: 18.4241),
    GazetteerCity(name: 'Joanesburgo', countryCode: 'ZA', latitude: -26.2041, longitude: 28.0473),
    GazetteerCity(name: 'Nairobi', countryCode: 'KE', latitude: -1.2921, longitude: 36.8219),
    GazetteerCity(name: 'Lagos', countryCode: 'NG', latitude: 6.5244, longitude: 3.3792),
    GazetteerCity(name: 'Casablanca', countryCode: 'MA', latitude: 33.5731, longitude: -7.5898),
    GazetteerCity(name: 'Marrakech', countryCode: 'MA', latitude: 31.6295, longitude: -7.9811),
    GazetteerCity(name: 'Belo Horizonte', countryCode: 'BR', latitude: -19.9167, longitude: -43.9345),
    GazetteerCity(name: 'Nova Lima', countryCode: 'BR', latitude: -19.9856, longitude: -43.8467),
    GazetteerCity(name: 'Confins', countryCode: 'BR', latitude: -19.6300, longitude: -43.9980),
    GazetteerCity(name: 'Betim', countryCode: 'BR', latitude: -19.9681, longitude: -44.1983),
    GazetteerCity(name: 'Mateus Leme', countryCode: 'BR', latitude: -19.9797, longitude: -44.3853),
    GazetteerCity(name: 'Contagem', countryCode: 'BR', latitude: -19.9317, longitude: -44.0536),
    GazetteerCity(name: 'Sabará', countryCode: 'BR', latitude: -19.8897, longitude: -43.8064),
    GazetteerCity(name: 'São Paulo', countryCode: 'BR', latitude: -23.5505, longitude: -46.6333),
    GazetteerCity(name: 'Rio de Janeiro', countryCode: 'BR', latitude: -22.9068, longitude: -43.1729),
    GazetteerCity(name: 'Brasília', countryCode: 'BR', latitude: -15.7975, longitude: -47.8919),
    GazetteerCity(name: 'Salvador', countryCode: 'BR', latitude: -12.9777, longitude: -38.5016),
    GazetteerCity(name: 'Fortaleza', countryCode: 'BR', latitude: -3.7172, longitude: -38.5433),
    GazetteerCity(name: 'Recife', countryCode: 'BR', latitude: -8.0476, longitude: -34.8770),
    GazetteerCity(name: 'Porto Alegre', countryCode: 'BR', latitude: -30.0346, longitude: -51.2177),
    GazetteerCity(name: 'Curitiba', countryCode: 'BR', latitude: -25.4284, longitude: -49.2733),
    GazetteerCity(name: 'Manaus', countryCode: 'BR', latitude: -3.1190, longitude: -60.0217),
    GazetteerCity(name: 'Belém', countryCode: 'BR', latitude: -1.4558, longitude: -48.4902),
    GazetteerCity(name: 'Goiânia', countryCode: 'BR', latitude: -16.6869, longitude: -49.2648),
    GazetteerCity(name: 'Campinas', countryCode: 'BR', latitude: -22.9099, longitude: -47.0626),
    GazetteerCity(name: 'Florianópolis', countryCode: 'BR', latitude: -27.5954, longitude: -48.5480),
    GazetteerCity(name: 'Vitória', countryCode: 'BR', latitude: -20.3155, longitude: -40.3128),
    GazetteerCity(name: 'Natal', countryCode: 'BR', latitude: -5.7945, longitude: -35.2110),
    GazetteerCity(name: 'Maceió', countryCode: 'BR', latitude: -9.6498, longitude: -35.7089),
    GazetteerCity(name: 'João Pessoa', countryCode: 'BR', latitude: -7.1195, longitude: -34.8450),
    GazetteerCity(name: 'Teresina', countryCode: 'BR', latitude: -5.0920, longitude: -42.8038),
    GazetteerCity(name: 'São Luís', countryCode: 'BR', latitude: -2.5391, longitude: -44.2829),
    GazetteerCity(name: 'Campo Grande', countryCode: 'BR', latitude: -20.4697, longitude: -54.6201),
    GazetteerCity(name: 'Cuiabá', countryCode: 'BR', latitude: -15.6014, longitude: -56.0979),
    GazetteerCity(name: 'Uberlândia', countryCode: 'BR', latitude: -18.9186, longitude: -48.2772),
    GazetteerCity(name: 'Ouro Preto', countryCode: 'BR', latitude: -20.3856, longitude: -43.5035),
    GazetteerCity(name: 'Tiradentes', countryCode: 'BR', latitude: -21.1103, longitude: -44.1733),
    GazetteerCity(name: 'Guarulhos', countryCode: 'BR', latitude: -23.4538, longitude: -46.5333),
    GazetteerCity(name: 'Osasco', countryCode: 'BR', latitude: -23.5324, longitude: -46.7916),
    GazetteerCity(name: 'Santos', countryCode: 'BR', latitude: -23.9608, longitude: -46.3336),
    GazetteerCity(name: 'Niterói', countryCode: 'BR', latitude: -22.8833, longitude: -43.1036),
    GazetteerCity(name: 'Buenos Aires', countryCode: 'AR', latitude: -34.6037, longitude: -58.3816),
    GazetteerCity(name: 'Santiago', countryCode: 'CL', latitude: -33.4489, longitude: -70.6693),
    GazetteerCity(name: 'Lima', countryCode: 'PE', latitude: -12.0464, longitude: -77.0428),
    GazetteerCity(name: 'Bogotá', countryCode: 'CO', latitude: 4.7110, longitude: -74.0721),
    GazetteerCity(name: 'Cidade do México', countryCode: 'MX', latitude: 19.4326, longitude: -99.1332),
    GazetteerCity(name: 'Nova Iorque', countryCode: 'US', latitude: 40.7128, longitude: -74.0060),
    GazetteerCity(name: 'Los Angeles', countryCode: 'US', latitude: 34.0522, longitude: -118.2437),
    GazetteerCity(name: 'Chicago', countryCode: 'US', latitude: 41.8781, longitude: -87.6298),
    GazetteerCity(name: 'São Francisco', countryCode: 'US', latitude: 37.7749, longitude: -122.4194),
    GazetteerCity(name: 'Seattle', countryCode: 'US', latitude: 47.6062, longitude: -122.3321),
    GazetteerCity(name: 'Miami', countryCode: 'US', latitude: 25.7617, longitude: -80.1918),
    GazetteerCity(name: 'Washington', countryCode: 'US', latitude: 38.9072, longitude: -77.0369),
    GazetteerCity(name: 'Boston', countryCode: 'US', latitude: 42.3601, longitude: -71.0589),
    GazetteerCity(name: 'Austin', countryCode: 'US', latitude: 30.2672, longitude: -97.7431),
    GazetteerCity(name: 'Denver', countryCode: 'US', latitude: 39.7392, longitude: -104.9903),
    GazetteerCity(name: 'Las Vegas', countryCode: 'US', latitude: 36.1699, longitude: -115.1398),
    GazetteerCity(name: 'Honolulu', countryCode: 'US', latitude: 21.3069, longitude: -157.8583),
    GazetteerCity(name: 'Toronto', countryCode: 'CA', latitude: 43.6532, longitude: -79.3832),
    GazetteerCity(name: 'Vancouver', countryCode: 'CA', latitude: 49.2827, longitude: -123.1207),
    GazetteerCity(name: 'Montreal', countryCode: 'CA', latitude: 45.5017, longitude: -73.5673),
    GazetteerCity(name: 'Londres', countryCode: 'GB', latitude: 51.5074, longitude: -0.1278),
    GazetteerCity(name: 'Manchester', countryCode: 'GB', latitude: 53.4808, longitude: -2.2426),
    GazetteerCity(name: 'Edimburgo', countryCode: 'GB', latitude: 55.9533, longitude: -3.1883),
    GazetteerCity(name: 'Belper', countryCode: 'GB', latitude: 53.0233, longitude: -1.4814),
    GazetteerCity(name: 'Paris', countryCode: 'FR', latitude: 48.8566, longitude: 2.3522),
    GazetteerCity(name: 'Lyon', countryCode: 'FR', latitude: 45.7640, longitude: 4.8357),
    GazetteerCity(name: 'Berlim', countryCode: 'DE', latitude: 52.5200, longitude: 13.4050),
    GazetteerCity(name: 'Munique', countryCode: 'DE', latitude: 48.1351, longitude: 11.5820),
    GazetteerCity(name: 'Frankfurt', countryCode: 'DE', latitude: 50.1109, longitude: 8.6821),
    GazetteerCity(name: 'Amesterdão', countryCode: 'NL', latitude: 52.3676, longitude: 4.9041),
    GazetteerCity(name: 'Roterdão', countryCode: 'NL', latitude: 51.9244, longitude: 4.4777),
    GazetteerCity(name: 'Bruxelas', countryCode: 'BE', latitude: 50.8503, longitude: 4.3517),
    GazetteerCity(name: 'Lisboa', countryCode: 'PT', latitude: 38.7223, longitude: -9.1393),
    GazetteerCity(name: 'Porto', countryCode: 'PT', latitude: 41.1579, longitude: -8.6291),
    GazetteerCity(name: 'Madrid', countryCode: 'ES', latitude: 40.4168, longitude: -3.7038),
    GazetteerCity(name: 'Barcelona', countryCode: 'ES', latitude: 41.3874, longitude: 2.1686),
    GazetteerCity(name: 'Roma', countryCode: 'IT', latitude: 41.9028, longitude: 12.4964),
    GazetteerCity(name: 'Milão', countryCode: 'IT', latitude: 45.4642, longitude: 9.1900),
    GazetteerCity(name: 'Veneza', countryCode: 'IT', latitude: 45.4408, longitude: 12.3155),
    GazetteerCity(name: 'Viena', countryCode: 'AT', latitude: 48.2082, longitude: 16.3738),
    GazetteerCity(name: 'Zurique', countryCode: 'CH', latitude: 47.3769, longitude: 8.5417),
    GazetteerCity(name: 'Genebra', countryCode: 'CH', latitude: 46.2044, longitude: 6.1432),
    GazetteerCity(name: 'Praga', countryCode: 'CZ', latitude: 50.0755, longitude: 14.4378),
    GazetteerCity(name: 'Budapeste', countryCode: 'HU', latitude: 47.4979, longitude: 19.0402),
    GazetteerCity(name: 'Varsóvia', countryCode: 'PL', latitude: 52.2297, longitude: 21.0122),
    GazetteerCity(name: 'Cracóvia', countryCode: 'PL', latitude: 50.0647, longitude: 19.9450),
    GazetteerCity(name: 'Estocolmo', countryCode: 'SE', latitude: 59.3293, longitude: 18.0686),
    GazetteerCity(name: 'Oslo', countryCode: 'NO', latitude: 59.9139, longitude: 10.7522),
    GazetteerCity(name: 'Copenhaga', countryCode: 'DK', latitude: 55.6761, longitude: 12.5683),
    GazetteerCity(name: 'Helsínquia', countryCode: 'FI', latitude: 60.1699, longitude: 24.9384),
    GazetteerCity(name: 'Dublin', countryCode: 'IE', latitude: 53.3498, longitude: -6.2603),
    GazetteerCity(name: 'Atenas', countryCode: 'GR', latitude: 37.9838, longitude: 23.7275),
    GazetteerCity(name: 'Reykjavík', countryCode: 'IS', latitude: 64.1466, longitude: -21.9426),
    GazetteerCity(name: 'Moscovo', countryCode: 'RU', latitude: 55.7558, longitude: 37.6173),
    GazetteerCity(name: 'São Petersburgo', countryCode: 'RU', latitude: 59.9343, longitude: 30.3351),
    GazetteerCity(name: 'Sydney', countryCode: 'AU', latitude: -33.8688, longitude: 151.2093),
    GazetteerCity(name: 'Melbourne', countryCode: 'AU', latitude: -37.8136, longitude: 144.9631),
    GazetteerCity(name: 'Auckland', countryCode: 'NZ', latitude: -36.8509, longitude: 174.7645),
  ];
}
