import 'music_canon_builder.dart';
import 'music_ontology.dart';

List<MusicTaxon> canonWesternArt() => flattenCanon([
    n('western_art', 'Música Erudita Ocidental', children: [
        n('early', 'Early Music', children: [
            n('medieval', 'Medieval', children: [
                n('plainchant', 'Plainchant', children: [
                    n('gregorian', 'Gregorian Chant', aliases: ['gregorian', 'canto gregoriano']),
                    n('ambrosian', 'Ambrosian Chant'),
                    n('mozarabic', 'Mozarabic Chant'),
                  ]),
                n('organum', 'Organum'),
                n('ars_antiqua', 'Ars Antiqua'),
                n('ars_nova', 'Ars Nova'),
                n('ars_subtilior', 'Ars Subtilior'),
                n('secular', 'Medieval Secular', children: [
                    n('troubadour', 'Troubadour'),
                    n('trouvere', 'Trouvère'),
                    n('minnesang', 'Minnesang'),
                  ]),
                n('trecento', 'Trecento'),
                n('polyphony', 'Medieval Polyphony'),
              ]),
            n('renaissance', 'Renaissance', children: [
                n('franco_flemish', 'Franco-Flemish School'),
                n('italian', 'Italian Renaissance'),
                n('venetian', 'Venetian School'),
                n('roman', 'Roman School'),
                n('english', 'English Renaissance'),
                n('spanish', 'Spanish Renaissance'),
                n('madrigal', 'Madrigal', children: [
                    n('italian', 'Italian Madrigal'),
                    n('english', 'English Madrigal'),
                  ]),
                n('sacred_polyphony', 'Renaissance Sacred Polyphony'),
                n('dance', 'Renaissance Dance Music'),
              ]),
          ], aliases: ['early music', 'musica antiga']),
        n('baroque', 'Baroque', children: [
            n('early', 'Early Baroque', children: [
                n('florentine', 'Florentine Camerata'),
                n('monody', 'Monody'),
                n('early_opera', 'Early Opera'),
              ]),
            n('italian', 'Italian Baroque', children: [
                n('venetian', 'Venetian Baroque'),
                n('roman', 'Roman Baroque'),
                n('neapolitan', 'Neapolitan Baroque'),
              ]),
            n('french', 'French Baroque', children: [
                n('tragedie', 'Tragédie Lyrique'),
                n('dance_suite', 'French Dance Suite'),
              ]),
            n('german', 'German Baroque'),
            n('english', 'English Baroque'),
            n('late', 'Late Baroque', children: [
                n('concerto_grosso', 'Concerto Grosso'),
                n('solo_concerto', 'Solo Concerto'),
                n('fugue', 'Baroque Fugue'),
                n('oratorio', 'Baroque Oratorio'),
                n('cantata', 'Baroque Cantata'),
              ]),
          ], aliases: ['barroco', 'baroque']),
        n('classical', 'Classical Period', children: [
            n('galant', 'Galant'),
            n('empfindsamer', 'Empfindsamer Stil'),
            n('viennese', 'Viennese Classical'),
            n('mannheim', 'Mannheim School'),
            n('chamber', 'Classical Chamber Music'),
            n('symphony', 'Classical Symphony'),
            n('concerto', 'Classical Concerto'),
            n('sonata', 'Classical Sonata'),
          ], aliases: ['classicismo', 'classical']),
        n('romantic', 'Romantic', children: [
            n('early', 'Early Romantic'),
            n('high', 'High Romantic'),
            n('late', 'Late Romantic'),
            n('national', 'National Romanticism', children: [
                n('russian', 'Russian Nationalism'),
                n('czech', 'Czech Nationalism'),
                n('scandinavian', 'Scandinavian Nationalism'),
                n('spanish', 'Spanish Nationalism'),
              ]),
            n('virtuoso', 'Romantic Virtuoso'),
            n('lied', 'Romantic Lied'),
            n('opera', 'Romantic Opera', children: [
                n('italian', 'Italian Romantic Opera'),
                n('german', 'German Romantic Opera'),
                n('french_grand', 'French Grand Opera'),
                n('verismo', 'Verismo'),
              ]),
          ], aliases: ['romantismo', 'romantic']),
        n('modern', 'Modern Classical', children: [
            n('impressionism', 'Impressionism', aliases: ['impressionismo']),
            n('expressionism', 'Expressionism'),
            n('atonality', 'Atonality'),
            n('second_viennese', 'Second Viennese School', children: [
                n('free_atonality', 'Free Atonality'),
                n('twelve_tone', 'Twelve-Tone', aliases: ['dodecafonismo', '12-tone']),
                n('serialism', 'Serialism'),
              ]),
            n('neoclassicism', 'Neoclassicism'),
            n('primitivism', 'Primitivism'),
            n('futurism', 'Futurism'),
            n('microtonality', 'Microtonality'),
            n('new_objectivity', 'New Objectivity'),
          ], aliases: ['modern classical', 'modernismo musical']),
        n('postwar', 'Postwar Avant-Garde', children: [
            n('total_serialism', 'Total Serialism'),
            n('aleatoric', 'Aleatoric Music'),
            n('indeterminacy', 'Indeterminacy'),
            n('stochastic', 'Stochastic Music'),
            n('electronic_art', 'Electronic Art Music', secondary: ['electronic.early']),
            n('electroacoustic', 'Electroacoustic', secondary: ['experimental.electroacoustic']),
            n('concretes', 'Musique Concrète', aliases: ['musique concrete']),
            n('acousmatic', 'Acousmatic'),
            n('tape', 'Tape Music'),
            n('computer', 'Computer Music'),
            n('live_electronics', 'Live Electronics'),
          ]),
        n('minimalism', 'Minimalism', children: [
            n('american', 'American Minimalism'),
            n('process', 'Process Music'),
            n('phase', 'Phase Music'),
            n('drone', 'Drone Minimalism'),
            n('holy', 'Holy Minimalism'),
            n('post', 'Post-Minimalism'),
            n('totalism', 'Totalism'),
          ], aliases: ['minimalismo'], movements: ['movement.minimalism']),
        n('contemporary', 'Contemporary Classical', children: [
            n('spectralism', 'Spectralism'),
            n('new_complexity', 'New Complexity'),
            n('new_simplicity', 'New Simplicity'),
            n('tonal', 'Contemporary Tonal'),
            n('postmodern', 'Postmodern Classical'),
            n('neo_romantic', 'Neo-Romanticism'),
            n('chamber', 'Contemporary Chamber'),
            n('electroacoustic', 'Contemporary Electroacoustic'),
          ]),
      ], aliases: ['classical', 'erudita', 'musica classica', 'western art music'], lore: '## Música Erudita Ocidental\nLinhagem da notação europeia — não é \'música clássica\' como prateleira de supermercado. Medieval e espectralismo cabem aqui; gamelan e Hindustani não.'),
]);

List<MusicTaxon> canonGlobalArt() => flattenCanon([
    n('global_art', 'Tradições Eruditas Não-Ocidentais', children: [
        n('hindustani', 'Hindustani', children: [
            n('dhrupad', 'Dhrupad'),
            n('khayal', 'Khayal'),
            n('thumri', 'Thumri'),
            n('tappa', 'Tappa'),
            n('tarana', 'Tarana'),
          ], aliases: ['hindustani classical', 'indian classical north'], traditions: ['tradition.indian']),
        n('carnatic', 'Carnatic', children: [
            n('kriti', 'Kriti'),
            n('varnam', 'Varnam'),
            n('rtp', 'Ragam-Tanam-Pallavi'),
          ], aliases: ['carnatic classical', 'karnatak'], traditions: ['tradition.indian']),
        n('persian', 'Persian Classical', children: [
            n('dastgah', 'Dastgah'),
            n('radif', 'Radif'),
          ], traditions: ['tradition.persian']),
        n('arabic_art', 'Arabic Art Music', children: [
            n('maqam', 'Maqam'),
            n('wasla', 'Wasla'),
            n('takht', 'Takht'),
            n('muwashshah', 'Muwashshah'),
          ], traditions: ['tradition.arabic']),
        n('ottoman', 'Ottoman Classical', children: [
            n('makam', 'Makam'),
            n('fasil', 'Fasıl'),
            n('court', 'Ottoman Court Music'),
          ], traditions: ['tradition.ottoman']),
        n('chinese_art', 'Chinese Art Music', children: [
            n('yayue', 'Yayue'),
            n('guoyue', 'Guoyue'),
            n('jiangnan_sizhu', 'Jiangnan Sizhu'),
            n('qin', 'Qin Music'),
          ], traditions: ['tradition.chinese']),
        n('japanese_classical', 'Japanese Classical', children: [
            n('gagaku', 'Gagaku'),
            n('shomyo', 'Shōmyō'),
            n('honkyoku', 'Honkyoku'),
            n('sokyoku', 'Sōkyoku'),
            n('jiuta', 'Jiuta'),
            n('nagauta', 'Nagauta'),
          ], traditions: ['tradition.japanese']),
        n('korean_art', 'Korean Traditional Art Music', children: [
            n('gugak', 'Gugak'),
            n('jeongak', 'Jeongak'),
            n('sanjo', 'Sanjo'),
            n('pansori', 'Pansori'),
          ], traditions: ['tradition.korean']),
        n('indonesian_classical', 'Indonesian Classical Traditions', children: [
            n('javanese_gamelan', 'Javanese Gamelan'),
            n('balinese_gamelan', 'Balinese Gamelan', children: [
                n('gong_kebyar', 'Gong Kebyar'),
                n('semar', 'Gamelan Semar Pegulingan'),
              ]),
          ], aliases: ['gamelan'], traditions: ['tradition.indonesian']),
      ], aliases: ['non-western art', 'global art music'], lore: '## Tradições Eruditas Não-Ocidentais\nNão é World Music. São sistemas eruditos com teoria, pedagogia e cânone próprios.'),
]);

List<MusicTaxon> canonFolk() => flattenCanon([
    n('folk', 'Folk e Música Tradicional', children: [
        n('contemporary', 'Contemporary Folk', children: [
            n('revival', 'Folk Revival'),
            n('singer_songwriter', 'Singer-Songwriter'),
            n('folk_pop', 'Folk Pop'),
            n('folk_rock', 'Folk Rock', secondary: ['rock.folk']),
            n('progressive', 'Progressive Folk'),
            n('psychedelic', 'Psychedelic Folk'),
            n('acid', 'Acid Folk'),
            n('freak', 'Freak Folk'),
            n('indie', 'Indie Folk', secondary: ['rock.alt.indie.folk']),
            n('avant', 'Avant-Folk', secondary: ['experimental.avant_folk']),
            n('dark', 'Dark Folk'),
            n('neofolk', 'Neofolk'),
            n('chamber', 'Chamber Folk'),
            n('folktronica', 'Folktronica'),
          ]),
        n('celtic', 'Celtic', children: [
            n('irish', 'Irish Traditional'),
            n('scottish', 'Scottish Traditional'),
            n('breton', 'Breton'),
            n('celtic_folk', 'Celtic Folk'),
          ], traditions: ['tradition.celtic']),
        n('iberian', 'Iberian', children: [
            n('fado', 'Fado', children: [
                n('lisbon', 'Lisbon Fado'),
                n('coimbra', 'Coimbra Fado'),
              ]),
            n('flamenco', 'Flamenco', children: [
                n('traditional', 'Traditional Flamenco', children: [
                    n('cante_jondo', 'Cante Jondo'),
                    n('solea', 'Soleá'),
                    n('seguiriya', 'Seguiriya'),
                    n('buleria', 'Bulería'),
                    n('tangos', 'Tangos'),
                    n('alegrias', 'Alegrías'),
                    n('fandango', 'Fandango'),
                    n('taranta', 'Taranta'),
                    n('rumba', 'Rumba Flamenca'),
                  ]),
                n('guitar', 'Flamenco Guitar'),
                n('nuevo', 'Flamenco Nuevo'),
                n('jazz', 'Flamenco Jazz', secondary: ['jazz']),
                n('fusion', 'Flamenco Fusion'),
                n('pop', 'Flamenco Pop', secondary: ['pop']),
              ], aliases: ['flamenco'], traditions: ['tradition.andalusi']),
          ]),
        n('balkan', 'Balkan', children: [
            n('balkan_folk', 'Balkan Folk'),
            n('brass', 'Balkan Brass'),
            n('roma', 'Roma Music'),
          ]),
        n('nordic', 'Nordic', children: [
            n('nordic_folk', 'Nordic Folk'),
            n('traditional', 'Nordic Traditional'),
          ]),
      ], aliases: ['folk', 'traditional music'], lore: '## Folk e Música Tradicional\nFolk revival e singer-songwriter vivem aqui. Tradições históricas específicas também têm eixo Tradition — não as achatar em World.'),
]);

List<MusicTaxon> canonBlues() => flattenCanon([
    n('blues', 'Blues', children: [
        n('rural', 'Early / Rural Blues', children: [
            n('country', 'Country Blues', children: [
                n('delta', 'Delta Blues', aliases: ['delta blues']),
                n('piedmont', 'Piedmont Blues'),
                n('texas_country', 'Texas Country Blues'),
                n('hill_country', 'Mississippi Hill Country Blues'),
                n('louisiana', 'Louisiana Blues'),
              ]),
            n('acoustic', 'Acoustic Blues'),
            n('hokum', 'Hokum Blues'),
          ]),
        n('urban', 'Urban Blues', children: [
            n('classic_female', 'Classic Female Blues'),
            n('memphis', 'Memphis Blues'),
            n('kansas_city', 'Kansas City Blues'),
            n('st_louis', 'St. Louis Blues'),
          ]),
        n('electric', 'Electric Blues', children: [
            n('chicago', 'Chicago Blues', children: [
                n('early', 'Early Chicago Blues'),
                n('west_side', 'West Side Chicago Blues'),
              ], aliases: ['chicago blues']),
            n('texas', 'Texas Blues', children: [
                n('electric', 'Texas Electric Blues'),
              ]),
            n('west_coast', 'West Coast Blues'),
            n('louisiana', 'Louisiana Electric Blues', children: [
                n('swamp', 'Swamp Blues'),
              ]),
          ]),
        n('modern', 'Modern Blues', children: [
            n('soul', 'Soul Blues'),
            n('contemporary', 'Contemporary Blues'),
            n('revival', 'Blues Revival'),
            n('blues_rock', 'Blues Rock', aliases: ['blues-rock', 'blues rock'], secondary: ['rock.blues']),
            n('british', 'British Blues'),
            n('texas_rock', 'Texas Blues Rock'),
          ]),
      ], aliases: ['blues']),
]);

List<MusicTaxon> canonJazz() => flattenCanon([
    n('jazz', 'Jazz', children: [
        n('proto', 'Proto-Jazz', children: [
            n('ragtime', 'Ragtime', children: [
                n('classic', 'Classic Ragtime'),
                n('folk', 'Folk Ragtime'),
              ]),
            n('stride', 'Stride'),
            n('novelty_piano', 'Novelty Piano'),
          ]),
        n('early', 'Early Jazz', children: [
            n('new_orleans', 'New Orleans Jazz', aliases: ['new orleans', 'trad jazz']),
            n('dixieland', 'Dixieland'),
            n('hot', 'Hot Jazz'),
            n('chicago', 'Chicago Jazz'),
            n('brass_band', 'New Orleans Brass Band'),
          ]),
        n('swing', 'Swing', children: [
            n('big_band', 'Big Band'),
            n('kansas_city', 'Kansas City Jazz'),
            n('jump', 'Jump Jazz'),
            n('revival', 'Swing Revival'),
          ], aliases: ['swing']),
        n('gypsy', 'Gypsy Jazz', children: [
            n('manouche', 'Jazz Manouche'),
          ], aliases: ['gypsy jazz', 'manouche']),
        n('bebop', 'Bebop', children: [
            n('vocalese', 'Vocalese'),
          ], aliases: ['bebop', 'bop']),
        n('cool', 'Cool Jazz', children: [
            n('west_coast', 'West Coast Jazz'),
          ], aliases: ['cool jazz']),
        n('hard_bop', 'Hard Bop', children: [
            n('soul_jazz', 'Soul Jazz'),
            n('gospel_jazz', 'Gospel Jazz'),
          ], aliases: ['hard bop', 'hardbop']),
        n('modal', 'Modal Jazz', aliases: ['modal jazz', 'modal', 'jazz.modal']),
        n('post_bop', 'Post-Bop', children: [
            n('advanced', 'Advanced Post-Bop'),
          ], aliases: ['post-bop', 'post bop']),
        n('third_stream', 'Third Stream', children: [
            n('jazz_classical', 'Jazz-Classical Fusion'),
            n('chamber', 'Chamber Jazz'),
          ]),
        n('avant', 'Avant-Garde Jazz', children: [
            n('free', 'Free Jazz', aliases: ['free jazz']),
            n('free_improv', 'Free Improvisation', secondary: ['experimental.free_improv']),
            n('spiritual', 'Spiritual Jazz', aliases: ['spiritual jazz', 'jazz.spiritual']),
            n('loft', 'Loft Jazz'),
            n('creative', 'Creative Music'),
            n('aacm', 'AACM-associated Jazz', scenes: ['scene.aacm']),
          ], aliases: ['avant-garde jazz', 'avant jazz']),
        n('fusion', 'Jazz Fusion', children: [
            n('early_electric', 'Early Electric Jazz'),
            n('jazz_rock', 'Jazz-Rock', children: [
                n('progressive', 'Progressive Fusion'),
                n('canterbury', 'Canterbury Fusion', secondary: ['rock.prog.canterbury'], scenes: ['scene.canterbury']),
                n('electric', 'Electric Fusion'),
              ], aliases: ['jazz-rock', 'jazz rock']),
            n('jazz_funk', 'Jazz-Funk', children: [
                n('funk_fusion', 'Funk Fusion'),
                n('groove', 'Groove Jazz'),
                n('boogie', 'Boogie Jazz'),
              ], aliases: ['jazz-funk', 'jazz funk'], secondary: ['funk.jazz_funk']),
            n('guitar', 'Guitar Fusion'),
            n('latin', 'Latin Fusion'),
            n('world', 'World Fusion'),
            n('digital', 'Digital Fusion'),
            n('contemporary', 'Contemporary Fusion'),
          ], aliases: ['fusion', 'jazz fusion', 'jazz.fusion']),
        n('latin', 'Latin Jazz', children: [
            n('afro_cuban', 'Afro-Cuban Jazz', children: [
                n('cubop', 'Cubop'),
                n('mambo', 'Mambo Jazz'),
                n('descarga', 'Descarga'),
              ]),
            n('brazilian', 'Brazilian Jazz', children: [
                n('samba_jazz', 'Samba-Jazz', aliases: ['samba-jazz', 'samba jazz', 'jazz.br'], secondary: ['brazilian.samba.jazz']),
                n('bossa_jazz', 'Bossa Jazz', secondary: ['brazilian.bossa.jazz']),
                n('fusion', 'Brazilian Fusion'),
              ], aliases: ['brazilian jazz', 'jazz brasileiro']),
            n('afro_brazilian', 'Afro-Brazilian Jazz'),
            n('caribbean', 'Caribbean Jazz'),
          ], aliases: ['latin jazz']),
        n('modern', 'Modern Jazz', children: [
            n('ecm', 'ECM-style Jazz', children: [
                n('nordic', 'Nordic Jazz'),
                n('chamber', 'Atmospheric Chamber Jazz'),
                n('atmospheric', 'Atmospheric Jazz'),
              ], aliases: ['ecm']),
            n('neo_bop', 'Neo-Bop'),
            n('contemporary', 'Contemporary Jazz'),
            n('modern_creative', 'Modern Creative'),
            n('progressive', 'Progressive Jazz'),
            n('minimal', 'Minimal Jazz'),
          ]),
        n('hybrid', 'Jazz híbrido contemporâneo', children: [
            n('acid', 'Acid Jazz'),
            n('nu', 'Nu Jazz'),
            n('electro', 'Electro-Jazz'),
            n('broken_beat', 'Broken Beat Jazz'),
            n('hiphop', 'Hip-Hop Jazz', secondary: ['hiphop.east.jazz_rap']),
            n('jazz_rap', 'Jazz Rap', aliases: ['jazz rap', 'jazz-rap', 'hiphop.jazzrap'], secondary: ['hiphop.east.jazz_rap']),
            n('jazztronica', 'Jazztronica'),
            n('future', 'Future Jazz'),
            n('dark', 'Dark Jazz'),
            n('doom', 'Doom Jazz'),
          ]),
        n('vocal', 'Jazz Vocal', children: [
            n('vocal_jazz', 'Vocal Jazz'),
            n('standards', 'Jazz Standards'),
            n('crooner', 'Crooner Jazz'),
            n('scat', 'Scat'),
          ]),
      ], aliases: ['jazz'], lore: '## Jazz\nLinhagem afro-americana improvisada. Fusion não apaga o bebop; ECM não é um género — é uma estética.'),
]);

List<MusicTaxon> canonRnb() => flattenCanon([
    n('rnb', 'Rhythm & Blues', children: [
        n('jump', 'Jump Blues'),
        n('doo_wop', 'Doo-Wop', aliases: ['doo-wop', 'doo wop']),
        n('new_orleans', 'New Orleans R&B', geographies: ['geo.new_orleans']),
        n('chicago', 'Chicago R&B', geographies: ['geo.chicago']),
        n('uptown', 'Uptown R&B'),
        n('quiet_storm', 'Quiet Storm'),
        n('new_jack', 'New Jack Swing', aliases: ['new jack swing']),
        n('alternative', 'Alternative R&B', aliases: ['pbr&b', 'alt-rnb', 'pbrnb']),
        n('contemporary', 'Contemporary R&B'),
        n('uk', 'UK R&B'),
        n('hip_rnb', 'Hip-Hop Soul', secondary: ['hiphop']),
      ], aliases: ['r&b', 'rnb', 'rhythm and blues', 'rhythm & blues'], lore: '## Rhythm & Blues\nNome de arquivo da indústria que cobriu jump, doo-wop e o que veio depois. Não é um sinónimo preguiçoso de soul.'),
]);

List<MusicTaxon> canonSoul() => flattenCanon([
    n('soul', 'Soul', children: [
        n('southern', 'Southern Soul'),
        n('memphis', 'Memphis Soul', geographies: ['geo.memphis']),
        n('detroit', 'Detroit / Motown Soul', aliases: ['motown'], geographies: ['geo.detroit']),
        n('philadelphia', 'Philadelphia Soul', aliases: ['philly soul', 'tsop']),
        n('chicago', 'Chicago Soul', geographies: ['geo.chicago']),
        n('northern', 'Northern Soul'),
        n('deep', 'Deep Soul'),
        n('psychedelic', 'Psychedelic Soul'),
        n('blue_eyed', 'Blue-Eyed Soul'),
        n('british', 'British Soul'),
        n('neo', 'Neo Soul', aliases: ['neo-soul', 'neosoul']),
        n('contemporary', 'Contemporary Soul'),
      ], aliases: ['soul'], lore: '## Soul\nGospel no corpo secular. Motown, Stax e Filadélfia são cidades, não sinónimos.'),
]);

List<MusicTaxon> canonFunk() => flattenCanon([
    n('funk', 'Funk', children: [
        n('proto', 'Proto-Funk'),
        n('p_funk', 'P-Funk', aliases: ['p-funk', 'parliament funkadelic']),
        n('jazz_funk', 'Jazz-Funk', aliases: ['jazz-funk', 'jazz funk'], secondary: ['jazz.fusion.jazz_funk']),
        n('go_go', 'Go-Go', geographies: ['geo.dc']),
        n('boogie', 'Boogie Funk'),
        n('electro', 'Electro-Funk', secondary: ['electronic.electro']),
        n('synth', 'Synth Funk'),
        n('punk', 'Punk-Funk', secondary: ['punk']),
        n('rock', 'Funk Rock', secondary: ['rock']),
        n('metal', 'Funk Metal', secondary: ['metal.funk']),
        n('modern', 'Modern Funk'),
      ], aliases: ['funk'], lore: '## Funk\nO uno no um. Não confundir com funk carioca — esse rio vive em brazilian.funk_br.'),
]);

List<MusicTaxon> canonGospel() => flattenCanon([
    n('gospel', 'Gospel e Música Devocional Afro-Americana', children: [
        n('spirituals', 'Spirituals'),
        n('traditional', 'Traditional Gospel'),
        n('quartet', 'Gospel Quartet'),
        n('golden_age', 'Golden Age Gospel'),
        n('contemporary', 'Contemporary Gospel'),
        n('urban', 'Urban Gospel'),
        n('praise', 'Praise & Worship'),
        n('southern', 'Southern Gospel'),
        n('sacred_steel', 'Sacred Steel'),
        n('choir', 'Mass Choir Gospel'),
        n('holy_hiphop', 'Holy Hip-Hop', secondary: ['hiphop']),
      ], aliases: ['gospel'], functions: ['function.religious'], lore: '## Gospel\nDevocional afro-americano como língua, não como prateleira de Natal.'),
]);

List<MusicTaxon> canonCountry() => flattenCanon([
    n('country', 'Country e Americana', children: [
        n('old_time', 'Old-Time'),
        n('hillbilly', 'Hillbilly'),
        n('honky_tonk', 'Honky-Tonk'),
        n('western_swing', 'Western Swing'),
        n('bluegrass', 'Bluegrass', children: [
            n('traditional', 'Traditional Bluegrass'),
            n('progressive', 'Progressive Bluegrass'),
            n('newgrass', 'Newgrass'),
          ], aliases: ['bluegrass']),
        n('nashville', 'Nashville Sound', geographies: ['geo.nashville']),
        n('countrypolitan', 'Countrypolitan'),
        n('outlaw', 'Outlaw Country'),
        n('urban_cowboy', 'Urban Cowboy'),
        n('country_rock', 'Country Rock', secondary: ['rock']),
        n('alt', 'Alternative Country', aliases: ['alt-country', 'alt country']),
        n('americana', 'Americana', aliases: ['americana']),
        n('texas', 'Texas Country', geographies: ['geo.texas']),
        n('red_dirt', 'Red Dirt'),
        n('western', 'Western / Cowboy'),
        n('country_pop', 'Country Pop'),
        n('bro', 'Bro-Country'),
        n('country_rap', 'Country Rap', secondary: ['hiphop']),
        n('neotraditional', 'Neotraditional Country'),
      ], aliases: ['country', 'country music'], lore: '## Country e Americana\nHonky-tonk, bluegrass e Americana não são o mesmo salão.'),
]);

List<MusicTaxon> canonRock() => flattenCanon([
    n('rock', 'Rock', children: [
        n('roll', 'Rock and Roll', children: [
            n('rockabilly', 'Rockabilly'),
            n('british_invasion', 'British Invasion'),
          ], aliases: ['rock and roll', 'rock n roll', 'rock \'n\' roll']),
        n('surf', 'Surf', children: [
            n('vocal', 'Vocal Surf'),
            n('instrumental', 'Instrumental Surf'),
            n('hot_rod', 'Hot Rod'),
          ], aliases: ['surf rock', 'surf']),
        n('garage', 'Garage Rock', children: [
            n('sixties', '1960s Garage'),
            n('revival', 'Garage Revival'),
            n('punk', 'Garage Punk'),
          ], aliases: ['garage rock', 'garage']),
        n('beat', 'Beat', children: [
            n('merseybeat', 'Merseybeat'),
            n('freakbeat', 'Freakbeat'),
          ], aliases: ['beat music', 'british beat']),
        n('folk', 'Folk Rock', children: [
            n('electric', 'Electric Folk'),
            n('celtic_rock', 'Celtic Rock'),
          ], aliases: ['folk rock', 'folk-rock']),
        n('blues', 'Blues Rock', children: [
            n('british', 'British Blues Rock'),
            n('boogie', 'Boogie Rock'),
          ], aliases: ['blues rock', 'blues-rock']),
        n('psych', 'Psychedelic Rock', children: [
            n('acid', 'Acid Rock'),
            n('raga', 'Raga Rock'),
            n('space', 'Space Rock'),
            n('neo', 'Neo-Psychedelia', aliases: ['neo-psych', 'neo psych']),
          ], aliases: ['psychedelic rock', 'psych', 'rock.psych']),
        n('hard', 'Hard Rock', children: [
            n('early', 'Early Hard Rock'),
            n('boogie', 'Hard Boogie'),
            n('arena', 'Arena Rock'),
          ], aliases: ['hard rock']),
        n('glam', 'Glam Rock', children: [
            n('glitter', 'Glitter Rock'),
            n('hair', 'Hair Metal-adjacent Glam'),
            n('sleaze', 'Sleaze Rock'),
          ], aliases: ['glam rock', 'glam']),
        n('art', 'Art Rock', children: [
            n('avant', 'Avant-Rock'),
            n('experimental', 'Experimental Rock'),
          ], aliases: ['art rock']),
        n('prog', 'Progressive Rock', children: [
            n('early', 'Early Prog'),
            n('symphonic', 'Symphonic Prog'),
            n('canterbury', 'Canterbury Scene Rock', aliases: ['canterbury'], scenes: ['scene.canterbury']),
            n('zeuhl', 'Zeuhl', aliases: ['zeuhl'], movements: ['movement.zeuhl']),
            n('krautrock', 'Krautrock', children: [
                n('motorik', 'Motorik'),
                n('kosmische', 'Kosmische'),
              ], aliases: ['krautrock', 'kraut', 'rock.kraut'], scenes: ['scene.krautrock']),
            n('rio', 'Rock in Opposition', aliases: ['rio', 'rock in opposition'], movements: ['movement.rio']),
            n('neo', 'Neo-Prog'),
            n('metal', 'Prog Metal Crossover', secondary: ['metal.prog']),
          ], aliases: ['prog', 'progressive rock', 'prog rock']),
        n('jazz_rock', 'Jazz Rock', aliases: ['jazz-rock', 'jazz rock'], secondary: ['jazz.fusion.jazz_rock']),
        n('soft', 'Soft Rock'),
        n('yacht', 'Yacht Rock', aliases: ['yacht rock']),
        n('aor', 'AOR', aliases: ['album-oriented rock', 'aor']),
        n('heartland', 'Heartland Rock'),
        n('power_pop', 'Power Pop', aliases: ['power pop', 'powerpop']),
        n('new_wave', 'New Wave', children: [
            n('synth', 'Synthpop New Wave'),
            n('new_romantic', 'New Romantic'),
          ], aliases: ['new wave']),
        n('alt', 'Alternative Rock', children: [
            n('college', 'College Rock'),
            n('indie', 'Indie', children: [
                n('rock', 'Indie Rock'),
                n('pop', 'Indie Pop'),
                n('folk', 'Indie Folk'),
                n('lo_fi', 'Lo-Fi Indie'),
                n('noise', 'Noise Pop / Indie Noise'),
                n('slacker', 'Slacker Rock'),
              ], aliases: ['indie', 'indie rock']),
            n('shoegaze', 'Shoegaze', aliases: ['shoegaze', 'rock.shoegaze']),
            n('dream_pop', 'Dream Pop', aliases: ['dream pop', 'dreampop']),
            n('post_rock', 'Post-Rock', children: [
                n('post_metal', 'Post-Metal', aliases: ['post-metal', 'post metal'], secondary: ['metal', 'metal.post']),
              ], aliases: ['post-rock', 'post rock']),
            n('math', 'Math Rock', aliases: ['math rock', 'math-rock']),
            n('grunge', 'Grunge', aliases: ['grunge'], scenes: ['scene.seattle_grunge']),
            n('post_grunge', 'Post-Grunge'),
            n('britpop', 'Britpop', aliases: ['britpop'], scenes: ['scene.britpop']),
            n('madchester', 'Madchester / Baggy', aliases: ['madchester', 'baggy'], scenes: ['scene.madchester']),
            n('psych_pop', 'Psychedelic Pop', aliases: ['psych pop', 'psychedelic pop']),
            n('noise_rock', 'Noise Rock'),
            n('slowcore', 'Slowcore'),
            n('sadcore', 'Sadcore'),
            n('riot_grrrl', 'Riot Grrrl'),
            n('paisley', 'Paisley Underground'),
            n('jangle', 'Jangle Pop'),
            n('dunedin', 'Dunedin Sound'),
            n('no_wave', 'No Wave Rock', scenes: ['scene.no_wave']),
            n('stoner', 'Stoner Rock', secondary: ['metal.stoner']),
            n('desert', 'Desert Rock'),
            n('garage_revival', 'Garage Rock Revival'),
          ], aliases: ['alternative', 'alternative rock', 'alt rock']),
      ], aliases: ['rock'], lore: '## Rock\nPorto velho. Canterbury, kraut e shoegaze são cidades; \'rock\' sozinho é só o cais.'),
]);

List<MusicTaxon> canonPunk() => flattenCanon([
    n('punk', 'Punk e Hardcore', children: [
        n('proto', 'Proto-Punk', aliases: ['proto-punk', 'protopunk']),
        n('punk', 'Punk Rock', children: [
            n('seventies', '1970s Punk'),
            n('uk', 'UK Punk'),
            n('us', 'US Punk'),
            n('anarcho', 'Anarcho-Punk'),
            n('street', 'Street Punk'),
            n('pop', 'Pop-Punk'),
            n('skate', 'Skate Punk'),
            n('horror', 'Horror Punk'),
          ], aliases: ['punk rock', 'punk']),
        n('hardcore', 'Hardcore Punk', children: [
            n('american', 'American Hardcore'),
            n('nyc', 'NYC Hardcore'),
            n('dc', 'DC Hardcore', geographies: ['geo.dc']),
            n('california', 'California Hardcore'),
            n('youth_crew', 'Youth Crew'),
            n('crossover_thrash', 'Crossover Thrash', aliases: ['crossover', 'crossover thrash'], secondary: ['metal.thrash']),
            n('crust', 'Crust Punk'),
            n('d_beat', 'D-Beat'),
            n('powerviolence', 'Powerviolence'),
            n('beatdown', 'Beatdown Hardcore'),
            n('metallic', 'Metallic Hardcore'),
          ], aliases: ['hardcore', 'hardcore punk']),
        n('postpunk', 'Post-Punk', children: [
            n('gothic', 'Gothic Rock'),
            n('coldwave', 'Coldwave'),
            n('deathrock', 'Deathrock'),
            n('no_wave', 'No Wave', scenes: ['scene.no_wave']),
          ], aliases: ['post-punk', 'post punk', 'rock.postpunk']),
        n('emo', 'Emo', children: [
            n('emocore', 'Emocore'),
            n('midwest', 'Midwest Emo'),
            n('screamo', 'Screamo'),
            n('emo_pop', 'Emo Pop'),
          ], aliases: ['emo', 'emocore']),
        n('posthardcore', 'Post-Hardcore', children: [
            n('skramz', 'Skramz'),
            n('mathcore', 'Mathcore'),
            n('melodic', 'Melodic Post-Hardcore'),
          ], aliases: ['post-hardcore', 'post hardcore']),
        n('grind', 'Grindcore', children: [
            n('goregrind', 'Goregrind'),
            n('noisegrind', 'Noisegrind'),
            n('cybergrind', 'Cybergrind'),
          ], aliases: ['grindcore', 'grind'], secondary: ['metal']),
      ], aliases: ['punk'], lore: '## Punk e Hardcore\nProto, 77, hardcore e post-punk são rios distintos. Grind visita o metal sem se apagar nele.'),
]);

List<MusicTaxon> canonMetal() => flattenCanon([
    n('metal', 'Metal', children: [
        n('trad', 'Traditional Heavy Metal', children: [
            n('nwobhm', 'NWOBHM', aliases: ['nwobhm'], scenes: ['scene.nwobhm']),
            n('us_power', 'US Traditional Power'),
          ], aliases: ['heavy metal', 'traditional metal']),
        n('speed', 'Speed Metal', aliases: ['speed metal']),
        n('thrash', 'Thrash Metal', children: [
            n('bay_area', 'Bay Area Thrash', scenes: ['scene.bay_area_thrash'], geographies: ['geo.bay_area']),
            n('teutonic', 'Teutonic Thrash'),
            n('technical', 'Technical Thrash'),
            n('crossover', 'Thrash Crossover', secondary: ['punk.hardcore.crossover_thrash']),
          ], aliases: ['thrash', 'thrash metal']),
        n('doom', 'Doom Metal', children: [
            n('traditional', 'Traditional Doom'),
            n('epic', 'Epic Doom'),
            n('funeral', 'Funeral Doom'),
            n('death_doom', 'Death-Doom'),
            n('drone', 'Drone Doom'),
          ], aliases: ['doom', 'doom metal']),
        n('death', 'Death Metal', children: [
            n('old_school', 'Old School Death Metal'),
            n('florida', 'Florida Death Metal'),
            n('gothenburg', 'Gothenburg / Melodeath', aliases: ['melodeath', 'melodic death'], scenes: ['scene.gothenburg_death']),
            n('technical', 'Technical Death Metal'),
            n('brutal', 'Brutal Death Metal'),
            n('dissonant', 'Dissonant Death Metal'),
            n('slam', 'Slam Death Metal'),
            n('progressive', 'Progressive Death Metal'),
          ], aliases: ['death metal', 'death']),
        n('black', 'Black Metal', children: [
            n('first_wave', 'First Wave Black Metal'),
            n('second_wave', 'Second Wave / Norwegian', scenes: ['scene.norwegian_bm'], geographies: ['geo.norway']),
            n('atmospheric', 'Atmospheric Black Metal'),
            n('depressive', 'Depressive Black Metal'),
            n('raw', 'Raw Black Metal'),
            n('symphonic', 'Symphonic Black Metal'),
            n('folk', 'Folk Black Metal'),
            n('industrial', 'Industrial Black Metal'),
            n('blackgaze', 'Blackgaze', aliases: ['blackgaze'], secondary: ['rock.alt.shoegaze']),
            n('war', 'War Metal'),
            n('orthodox', 'Orthodox Black Metal'),
            n('post', 'Post-Black Metal'),
          ], aliases: ['black metal', 'black']),
        n('power', 'Power Metal', children: [
            n('us', 'US Power Metal'),
            n('european', 'European Power Metal'),
            n('japanese', 'Japanese Power Metal'),
            n('symphonic', 'Symphonic Power Metal'),
          ], aliases: ['power metal']),
        n('prog', 'Progressive Metal', children: [
            n('djent', 'Djent'),
            n('tech', 'Technical Progressive Metal'),
          ], aliases: ['prog metal', 'progressive metal']),
        n('groove', 'Groove Metal', aliases: ['groove metal']),
        n('sludge', 'Sludge Metal', aliases: ['sludge']),
        n('stoner', 'Stoner Metal', aliases: ['stoner metal', 'stoner']),
        n('gothic', 'Gothic Metal'),
        n('symphonic', 'Symphonic Metal'),
        n('folk', 'Folk Metal'),
        n('industrial', 'Industrial Metal', secondary: ['industrial.industrial_metal']),
        n('alt', 'Alternative Metal'),
        n('funk', 'Funk Metal', secondary: ['funk.metal']),
        n('rap', 'Rap Metal', secondary: ['hiphop']),
        n('nu', 'Nu Metal', aliases: ['nu-metal', 'numetal']),
        n('metalcore', 'Metalcore', children: [
            n('melodic', 'Melodic Metalcore'),
            n('metallic', 'Metallic Hardcore Metalcore'),
            n('progressive', 'Progressive Metalcore'),
          ], aliases: ['metalcore']),
        n('deathcore', 'Deathcore', aliases: ['deathcore']),
        n('post', 'Post-Metal', aliases: ['post-metal', 'post metal', 'metal.post']),
        n('avant', 'Avant-Garde Metal'),
        n('viking', 'Viking Metal'),
        n('pagan', 'Pagan Metal'),
      ], aliases: ['metal', 'heavy metal'], lore: '## Metal\nFamília de densidade. Doom, black e post importam mais do que o guarda-chuva.'),
]);

List<MusicTaxon> canonPop() => flattenCanon([
    n('pop', 'Pop', children: [
        n('traditional', 'Traditional Pop'),
        n('brill_building', 'Brill Building Pop'),
        n('teen', 'Teen Pop'),
        n('sunshine', 'Sunshine Pop'),
        n('bubblegum', 'Bubblegum Pop'),
        n('baroque', 'Baroque Pop'),
        n('sophisti', 'Sophisti-Pop'),
        n('adult_contemporary', 'Adult Contemporary'),
        n('synth', 'Synth-Pop', aliases: ['synthpop', 'synth-pop']),
        n('dance', 'Dance-Pop'),
        n('europop', 'Europop'),
        n('latin_pop', 'Latin Pop', secondary: ['latin']),
        n('electropop', 'Electropop'),
        n('indie_pop', 'Indie Pop', secondary: ['rock.alt.indie.pop']),
        n('art_pop', 'Art Pop'),
        n('chamber_pop', 'Chamber Pop'),
        n('dream', 'Dream Pop Pop-side', secondary: ['rock.alt.dream_pop']),
        n('hypnagogic', 'Hypnagogic Pop'),
        n('vapor', 'Vapor Pop', secondary: ['electronic.vaporwave']),
        n('hyperpop', 'Hyperpop', aliases: ['hyperpop']),
        n('glitch_pop', 'Glitch Pop'),
        n('bitpop', 'Bitpop', secondary: ['electronic.chiptune']),
        n('city_pop', 'City Pop', aliases: ['city pop']),
        n('jpop', 'J-Pop', children: [
            n('idol', 'Japanese Idol Pop'),
            n('shibuya', 'Shibuya-kei Pop', scenes: ['scene.shibuya_kei']),
            n('city', 'Japanese City Pop'),
          ], aliases: ['j-pop', 'jpop']),
        n('kpop', 'K-Pop', children: [
            n('idol', 'K-Pop Idol'),
            n('trot_pop', 'Trot-Pop'),
          ], aliases: ['k-pop', 'kpop']),
        n('cpop', 'C-Pop', children: [
            n('mandopop', 'Mandopop'),
            n('cantopop', 'Cantopop'),
            n('hokkien', 'Hokkien Pop'),
          ], aliases: ['c-pop', 'cpop']),
        n('french', 'French Pop'),
        n('italian', 'Italian Pop'),
        n('swedish', 'Swedish Pop'),
        n('contemporary', 'Contemporary Pop'),
        n('alt_pop', 'Alternative Pop'),
        n('bedroom', 'Bedroom Pop'),
      ], aliases: ['pop'], lore: '## Pop\nDo Brill Building ao hyperpop. J-pop, K-pop e C-pop são rios regionais, não \'o mesmo pop com sotaque\'.'),
]);

List<MusicTaxon> canonHiphop() => flattenCanon([
    n('hiphop', 'Hip-Hop', children: [
        n('old_school', 'Old School Hip-Hop', aliases: ['old school', 'old-school hip hop']),
        n('golden', 'Golden Age Hip-Hop'),
        n('east', 'East Coast', children: [
            n('boom_bap', 'Boom-Bap', aliases: ['boom bap', 'boom-bap', 'hiphop.boombap']),
            n('jazz_rap', 'Jazz Rap', aliases: ['jazz rap', 'hiphop.jazzrap', 'jazz-rap']),
            n('hardcore', 'East Coast Hardcore Rap'),
            n('mafioso', 'Mafioso Rap'),
            n('horrorcore', 'Horrorcore'),
            n('conscious', 'Conscious Rap'),
          ], aliases: ['east coast hip hop']),
        n('west', 'West Coast', children: [
            n('g_funk', 'G-Funk'),
            n('gangsta', 'Gangsta Rap'),
            n('hyphy', 'Hyphy'),
            n('latin', 'Latin West Coast Rap'),
          ], aliases: ['west coast hip hop']),
        n('south', 'Southern Hip-Hop', children: [
            n('miami_bass', 'Miami Bass'),
            n('crunk', 'Crunk'),
            n('snap', 'Snap'),
            n('bounce', 'New Orleans Bounce', geographies: ['geo.new_orleans']),
            n('chopped', 'Chopped and Screwed'),
          ], aliases: ['southern hip hop', 'dirty south']),
        n('midwest', 'Midwest Hip-Hop', children: [
            n('chopper', 'Chopper'),
            n('chicago', 'Chicago Hip-Hop', geographies: ['geo.chicago']),
          ], aliases: ['midwest hip hop']),
        n('alternative', 'Alternative Hip-Hop'),
        n('experimental', 'Experimental Hip-Hop', aliases: ['experimental hip hop', 'abstract hip hop']),
        n('industrial', 'Industrial Hip-Hop'),
        n('cloud', 'Cloud Rap'),
        n('emo_rap', 'Emo Rap'),
        n('mumble', 'Mumble Rap'),
        n('trap', 'Trap', children: [
            n('phonk', 'Phonk'),
            n('plugg', 'Plugg'),
            n('rage', 'Rage Rap'),
          ], aliases: ['trap']),
        n('drill', 'Drill', children: [
            n('chicago', 'Chicago Drill'),
            n('uk', 'UK Drill'),
            n('brooklyn', 'Brooklyn Drill'),
          ], aliases: ['drill']),
        n('grime', 'Grime', aliases: ['grime'], secondary: ['electronic']),
        n('uk', 'UK Hip-Hop', children: [
            n('garage_rap', 'UK Garage Rap'),
            n('road_rap', 'Road Rap'),
            n('afroswing', 'Afroswing'),
          ]),
        n('brazilian', 'Hip-Hop Brasileiro', children: [
            n('rap_nacional', 'Rap Nacional'),
            n('trap_br', 'Trap BR'),
            n('funk_rap', 'Rap-Funk Carioca', secondary: ['brazilian.funk_br']),
          ], aliases: ['rap nacional', 'hip hop brasileiro']),
        n('french', 'French Hip-Hop'),
        n('german', 'German Hip-Hop'),
        n('lofi', 'Lo-Fi Hip-Hop'),
        n('turntablism', 'Turntablism'),
        n('nerdcore', 'Nerdcore'),
        n('political', 'Political Hip-Hop'),
        n('christian', 'Christian Hip-Hop'),
      ], aliases: ['hip hop', 'hip-hop', 'rap', 'hiphop'], lore: '## Hip-Hop\nTerritório de amostra, de sala e de esquina. Boom-bap, jazz-rap e trap são bairros, não \'eras\' únicas.'),
]);

List<MusicTaxon> canonReggae() => flattenCanon([
    n('reggae', 'Reggae e Música Jamaicana', children: [
        n('mento', 'Mento'),
        n('ska', 'Ska', children: [
            n('first_wave', 'First-Wave Ska'),
            n('two_tone', '2 Tone'),
            n('third_wave', 'Third-Wave Ska'),
          ], aliases: ['ska']),
        n('rocksteady', 'Rocksteady', aliases: ['rocksteady']),
        n('early', 'Early Reggae'),
        n('roots', 'Roots Reggae'),
        n('dub', 'Dub', aliases: ['dub']),
        n('rockers', 'Rockers'),
        n('lovers', 'Lovers Rock'),
        n('steppers', 'Steppers'),
        n('nyabinghi', 'Nyabinghi'),
        n('dancehall', 'Dancehall', children: [
            n('early', 'Early Dancehall'),
            n('digital', 'Digital Dancehall'),
            n('modern', 'Modern Dancehall'),
          ], aliases: ['dancehall']),
        n('ragga', 'Ragga'),
        n('reggae_fusion', 'Reggae Fusion'),
        n('british', 'British Reggae'),
        n('spanish', 'Spanish Reggae'),
        n('pacific', 'Pacific Reggae'),
      ], aliases: ['reggae'], geographies: ['geo.kingston'], lore: '## Reggae e Música Jamaicana\nMento, ska, rocksteady e dub não são subpastas de um único verão.'),
]);

List<MusicTaxon> canonElectronic() => flattenCanon([
    n('electronic', 'Electronic', children: [
        n('early', 'Early Electronic', children: [
            n('tape', 'Early Tape Music'),
            n('berlin_school', 'Berlin School'),
            n('kosmische', 'Kosmische Electronic'),
            n('radiophonic', 'Radiophonic Workshop'),
            n('proto_synth', 'Proto-Synth'),
          ], aliases: ['early electronic']),
        n('ambient', 'Ambient', children: [
            n('dark', 'Dark Ambient'),
            n('drone', 'Ambient Drone'),
            n('space', 'Space Ambient'),
            n('isolationist', 'Isolationism'),
            n('lowercase', 'Lowercase Ambient'),
            n('illbient', 'Illbient'),
            n('ambient_house', 'Ambient House'),
            n('ambient_techno', 'Ambient Techno'),
            n('tribal', 'Tribal Ambient'),
          ], aliases: ['ambient', 'electronic.ambient']),
        n('disco', 'Disco', children: [
            n('proto', 'Proto-Disco'),
            n('philadelphia', 'Philadelphia Disco'),
            n('eurodisco', 'Eurodisco'),
            n('italo', 'Italo Disco'),
            n('hi_nrg', 'Hi-NRG'),
            n('cosmic', 'Cosmic Disco'),
            n('space', 'Space Disco'),
            n('boogie', 'Boogie'),
            n('post', 'Post-Disco'),
            n('nu', 'Nu-Disco'),
            n('french', 'French Disco / Touch', scenes: ['scene.french_touch']),
          ], aliases: ['disco']),
        n('house', 'House', children: [
            n('chicago', 'Chicago House', aliases: ['chicago house'], scenes: ['scene.chicago_house'], geographies: ['geo.chicago']),
            n('deep', 'Deep House'),
            n('acid', 'Acid House'),
            n('progressive', 'Progressive House'),
            n('tribal', 'Tribal House'),
            n('vocal', 'Vocal House'),
            n('garage', 'New York Garage'),
            n('funky', 'Funky House'),
            n('tech', 'Tech House'),
            n('electro', 'Electro House'),
            n('microhouse', 'Microhouse'),
            n('minimal', 'Minimal House'),
            n('tropical', 'Tropical House'),
            n('future', 'Future House'),
            n('ghetto', 'Ghetto House'),
            n('jackin', 'Jackin House'),
            n('soulful', 'Soulful House'),
            n('afro', 'Afro House'),
            n('french', 'French House', scenes: ['scene.french_touch']),
            n('filter', 'Filter House'),
            n('fidget', 'Fidget House'),
            n('organic', 'Organic House'),
            n('melodic', 'Melodic House'),
          ], aliases: ['house']),
        n('techno', 'Techno', children: [
            n('detroit', 'Detroit Techno', aliases: ['detroit techno'], scenes: ['scene.detroit_techno'], geographies: ['geo.detroit']),
            n('acid', 'Acid Techno'),
            n('minimal', 'Minimal Techno'),
            n('dub', 'Dub Techno'),
            n('hard', 'Hard Techno'),
            n('industrial', 'Industrial Techno'),
            n('schranz', 'Schranz'),
            n('ambient', 'Ambient Techno Room'),
            n('bleep', 'Bleep Techno'),
            n('birmingham', 'Birmingham Techno'),
            n('berlin', 'Berlin Techno', geographies: ['geo.berlin']),
            n('loft', 'Loft Techno'),
            n('ghettotech', 'Ghettotech'),
            n('hardgroove', 'Hardgroove'),
            n('raw', 'Raw Techno'),
            n('peak_time', 'Peak-Time Techno'),
            n('warehouse', 'Warehouse Techno'),
            n('melodic', 'Melodic Techno'),
            n('hypnotic', 'Hypnotic Techno'),
            n('outsider', 'Outsider Techno'),
          ], aliases: ['techno']),
        n('trance', 'Trance', children: [
            n('goa', 'Goa Trance'),
            n('psy', 'Psytrance', children: [
                n('full_on', 'Full-On'),
                n('dark_psy', 'Dark Psy'),
                n('forest', 'Forest Psy'),
                n('progressive_psy', 'Progressive Psy'),
                n('hitech', 'Hi-Tech Psy'),
              ], aliases: ['psytrance', 'psy']),
            n('progressive', 'Progressive Trance'),
            n('uplifting', 'Uplifting Trance'),
            n('vocal', 'Vocal Trance'),
            n('tech', 'Tech Trance'),
            n('hard', 'Hard Trance'),
            n('acid', 'Acid Trance'),
            n('balearic', 'Balearic Trance'),
            n('dream', 'Dream Trance'),
            n('euro', 'Eurotrance'),
            n('classic', 'Classic Trance'),
          ], aliases: ['trance']),
        n('breaks', 'Breaks', children: [
            n('big_beat', 'Big Beat'),
            n('florida', 'Florida Breaks'),
            n('nu_skool', 'Nu Skool Breaks'),
            n('chemical', 'Chemical Breaks'),
            n('hardcore', 'Breakbeat Hardcore'),
            n('acid', 'Acid Breaks'),
            n('progressive', 'Progressive Breaks'),
            n('atmospheric', 'Atmospheric Breaks'),
          ], aliases: ['breaks', 'breakbeat']),
        n('jungle', 'Jungle', children: [
            n('ragga', 'Ragga Jungle'),
            n('darkside', 'Darkside Jungle'),
            n('intelligent', 'Intelligent Jungle'),
            n('jump_up', 'Jump-Up Jungle'),
          ], aliases: ['jungle']),
        n('dnb', 'Drum and Bass', children: [
            n('atmospheric', 'Atmospheric Drum and Bass'),
            n('liquid', 'Liquid Funk'),
            n('jump_up', 'Jump-Up'),
            n('techstep', 'Techstep'),
            n('darkstep', 'Darkstep'),
            n('neurofunk', 'Neurofunk', aliases: ['neurofunk', 'neuro']),
            n('roller', 'Rollers'),
            n('sambass', 'Sambass', secondary: ['brazilian']),
            n('minimal', 'Minimal DnB'),
            n('dancefloor', 'Dancefloor DnB'),
          ], aliases: ['drum and bass', 'dnb', 'dnB', 'drum & bass']),
        n('hardcore', 'Hardcore Electronic', children: [
            n('rave', 'Early Rave'),
            n('breakbeat', 'UK Breakbeat Hardcore'),
            n('gabber', 'Gabber'),
            n('happy', 'Happy Hardcore'),
            n('uk', 'UK Hardcore'),
            n('frenchcore', 'Frenchcore'),
            n('makina', 'Mákina'),
            n('speedcore', 'Speedcore'),
            n('terror', 'Terrorcore'),
            n('splittercore', 'Splittercore'),
            n('freeform', 'Freeform Hardcore'),
            n('bouncy', 'Bouncy Techno'),
            n('hardstyle', 'Hardstyle', children: [
                n('rawstyle', 'Rawstyle'),
                n('euphoric', 'Euphoric Hardstyle'),
              ], aliases: ['hardstyle']),
            n('crossbreed', 'Crossbreed'),
          ], aliases: ['hardcore techno', 'rave hardcore']),
        n('garage', 'UK Garage', children: [
            n('uk', 'Classic UKG'),
            n('2step', '2-Step'),
            n('speed', 'Speed Garage'),
            n('future', 'Future Garage'),
            n('bassline', 'Bassline'),
            n('4x4', '4x4 Garage'),
          ], aliases: ['uk garage', 'ukg']),
        n('dubstep', 'Dubstep', children: [
            n('early', 'Early / Dark Dubstep'),
            n('brostep', 'Brostep'),
            n('riddim', 'Riddim'),
            n('tearout', 'Tearout'),
            n('deep', 'Deep Dubstep'),
            n('future_garage', 'Future Garage Dubstep'),
            n('post', 'Post-Dubstep'),
            n('purple', 'Purple Sound'),
            n('deathstep', 'Deathstep'),
            n('melodic', 'Melodic Dubstep'),
          ], aliases: ['dubstep']),
        n('idm', 'IDM', children: [
            n('glitch', 'Glitch'),
            n('drill_n_bass', 'Drill n Bass'),
            n('microsound', 'Microsound'),
            n('flashcore', 'Flashcore'),
            n('algorithmic', 'Algorithmic IDM'),
            n('glitch_hop', 'Glitch Hop'),
          ], aliases: ['idm', 'braindance', 'electronic.idm', 'intelligent dance music']),
        n('electro', 'Electro', children: [
            n('freestyle', 'Freestyle'),
            n('miami', 'Miami Electro'),
            n('techno_bass', 'Techno Bass'),
            n('electroclash', 'Electroclash'),
            n('synth', 'Synth Electro'),
          ], aliases: ['electro']),
        n('downtempo', 'Downtempo', children: [
            n('trip_hop', 'Trip-Hop', aliases: ['trip-hop', 'trip hop'], scenes: ['scene.bristol_triphop']),
            n('chillout', 'Chillout'),
            n('lounge', 'Lounge'),
            n('psybient', 'Psybient'),
            n('chillwave', 'Chillwave'),
            n('lofi', 'Lo-Fi Electronic'),
          ], aliases: ['downtempo']),
        n('bass', 'Bass Music', children: [
            n('uk', 'UK Bass'),
            n('future', 'Future Bass'),
            n('wave', 'Wave'),
            n('trap_edm', 'Trap EDM'),
            n('midtempo', 'Midtempo Bass'),
            n('halftime', 'Halftime'),
            n('one40', '140 Bass'),
          ], aliases: ['bass music']),
        n('footwork', 'Footwork', children: [
            n('juke', 'Juke'),
            n('ghetto_house', 'Ghetto House Footwork'),
            n('jersey', 'Jersey Club Adjacent'),
          ], aliases: ['footwork', 'juke']),
        n('club', 'Regional Club', children: [
            n('baile', 'Baile Funk', aliases: ['baile funk', 'funk carioca club'], secondary: ['brazilian.funk_br']),
            n('gqom', 'Gqom Club', secondary: ['african.gqom']),
            n('amapiano', 'Amapiano Club', secondary: ['african.amapiano']),
            n('ballroom', 'Ballroom / Vogue'),
            n('jersey_club', 'Jersey Club'),
            n('baltimore', 'Baltimore Club'),
            n('philadelphia', 'Philly Club'),
            n('booty', 'Booty Bass'),
            n('kuduro', 'Kuduro Club', secondary: ['african.kuduro']),
            n('tarraxinha', 'Tarraxinha'),
            n('afrohouse', 'Afrohouse Club'),
            n('singeli', 'Singeli Club', secondary: ['african.east.singeli']),
            n('shangaan', 'Shangaan Electro'),
            n('batida', 'Batida'),
            n('bubbling', 'Bubbling'),
            n('dembow_club', 'Dembow Club', secondary: ['latin.reggaeton']),
            n('moombahton', 'Moombahton'),
            n('moombahcore', 'Moombahcore'),
          ], aliases: ['club', 'regional club']),
        n('vaporwave', 'Vaporwave', children: [
            n('mallsoft', 'Mallsoft'),
            n('future_funk', 'Future Funk'),
            n('hardvapour', 'Hardvapour'),
            n('signalwave', 'Signalwave'),
            n('vaportrap', 'Vaportrap'),
            n('slushwave', 'Slushwave'),
          ], aliases: ['vaporwave']),
        n('synthwave', 'Synthwave', children: [
            n('darksynth', 'Darksynth'),
            n('retrowave', 'Retrowave'),
            n('outrun', 'Outrun'),
            n('chillsynth', 'Chillsynth'),
            n('spacesynth', 'Spacesynth'),
          ], aliases: ['synthwave']),
        n('edm', 'Festival EDM', children: [
            n('progressive_house', 'Festival Progressive House'),
            n('big_room', 'Big Room'),
            n('complextro', 'Complextro'),
            n('bounce', 'Melbourne Bounce'),
            n('festival', 'Festival House'),
          ], aliases: ['edm']),
        n('chiptune', 'Chiptune', children: [
            n('bitpop', 'Bitpop Chip'),
            n('nintendocore', 'Nintendocore'),
            n('8bit', '8-bit'),
          ], aliases: ['chiptune', 'chipmusic']),
        n('leftfield', 'Leftfield Electronic'),
        n('experimental_electronic', 'Experimental Electronic'),
        n('space_music', 'Space Music'),
      ], aliases: ['electronic', 'electronica'], lore: '## Electronic\nFamília de relógios e salas. Jungle precede DnB; neurofunk é um bairro, não um sinónimo de \'bass pesado\'.'),
]);

List<MusicTaxon> canonIndustrial() => flattenCanon([
    n('industrial', 'Industrial e Noise', children: [
        n('first_wave', 'First-Wave Industrial'),
        n('power_electronics', 'Power Electronics'),
        n('death_industrial', 'Death Industrial'),
        n('martial', 'Martial Industrial'),
        n('neofolk', 'Neofolk Industrial Side', secondary: ['folk.contemporary.neofolk']),
        n('ebm', 'EBM', aliases: ['ebm', 'electronic body music']),
        n('electro_industrial', 'Electro-Industrial'),
        n('aggrotech', 'Aggrotech'),
        n('industrial_rock', 'Industrial Rock', secondary: ['rock']),
        n('industrial_metal', 'Industrial Metal', secondary: ['metal.industrial']),
        n('noise', 'Noise', children: [
            n('harsh', 'Harsh Noise'),
            n('japanoise', 'Japanoise'),
            n('wall', 'Harsh Noise Wall'),
            n('power', 'Power Noise'),
          ], aliases: ['noise']),
        n('dark_ambient', 'Industrial Dark Ambient', secondary: ['electronic.ambient.dark']),
        n('ritual', 'Ritual Industrial'),
        n('witch_house', 'Witch House'),
      ], aliases: ['industrial'], lore: '## Industrial e Noise\nThrobbing Gristle não é um mood. Noise é eixo próprio, não \'industrial mais alto\'.'),
]);

List<MusicTaxon> canonExperimental() => flattenCanon([
    n('experimental', 'Experimental e Avant-Garde', children: [
        n('avant_garde', 'Avant-Garde'),
        n('free_improv', 'Free Improvisation', aliases: ['free improvisation', 'free improv']),
        n('electroacoustic', 'Electroacoustic Experimental'),
        n('sound_art', 'Sound Art Practice', functions: ['function.sound_art']),
        n('lowercase', 'Lowercase'),
        n('onkyo', 'Onkyō'),
        n('wandelweiser', 'Wandelweiser'),
        n('reductionism', 'Reductionism'),
        n('noise', 'Experimental Noise', secondary: ['industrial.noise']),
        n('drone', 'Experimental Drone'),
        n('avant_folk', 'Avant-Folk'),
        n('outsider', 'Outsider Music'),
        n('fluxus', 'Fluxus Music', movements: ['movement.fluxus']),
        n('conceptual', 'Conceptual Music'),
        n('eai', 'EAI'),
        n('microsound', 'Experimental Microsound'),
        n('graphic', 'Graphic Score Music'),
        n('process', 'Process / Systems Music'),
        n('tape', 'Experimental Tape'),
      ], aliases: ['experimental', 'avant-garde'], lore: '## Experimental e Avant-Garde\nNão é um adjectivo para o que não encaixa. É um rio com escolas, não um caixote.'),
]);

List<MusicTaxon> canonBrazilian() => flattenCanon([
    n('brazilian', 'Música Brasileira', children: [
        n('samba', 'Samba', children: [
            n('roda', 'Samba de Roda'),
            n('partido_alto', 'Partido Alto'),
            n('enredo', 'Samba-Enredo'),
            n('pagode', 'Pagode'),
            n('pagode_romantico', 'Pagode Romântico'),
            n('samba_cancao', 'Samba-Canção'),
            n('breque', 'Samba de Breque'),
            n('samba_rock', 'Samba-Rock'),
            n('jazz', 'Samba-Jazz', secondary: ['jazz.latin.brazilian.samba_jazz']),
            n('rap', 'Samba-Rap'),
          ], aliases: ['samba', 'br.samba']),
        n('choro', 'Choro', children: [
            n('tradicional', 'Choro Tradicional'),
            n('contemporaneo', 'Choro Contemporâneo'),
            n('chorinho', 'Chorinho'),
          ], aliases: ['choro', 'chorinho'], forms: ['form.choro']),
        n('bossa', 'Bossa Nova', children: [
            n('jazz', 'Bossa Jazz', secondary: ['jazz.latin.brazilian.bossa_jazz']),
            n('contemporanea', 'Bossa Contemporânea'),
          ], aliases: ['bossa', 'bossa nova', 'br.bossa']),
        n('mpb', 'MPB', children: [
            n('primeira', 'Primeira Geração MPB'),
            n('segunda', 'Segunda Geração MPB'),
            n('contemporanea', 'MPB Contemporânea'),
            n('universitaria', 'MPB Universitária'),
          ], aliases: ['mpb', 'br.mpb', 'musica popular brasileira'], lore: '## MPB\nMacro pós-1960. Não é pai do samba nem do choro — é um arquivo de canção urbana depois da bossa.'),
        n('tropicalia', 'Tropicália', aliases: ['tropicália', 'tropicalia', 'tropicalismo', 'br.tropicalia'], scenes: ['scene.tropicalia'], movements: ['movement.tropicalismo']),
        n('clube_da_esquina', 'Clube da Esquina', aliases: ['clube da esquina'], scenes: ['scene.clube_da_esquina'], geographies: ['geo.minas_gerais']),
        n('nordeste', 'Nordeste', children: [
            n('forro', 'Forró', children: [
                n('pe_de_serra', 'Pé-de-Serra'),
                n('eletronico', 'Forró Eletrônico'),
                n('universitario', 'Forró Universitário'),
              ], aliases: ['forro', 'forró']),
            n('baiao', 'Baião'),
            n('xote', 'Xote'),
            n('xaxado', 'Xaxado'),
            n('coco', 'Coco'),
            n('ciranda', 'Ciranda'),
            n('maracatu', 'Maracatu'),
            n('frevo', 'Frevo'),
            n('embolada', 'Embolada'),
            n('repentismo', 'Repentismo / Cantoria'),
            n('caboclinhos', 'Caboclinhos'),
            n('reisado', 'Reisado'),
          ], aliases: ['nordeste', 'música nordestina']),
        n('sertanejo', 'Sertanejo', children: [
            n('raiz', 'Sertanejo de Raiz'),
            n('caipira', 'Música Caipira'),
            n('universitaria', 'Sertanejo Universitário'),
            n('sertanejo_pop', 'Sertanejo Pop'),
            n('feminejo', 'Feminejo'),
          ], aliases: ['sertanejo']),
        n('amazonia', 'Amazônia', children: [
            n('carimbo', 'Carimbó'),
            n('lundu_amazonico', 'Lundu Amazônico'),
            n('siria', 'Siriá'),
            n('boi', 'Boi-Bumbá'),
            n('retumbao', 'Retumbão'),
            n('lambada', 'Lambada'),
          ], aliases: ['amazonia', 'música amazônica']),
        n('axe', 'Axé', children: [
            n('pagode_baiano', 'Pagode Baiano'),
            n('arrocha', 'Arrocha'),
            n('swingueira', 'Swingueira'),
            n('samba_reggae', 'Samba-Reggae'),
            n('ijexa', 'Ijexá Pop'),
          ], aliases: ['axe', 'axé'], geographies: ['geo.salvador']),
        n('funk_br', 'Funk Brasileiro', children: [
            n('carioca', 'Funk Carioca'),
            n('ostentacao', 'Funk Ostentação'),
            n('consciente', 'Funk Consciente'),
            n('melody', 'Funk Melody'),
            n('proibidao', 'Proibidão'),
            n('bpm150', 'Funk 150 BPM'),
            n('montagem', 'Montagem'),
          ], aliases: ['funk carioca', 'baile funk', 'funk brasileiro'], secondary: ['electronic.club.baile'], geographies: ['geo.rio'], lore: '## Funk Brasileiro\nNão é o funk norte-americano. Rio, 150 BPM e baile são outra máquina.'),
        n('brega', 'Brega', children: [
            n('tecnobrega', 'Tecnobrega'),
            n('romantico', 'Brega Romântico'),
            n('calypso', 'Calypso Paraense'),
            n('bregadeira', 'Bregadeira'),
          ], aliases: ['brega']),
        n('black_rio', 'Black Rio', children: [
            n('soul_br', 'Soul Brasileiro'),
            n('funk_br_70s', 'Funk Black Rio'),
          ], aliases: ['black rio'], scenes: ['scene.black_rio'], geographies: ['geo.rio']),
        n('instrumental', 'Instrumental Brasileiro', children: [
            n('choro_instrumental', 'Choro Instrumental'),
            n('samba_instrumental', 'Samba Instrumental'),
            n('jazz_br', 'Jazz Instrumental Brasileiro'),
            n('guitarra', 'Guitarra Brasileira'),
          ], aliases: ['instrumental brasileiro']),
        n('manguebeat', 'Manguebeat', aliases: ['mangue', 'manguebeat', 'mangue bit'], scenes: ['scene.manguebeat'], geographies: ['geo.recife']),
        n('rock_br', 'Rock Brasileiro', secondary: ['rock']),
        n('metal_br', 'Metal Brasileiro', secondary: ['metal']),
        n('hiphop_br', 'Hip-Hop Brasileiro Macro', secondary: ['hiphop.brazilian']),
        n('maxixe', 'Maxixe'),
        n('lundu', 'Lundu'),
        n('modinha', 'Modinha'),
        n('marcha', 'Marcha'),
        n('jongo', 'Jongo'),
        n('afoxe', 'Afoxé'),
        n('capoeira', 'Capoeira Music'),
        n('gaucho', 'Música Gaúcha', children: [
            n('vanera', 'Vanera'),
            n('chimarrita', 'Chimarrita'),
          ]),
      ], aliases: ['brazilian', 'brasil', 'musica brasileira', 'música brasileira'], lore: '## Música Brasileira\nNão é um género. Samba, choro, bossa e MPB são rios irmãos — MPB não adopta os outros.'),
]);

List<MusicTaxon> canonLatin() => flattenCanon([
    n('latin', 'Música Latina e Caribenha', children: [
        n('cuba', 'Cuba', children: [
            n('son', 'Son Cubano'),
            n('rumba', 'Rumba Cubana'),
            n('mambo', 'Mambo'),
            n('cha_cha', 'Cha-Cha-Chá'),
            n('danzon', 'Danzón'),
            n('timba', 'Timba'),
            n('nueva_trova', 'Nueva Trova'),
            n('filin', 'Filin'),
            n('comparsa', 'Comparsa'),
            n('changui', 'Changüí'),
          ], aliases: ['cuban music', 'musica cubana'], geographies: ['geo.havana']),
        n('salsa', 'Salsa', children: [
            n('dura', 'Salsa Dura'),
            n('romantica', 'Salsa Romántica'),
            n('ny', 'New York Salsa'),
            n('colombian', 'Salsa Colombiana'),
          ], aliases: ['salsa']),
        n('puerto', 'Porto Rico', children: [
            n('bomba', 'Bomba'),
            n('plena', 'Plena'),
            n('salsa', 'Salsa Puertorriqueña'),
          ], aliases: ['puerto rican music'], geographies: ['geo.san_juan']),
        n('dominican', 'República Dominicana', children: [
            n('merengue', 'Merengue'),
            n('bachata', 'Bachata'),
            n('dembow', 'Dembow Dominicano'),
          ], aliases: ['dominican music']),
        n('reggaeton', 'Reggaeton', children: [
            n('old_school', 'Old-School Reggaeton'),
            n('modern', 'Modern Reggaeton'),
            n('latin_trap', 'Latin Trap'),
          ], aliases: ['reggaeton', 'reguetón']),
        n('colombia', 'Colômbia', children: [
            n('cumbia', 'Cumbia'),
            n('vallenato', 'Vallenato'),
            n('porro', 'Porro'),
            n('champeta', 'Champeta'),
            n('salsa_colombiana', 'Salsa Colombiana Scene'),
            n('mapale', 'Mapalé'),
          ], aliases: ['colombian music']),
        n('venezuela', 'Venezuela', children: [
            n('joropo', 'Joropo'),
            n('gaita', 'Gaita Zuliana'),
          ], aliases: ['venezuelan music']),
        n('argentina', 'Argentina', children: [
            n('tango', 'Tango'),
            n('nuevo_tango', 'Nuevo Tango'),
            n('folklore', 'Folklore Argentino'),
            n('chacarera', 'Chacarera'),
            n('zamba', 'Zamba'),
            n('chamame', 'Chamame'),
            n('cumbia_villera', 'Cumbia Villera'),
            n('rock_nacional', 'Rock Nacional'),
          ], aliases: ['argentine music'], geographies: ['geo.buenos_aires']),
        n('mexico', 'México', children: [
            n('son_jarocho', 'Son Jarocho'),
            n('son_huasteco', 'Son Huasteco'),
            n('mariachi', 'Mariachi'),
            n('ranchera', 'Ranchera'),
            n('banda', 'Banda'),
            n('norteno', 'Norteño'),
            n('corrido', 'Corrido'),
            n('corridos_tumbados', 'Corridos Tumbados'),
            n('cumbia_mex', 'Cumbia Mexicana'),
            n('sonidero', 'Sonidero'),
            n('bolero', 'Bolero'),
            n('huapango', 'Huapango'),
          ], aliases: ['mexican music']),
        n('andean', 'Andina', children: [
            n('huayno', 'Huayno'),
            n('saya', 'Saya'),
            n('cueca', 'Cueca'),
            n('morenada', 'Morenada'),
            n('caporal', 'Caporales'),
          ], aliases: ['andean music']),
        n('peru', 'Peru', children: [
            n('vals_criollo', 'Vals Criollo'),
            n('lando', 'Landó'),
            n('festejo', 'Festejo'),
            n('chicha', 'Chicha'),
            n('cumbia_peruana', 'Cumbia Peruana'),
            n('tondero', 'Tondero'),
            n('marinera', 'Marinera'),
          ], aliases: ['peruvian music'], geographies: ['geo.lima']),
        n('nueva_cancion', 'Nueva Canción', children: [
            n('chile', 'Nueva Canción Chilena'),
            n('cancion_protesta', 'Canción de Protesta'),
          ], aliases: ['nueva cancion', 'nueva canción']),
        n('trinidad', 'Trinidad e Tobago', children: [
            n('calypso', 'Calypso'),
            n('soca', 'Soca'),
            n('steel_pan', 'Steel Pan / Steelband'),
            n('chutney', 'Chutney'),
          ], aliases: ['trinidadian music']),
        n('haiti', 'Haiti', children: [
            n('kompa', 'Kompa'),
            n('rara', 'Rara'),
            n('twoubadou', 'Twoubadou'),
            n('rasin', 'Rasin'),
          ], aliases: ['haitian music']),
        n('french_caribbean', 'Antilhas Francesas', children: [
            n('zouk', 'Zouk'),
            n('gwoka', 'Gwoka'),
            n('biguine', 'Biguine'),
            n('kadans', 'Kadans'),
            n('bouyon', 'Bouyon'),
          ], aliases: ['french caribbean']),
      ], aliases: ['latin', 'musica latina', 'música latina'], lore: '## Música Latina e Caribenha\nCuba, salsa, cumbia e tango não cabem numa prateleira \'Latino\'.'),
]);

List<MusicTaxon> canonAfrican() => flattenCanon([
    n('african', 'Música Africana Moderna', children: [
        n('highlife', 'Highlife', children: [
            n('ghanaian', 'Ghanaian Highlife'),
            n('nigerian', 'Nigerian Highlife'),
            n('burger', 'Burger Highlife'),
          ], aliases: ['highlife']),
        n('afrobeat', 'Afrobeat', aliases: ['afrobeat'], lore: '## Afrobeat\nLinhagem de Fela — politizada, longa, hipnótica. Não é Afrobeats.'),
        n('afrobeats', 'Afrobeats', children: [
            n('azonto', 'Azonto'),
            n('alte', 'Alte'),
          ], aliases: ['afrobeats'], lore: '## Afrobeats\nPop urbana da África Ocidental do século XXI. Plural de propósito: não é o Afrobeat de Fela.'),
        n('congo', 'Congo / Rumba Africana', children: [
            n('rumba', 'Congolese Rumba'),
            n('soukous', 'Soukous'),
            n('ndombolo', 'Ndombolo'),
            n('kwasa', 'Kwassa Kwassa'),
          ], aliases: ['congolese rumba', 'soukous']),
        n('east', 'África Oriental', children: [
            n('taarab', 'Taarab'),
            n('bongo_flava', 'Bongo Flava'),
            n('singeli', 'Singeli'),
            n('genge', 'Genge'),
            n('kadongo_kamu', 'Kadongo Kamu'),
          ], aliases: ['east african']),
        n('gqom', 'Gqom', aliases: ['gqom']),
        n('amapiano', 'Amapiano', children: [
            n('private_school', 'Private School Amapiano'),
            n('piano', 'Piano Amapiano'),
          ], aliases: ['amapiano']),
        n('mbaqanga', 'Mbaqanga'),
        n('kwaito', 'Kwaito'),
        n('afro_soul', 'Afro-Soul'),
        n('mbalax', 'Mbalax'),
        n('makossa', 'Makossa'),
        n('bikutsi', 'Bikutsi'),
        n('fuji', 'Fuji'),
        n('juju', 'Jùjú'),
        n('apala', 'Apala'),
        n('chimurenga', 'Chimurenga'),
        n('maskandi', 'Maskandi'),
        n('isicathamiya', 'Isicathamiya'),
        n('ethio_jazz', 'Ethio-Jazz'),
        n('desert_blues', 'Desert Blues'),
        n('tuareg', 'Tuareg Guitar'),
        n('benga', 'Benga'),
        n('coupe_decale', 'Coupé-Décalé'),
        n('zouglou', 'Zouglou'),
        n('kuduro', 'Kuduro'),
        n('kizomba', 'Kizomba'),
        n('semba', 'Semba'),
        n('morna', 'Morna'),
        n('coladeira', 'Coladeira'),
      ], aliases: ['african', 'african music'], lore: '## Música Africana Moderna\nAfrobeat e Afrobeats não são o mesmo rio. Highlife, soukous, gqom e amapiano também não.'),
]);

List<MusicTaxon> canonMena() => flattenCanon([
    n('mena', 'Música do Oriente Médio e Norte da África', children: [
        n('arabic_pop', 'Arabic Pop'),
        n('egyptian', 'Egipto', children: [
            n('al_jeel', 'Al-Jeel'),
            n('shaabi', 'Shaabi'),
            n('mahraganat', 'Mahraganat'),
          ], aliases: ['egyptian popular']),
        n('levantine', 'Levante', children: [
            n('dabke', 'Dabke'),
            n('tarab', 'Tarab'),
          ], aliases: ['levantine']),
        n('maghreb', 'Magrebe', children: [
            n('rai', 'Raï'),
            n('chaabi', 'Chaabi'),
            n('gnawa', 'Gnawa'),
            n('andalusi', 'Andalusi Maghrebi'),
          ], aliases: ['maghreb']),
        n('turkish', 'Turquia', children: [
            n('arabesque', 'Arabesque'),
            n('turkish_pop', 'Turkish Pop'),
            n('anatolian_rock', 'Anatolian Rock'),
            n('psychedelic', 'Turkish Psychedelia'),
          ], aliases: ['turkish music']),
        n('persian_pop', 'Persian Pop'),
        n('khaleeji', 'Khaleeji'),
        n('mizrahi', 'Mizrahi'),
        n('amazigh', 'Amazigh Popular'),
        n('sephardic_pop', 'Sephardic Popular'),
      ], aliases: ['mena', 'middle eastern', 'north african'], lore: '## Oriente Médio e Norte de África\nRaï, tarab, mahraganat e gnawa não são \'world beat\'.'),
]);

List<MusicTaxon> canonSouthAsian() => flattenCanon([
    n('south_asian', 'Música Sul-Asiática', children: [
        n('filmi', 'Filmi'),
        n('bollywood', 'Bollywood'),
        n('tollywood', 'Tollywood'),
        n('kollywood', 'Kollywood'),
        n('punjabi', 'Punjabi', children: [
            n('bhangra', 'Bhangra'),
            n('folk', 'Punjabi Folk Popular'),
          ], aliases: ['punjabi']),
        n('qawwali', 'Qawwali'),
        n('ghazal', 'Ghazal Popular'),
        n('sufi', 'Sufi Popular'),
        n('indipop', 'Indipop'),
        n('indian_rock', 'Indian Rock'),
        n('baul', 'Baul Popular'),
        n('lavani', 'Lavani'),
        n('pakistani_pop', 'Pakistani Pop'),
        n('lollywood', 'Lollywood'),
        n('baila', 'Baila'),
        n('bangladeshi', 'Bangladeshi Popular'),
        n('asian_underground', 'Asian Underground'),
      ], aliases: ['south asian', 'indian popular'], lore: '## Música Sul-Asiática\nFilmi e Hindustani não são o mesmo arquivo. Bhangra não é um tempero.'),
]);

List<MusicTaxon> canonEastAsian() => flattenCanon([
    n('east_asian', 'Música do Leste Asiático', children: [
        n('enka', 'Enka'),
        n('kayokyoku', 'Kayōkyoku'),
        n('jrock', 'J-Rock', secondary: ['rock']),
        n('visual_kei', 'Visual Kei'),
        n('city_pop_jp', 'City Pop Japonês', secondary: ['pop.city_pop']),
        n('shibuya_kei', 'Shibuya-kei', secondary: ['pop.jpop.shibuya'], scenes: ['scene.shibuya_kei']),
        n('trot', 'Trot'),
        n('k_indie', 'K-Indie'),
        n('korean_ballad', 'Korean Ballad'),
        n('korean_hiphop', 'Korean Hip-Hop', secondary: ['hiphop']),
        n('japanese_hiphop', 'Japanese Hip-Hop', secondary: ['hiphop']),
        n('chinese_rock', 'Chinese Rock', secondary: ['rock']),
        n('t_pop', 'T-Pop Taiwan'),
        n('denpa', 'Denpa'),
        n('doujin', 'Doujin Music'),
        n('okinawan', 'Okinawan Popular'),
        n('ainu_pop', 'Ainu Contemporary'),
        n('taiwanese', 'Taiwanese Popular'),
        n('hakka_pop', 'Hakka Popular'),
      ], aliases: ['east asian'], lore: '## Leste Asiático\nEnka, city pop e K-indie são rios. \'Asian pop\' não é um género.'),
]);

List<MusicTaxon> canonSoutheastAsian() => flattenCanon([
    n('southeast_asian', 'Música do Sudeste Asiático', children: [
        n('dangdut', 'Dangdut'),
        n('keroncong', 'Keroncong'),
        n('campursari', 'Campursari'),
        n('luk_thung', 'Luk Thung'),
        n('mor_lam', 'Mor Lam'),
        n('opm', 'OPM'),
        n('pinoy_rock', 'Pinoy Rock'),
        n('manila_sound', 'Manila Sound'),
        n('vpop', 'V-Pop'),
        n('malay_pop', 'Malay Pop'),
        n('indo_pop', 'Indo-Pop'),
        n('jaipong', 'Jaipongan Popular'),
        n('lao_pop', 'Lao Pop'),
        n('khmer_pop', 'Khmer Pop'),
        n('burmese_pop', 'Burmese Pop'),
        n('singapore_pop', 'Singapore Popular'),
        n('indonesian_jazz', 'Indonesian Jazz', secondary: ['jazz']),
      ], aliases: ['southeast asian'], lore: '## Sudeste Asiático\nDangdut, luk thung e OPM não são uma prateleira ASEAN.'),
]);

List<MusicTaxon> canonTraditions() => flattenCanon([
    n('indian', 'Tradição Indiana', axis: MusicAxisKind.tradition),
    n('persian', 'Tradição Persa', axis: MusicAxisKind.tradition),
    n('arabic', 'Tradição Árabe', axis: MusicAxisKind.tradition),
    n('ottoman', 'Tradição Otomana', axis: MusicAxisKind.tradition),
    n('chinese', 'Tradição Chinesa', axis: MusicAxisKind.tradition),
    n('japanese', 'Tradição Japonesa', axis: MusicAxisKind.tradition),
    n('korean', 'Tradição Coreana', axis: MusicAxisKind.tradition),
    n('indonesian', 'Tradição Indonésia', axis: MusicAxisKind.tradition),
    n('celtic', 'Tradição Celta', axis: MusicAxisKind.tradition),
    n('andalusi', 'Tradição Andalusi', axis: MusicAxisKind.tradition),
    n('west_african', 'Tradição da África Ocidental', axis: MusicAxisKind.tradition),
    n('yoruba', 'Tradição Iorubá', axis: MusicAxisKind.tradition),
    n('bantu', 'Tradição Bantu', axis: MusicAxisKind.tradition),
    n('andean', 'Tradição Andina', axis: MusicAxisKind.tradition),
    n('afro_brazilian', 'Tradição Afro-Brasileira', axis: MusicAxisKind.tradition),
    n('sephardic', 'Tradição Sefardita', axis: MusicAxisKind.tradition),
    n('ashkenazi', 'Tradição Asquenaze', axis: MusicAxisKind.tradition),
    n('polynesian', 'Tradição Polinésia', axis: MusicAxisKind.tradition),
    n('aboriginal', 'Tradição Aborígene Australiana', axis: MusicAxisKind.tradition),
    n('first_nations', 'Tradição das Primeiras Nações', axis: MusicAxisKind.tradition),
    n('saami', 'Tradição Sámi', axis: MusicAxisKind.tradition),
    n('balkan', 'Tradição Balcânica', axis: MusicAxisKind.tradition),
    n('roma', 'Tradição Roma', axis: MusicAxisKind.tradition),
    n('malian', 'Tradição Malinesa', axis: MusicAxisKind.tradition),
    n('ethiopian', 'Tradição Etíope', axis: MusicAxisKind.tradition),
    n('javanese', 'Tradição Javanesa', axis: MusicAxisKind.tradition),
    n('balinese', 'Tradição Balinesa', axis: MusicAxisKind.tradition),
], prefix: 'tradition', defaultAxis: MusicAxisKind.tradition);

List<MusicTaxon> canonScenes() => flattenCanon([
    n('canterbury', 'Canterbury', axis: MusicAxisKind.scene),
    n('krautrock', 'Krautrock', axis: MusicAxisKind.scene),
    n('clube_da_esquina', 'Clube da Esquina', axis: MusicAxisKind.scene),
    n('tropicalia', 'Tropicália', axis: MusicAxisKind.scene),
    n('manguebeat', 'Manguebeat', axis: MusicAxisKind.scene),
    n('black_rio', 'Black Rio', axis: MusicAxisKind.scene),
    n('madchester', 'Madchester', axis: MusicAxisKind.scene),
    n('britpop', 'Britpop', axis: MusicAxisKind.scene),
    n('seattle_grunge', 'Seattle Grunge', axis: MusicAxisKind.scene),
    n('no_wave', 'No Wave', axis: MusicAxisKind.scene),
    n('downtown_ny', 'Downtown New York', axis: MusicAxisKind.scene),
    n('detroit_techno', 'Detroit Techno', axis: MusicAxisKind.scene),
    n('chicago_house', 'Chicago House', axis: MusicAxisKind.scene),
    n('bristol_triphop', 'Bristol Trip-Hop', axis: MusicAxisKind.scene),
    n('bay_area_thrash', 'Bay Area Thrash', axis: MusicAxisKind.scene),
    n('norwegian_bm', 'Norwegian Black Metal', axis: MusicAxisKind.scene),
    n('gothenburg_death', 'Gothenburg Death Metal', axis: MusicAxisKind.scene),
    n('nwobhm', 'NWOBHM', axis: MusicAxisKind.scene),
    n('french_touch', 'French Touch', axis: MusicAxisKind.scene),
    n('shibuya_kei', 'Shibuya-kei', axis: MusicAxisKind.scene),
    n('aacm', 'AACM', axis: MusicAxisKind.scene),
    n('loft_jazz', 'Loft Jazz', axis: MusicAxisKind.scene),
    n('cbgb', 'CBGB', axis: MusicAxisKind.scene),
    n('haight_ashbury', 'Haight-Ashbury', axis: MusicAxisKind.scene),
    n('laurel_canyon', 'Laurel Canyon', axis: MusicAxisKind.scene),
    n('motown', 'Motown', axis: MusicAxisKind.scene),
    n('stax', 'Stax', axis: MusicAxisKind.scene),
    n('muscle_shoals', 'Muscle Shoals', axis: MusicAxisKind.scene),
    n('studio_one', 'Studio One', axis: MusicAxisKind.scene),
    n('paisley_underground', 'Paisley Underground', axis: MusicAxisKind.scene),
    n('dunedin', 'Dunedin', axis: MusicAxisKind.scene),
    n('warp', 'Warp', axis: MusicAxisKind.scene),
    n('factory', 'Factory Records', axis: MusicAxisKind.scene),
], prefix: 'scene', defaultAxis: MusicAxisKind.scene);

List<MusicTaxon> canonMovements() => flattenCanon([
    n('tropicalismo', 'Tropicalismo', axis: MusicAxisKind.movement),
    n('minimalism', 'Minimalism', axis: MusicAxisKind.movement),
    n('rio', 'Rock in Opposition', axis: MusicAxisKind.movement),
    n('zeuhl', 'Zeuhl', axis: MusicAxisKind.movement),
    n('primitivism', 'Primitivism', axis: MusicAxisKind.movement),
    n('futurism', 'Futurism', axis: MusicAxisKind.movement),
    n('serialism', 'Serialism', axis: MusicAxisKind.movement),
    n('spectralism', 'Spectralism', axis: MusicAxisKind.movement),
    n('fluxus', 'Fluxus', axis: MusicAxisKind.movement),
    n('dada', 'Dada', axis: MusicAxisKind.movement),
    n('modernism', 'Modernism', axis: MusicAxisKind.movement),
    n('postmodernism', 'Postmodernism', axis: MusicAxisKind.movement),
    n('romanticism', 'Romanticism', axis: MusicAxisKind.movement),
    n('nationalism', 'Musical Nationalism', axis: MusicAxisKind.movement),
    n('totalism', 'Totalism', axis: MusicAxisKind.movement),
    n('holy_minimalism', 'Holy Minimalism', axis: MusicAxisKind.movement),
], prefix: 'movement', defaultAxis: MusicAxisKind.movement);

List<MusicTaxon> canonForms() => flattenCanon([
    n('symphony', 'Symphony', axis: MusicAxisKind.form),
    n('sonata', 'Sonata', axis: MusicAxisKind.form),
    n('raga', 'Raga Form', axis: MusicAxisKind.form),
    n('blues_form', 'Blues Form', axis: MusicAxisKind.form),
    n('choro', 'Choro Form', axis: MusicAxisKind.form),
    n('song', 'Song Form', axis: MusicAxisKind.form),
    n('suite', 'Suite', axis: MusicAxisKind.form),
    n('opera', 'Opera', axis: MusicAxisKind.form),
    n('concerto', 'Concerto', axis: MusicAxisKind.form),
    n('fugue', 'Fugue', axis: MusicAxisKind.form),
    n('mass', 'Mass', axis: MusicAxisKind.form),
    n('oratorio', 'Oratorio', axis: MusicAxisKind.form),
    n('cantata', 'Cantata', axis: MusicAxisKind.form),
    n('lied', 'Lied', axis: MusicAxisKind.form),
    n('madrigal', 'Madrigal Form', axis: MusicAxisKind.form),
    n('string_quartet', 'String Quartet', axis: MusicAxisKind.form),
    n('theme_variations', 'Theme and Variations', axis: MusicAxisKind.form),
    n('passacaglia', 'Passacaglia', axis: MusicAxisKind.form),
    n('aaba', 'AABA / 32-bar', axis: MusicAxisKind.form),
    n('verse_chorus', 'Verse-Chorus', axis: MusicAxisKind.form),
    n('through_composed', 'Through-Composed', axis: MusicAxisKind.form),
    n('strophic', 'Strophic', axis: MusicAxisKind.form),
    n('call_response', 'Call and Response Form', axis: MusicAxisKind.form),
    n('head_solos', 'Head-Solos-Head', axis: MusicAxisKind.form),
    n('wasla', 'Wasla', axis: MusicAxisKind.form),
    n('alap_jor_jhala', 'Alap-Jor-Jhala', axis: MusicAxisKind.form),
], prefix: 'form', defaultAxis: MusicAxisKind.form);

List<MusicTaxon> canonFunctions() => flattenCanon([
    n('stage_screen', 'Stage and Screen', axis: MusicAxisKind.function),
    n('game', 'Game Music', axis: MusicAxisKind.function),
    n('children', 'Children\'s Music', axis: MusicAxisKind.function),
    n('spoken', 'Spoken Word', axis: MusicAxisKind.function),
    n('comedy', 'Comedy Music', axis: MusicAxisKind.function),
    n('field_recording', 'Field Recording', axis: MusicAxisKind.function),
    n('sound_art', 'Sound Art', axis: MusicAxisKind.function),
    n('religious', 'Religious / Liturgical Function', axis: MusicAxisKind.function),
    n('library', 'Library / Production Music', axis: MusicAxisKind.function),
    n('advertising', 'Advertising', axis: MusicAxisKind.function),
    n('ceremonial', 'Ceremonial', axis: MusicAxisKind.function),
    n('dance_social', 'Social Dance', axis: MusicAxisKind.function),
    n('work_song', 'Work Song', axis: MusicAxisKind.function),
    n('protest', 'Protest Song Function', axis: MusicAxisKind.function),
    n('lullaby', 'Lullaby', axis: MusicAxisKind.function),
    n('anthem', 'Anthem', axis: MusicAxisKind.function),
    n('sports', 'Sports Music', axis: MusicAxisKind.function),
    n('ritual', 'Ritual Function', axis: MusicAxisKind.function),
    n('educational', 'Educational', axis: MusicAxisKind.function),
    n('trailer', 'Trailer Music', axis: MusicAxisKind.function),
    n('wedding', 'Wedding Function', axis: MusicAxisKind.function),
    n('funeral', 'Funeral Function', axis: MusicAxisKind.function),
    n('military', 'Military Function', axis: MusicAxisKind.function),
], prefix: 'function', defaultAxis: MusicAxisKind.function);

List<MusicTaxon> canonTechniques() => flattenCanon([
    n('sampling', 'Sampling', axis: MusicAxisKind.technique),
    n('turntablism', 'Turntablism', axis: MusicAxisKind.technique),
    n('looping', 'Looping', axis: MusicAxisKind.technique),
    n('sequencing', 'Sequencing', axis: MusicAxisKind.technique),
    n('field_recording', 'Field Recording Technique', axis: MusicAxisKind.technique),
    n('prepared_piano', 'Prepared Piano', axis: MusicAxisKind.technique),
    n('extended_technique', 'Extended Technique', axis: MusicAxisKind.technique),
    n('circular_breathing', 'Circular Breathing', axis: MusicAxisKind.technique),
    n('overtone_singing', 'Overtone Singing', axis: MusicAxisKind.technique),
    n('scatting', 'Scat Singing', axis: MusicAxisKind.technique),
    n('beatboxing', 'Beatboxing', axis: MusicAxisKind.technique),
    n('fingerpicking', 'Fingerpicking', axis: MusicAxisKind.technique),
    n('slide', 'Slide Guitar', axis: MusicAxisKind.technique),
    n('tape_manipulation', 'Tape Manipulation', axis: MusicAxisKind.technique),
    n('granular', 'Granular Synthesis', axis: MusicAxisKind.technique),
    n('fm_synthesis', 'FM Synthesis', axis: MusicAxisKind.technique),
    n('modular', 'Modular Synthesis', axis: MusicAxisKind.technique),
    n('breakbeat_chop', 'Breakbeat Chopping', axis: MusicAxisKind.technique),
    n('sidechain', 'Sidechain Compression', axis: MusicAxisKind.technique),
    n('vocoder', 'Vocoder', axis: MusicAxisKind.technique),
    n('autotune', 'Auto-Tune as Technique', axis: MusicAxisKind.technique),
    n('wall_of_sound', 'Wall of Sound', axis: MusicAxisKind.technique),
    n('motorik', 'Motorik Playing', axis: MusicAxisKind.technique),
    n('counterpoint', 'Counterpoint', axis: MusicAxisKind.technique),
    n('phase_shifting', 'Phase Shifting', axis: MusicAxisKind.technique),
    n('circuit_bending', 'Circuit Bending', axis: MusicAxisKind.technique),
    n('live_coding', 'Live Coding', axis: MusicAxisKind.technique),
    n('no_input_mixer', 'No-Input Mixing', axis: MusicAxisKind.technique),
    n('prepared_guitar', 'Prepared Guitar', axis: MusicAxisKind.technique),
    n('just_intonation', 'Just Intonation Practice', axis: MusicAxisKind.technique),
], prefix: 'technique', defaultAxis: MusicAxisKind.technique);

List<MusicTaxon> canonDescriptors() => flattenCanon([
    n('lo_fi', 'Lo-fi', axis: MusicAxisKind.descriptor),
    n('hi_fi', 'Hi-fi', axis: MusicAxisKind.descriptor),
    n('dense', 'Dense', axis: MusicAxisKind.descriptor),
    n('sparse', 'Sparse', axis: MusicAxisKind.descriptor),
    n('dark', 'Dark', axis: MusicAxisKind.descriptor),
    n('bright', 'Bright', axis: MusicAxisKind.descriptor),
    n('warm', 'Warm', axis: MusicAxisKind.descriptor),
    n('cold', 'Cold', axis: MusicAxisKind.descriptor),
    n('aggressive', 'Aggressive', axis: MusicAxisKind.descriptor),
    n('gentle', 'Gentle', axis: MusicAxisKind.descriptor),
    n('dreamy', 'Dreamy', axis: MusicAxisKind.descriptor),
    n('raw', 'Raw', axis: MusicAxisKind.descriptor),
    n('polished', 'Polished', axis: MusicAxisKind.descriptor),
    n('noisy', 'Noisy', axis: MusicAxisKind.descriptor),
    n('heavy', 'Heavy', axis: MusicAxisKind.descriptor),
    n('atmospheric', 'Atmospheric', axis: MusicAxisKind.descriptor),
    n('hypnotic', 'Hypnotic', axis: MusicAxisKind.descriptor),
    n('abrasive', 'Abrasive', axis: MusicAxisKind.descriptor),
    n('lush', 'Lush', axis: MusicAxisKind.descriptor),
    n('motorik_feel', 'Motorik Feel', axis: MusicAxisKind.descriptor),
    n('swung', 'Swung', axis: MusicAxisKind.descriptor),
    n('straight', 'Straight', axis: MusicAxisKind.descriptor),
    n('syncopated', 'Syncopated', axis: MusicAxisKind.descriptor),
    n('melancholic', 'Melancholic', axis: MusicAxisKind.descriptor),
    n('euphoric', 'Euphoric', axis: MusicAxisKind.descriptor),
    n('psychedelic_feel', 'Psychedelic Feel', axis: MusicAxisKind.descriptor),
    n('retro', 'Retro', axis: MusicAxisKind.descriptor),
    n('futuristic', 'Futuristic', axis: MusicAxisKind.descriptor),
    n('cosmic', 'Cosmic', axis: MusicAxisKind.descriptor),
    n('urban', 'Urban', axis: MusicAxisKind.descriptor),
    n('rural', 'Rural', axis: MusicAxisKind.descriptor),
], prefix: 'descriptor', defaultAxis: MusicAxisKind.descriptor);

List<MusicTaxon> canonGeographies() => flattenCanon([
    n('minas_gerais', 'Minas Gerais', axis: MusicAxisKind.geography),
    n('detroit', 'Detroit', axis: MusicAxisKind.geography),
    n('chicago', 'Chicago', axis: MusicAxisKind.geography),
    n('london', 'London', axis: MusicAxisKind.geography),
    n('kingston', 'Kingston', axis: MusicAxisKind.geography),
    n('salvador', 'Salvador', axis: MusicAxisKind.geography),
    n('rio', 'Rio de Janeiro', axis: MusicAxisKind.geography),
    n('recife', 'Recife', axis: MusicAxisKind.geography),
    n('new_orleans', 'New Orleans', axis: MusicAxisKind.geography),
    n('sevilla', 'Sevilla', axis: MusicAxisKind.geography),
    n('new_york', 'New York', axis: MusicAxisKind.geography),
    n('los_angeles', 'Los Angeles', axis: MusicAxisKind.geography),
    n('memphis', 'Memphis', axis: MusicAxisKind.geography),
    n('nashville', 'Nashville', axis: MusicAxisKind.geography),
    n('manchester', 'Manchester', axis: MusicAxisKind.geography),
    n('bristol', 'Bristol', axis: MusicAxisKind.geography),
    n('berlin', 'Berlin', axis: MusicAxisKind.geography),
    n('tokyo', 'Tokyo', axis: MusicAxisKind.geography),
    n('lagos', 'Lagos', axis: MusicAxisKind.geography),
    n('havana', 'Havana', axis: MusicAxisKind.geography),
    n('san_juan', 'San Juan', axis: MusicAxisKind.geography),
    n('buenos_aires', 'Buenos Aires', axis: MusicAxisKind.geography),
    n('lima', 'Lima', axis: MusicAxisKind.geography),
    n('bay_area', 'Bay Area', axis: MusicAxisKind.geography),
    n('seattle', 'Seattle', axis: MusicAxisKind.geography),
    n('dc', 'Washington D.C.', axis: MusicAxisKind.geography),
    n('texas', 'Texas', axis: MusicAxisKind.geography),
    n('norway', 'Norway', axis: MusicAxisKind.geography),
    n('sao_paulo', 'São Paulo', axis: MusicAxisKind.geography),
    n('bahia', 'Bahia', axis: MusicAxisKind.geography),
], prefix: 'geo', defaultAxis: MusicAxisKind.geography);

List<MusicTaxon> canonEras() => flattenCanon([
    n('medieval', 'Medieval', axis: MusicAxisKind.era),
    n('renaissance', 'Renaissance', axis: MusicAxisKind.era),
    n('baroque', 'Baroque Era', axis: MusicAxisKind.era),
    n('classical', 'Classical Era', axis: MusicAxisKind.era),
    n('romantic', 'Romantic Era', axis: MusicAxisKind.era),
    n('modernist', 'Modernist Era', axis: MusicAxisKind.era),
    n('postwar', 'Postwar Era', axis: MusicAxisKind.era),
    n('fifties', '1950s', axis: MusicAxisKind.era),
    n('sixties', '1960s', axis: MusicAxisKind.era),
    n('seventies', '1970s', axis: MusicAxisKind.era),
    n('eighties', '1980s', axis: MusicAxisKind.era),
    n('nineties', '1990s', axis: MusicAxisKind.era),
    n('two_thousands', '2000s', axis: MusicAxisKind.era),
    n('twenty_tens', '2010s', axis: MusicAxisKind.era),
    n('twenty_twenties', '2020s', axis: MusicAxisKind.era),
    n('interwar', 'Interwar', axis: MusicAxisKind.era),
    n('rave_era', 'Rave Era', axis: MusicAxisKind.era),
    n('streaming_era', 'Streaming Era', axis: MusicAxisKind.era),
    n('golden_age_hiphop', 'Golden Age Hip-Hop Era', axis: MusicAxisKind.era),
    n('post_punk_era', 'Post-Punk Era', axis: MusicAxisKind.era),
], prefix: 'era', defaultAxis: MusicAxisKind.era);

List<MusicTaxon> canonConcepts() => flattenCanon([
    n('tonal', 'Tonality', axis: MusicAxisKind.concept),
    n('modal', 'Modality', axis: MusicAxisKind.concept),
    n('atonal', 'Atonality', axis: MusicAxisKind.concept),
    n('serial', 'Serial Thought', axis: MusicAxisKind.concept),
    n('swing', 'Swing Feel', axis: MusicAxisKind.concept),
    n('clave', 'Clave', axis: MusicAxisKind.concept),
    n('son_clave', 'Son Clave', axis: MusicAxisKind.concept),
    n('rumba_clave', 'Rumba Clave', axis: MusicAxisKind.concept),
    n('four_on_the_floor', 'Four-on-the-Floor', axis: MusicAxisKind.concept),
    n('breakbeat', 'Breakbeat', axis: MusicAxisKind.concept),
    n('improvisation', 'Improvisation', children: [
        n('thematic', 'Thematic Improvisation', axis: MusicAxisKind.concept),
        n('motivic', 'Motivic Improvisation', axis: MusicAxisKind.concept),
        n('free', 'Free Improvisation Concept', axis: MusicAxisKind.concept),
        n('modal_improv', 'Modal Improvisation', axis: MusicAxisKind.concept),
        n('collective', 'Collective Improvisation', axis: MusicAxisKind.concept),
        n('solo', 'Soloistic Improvisation', axis: MusicAxisKind.concept),
      ], axis: MusicAxisKind.concept),
    n('syncopation', 'Syncopation', axis: MusicAxisKind.concept),
    n('polyrhythm', 'Polyrhythm', axis: MusicAxisKind.concept),
    n('groove', 'Groove', axis: MusicAxisKind.concept),
    n('motorik', 'Motorik Pulse', axis: MusicAxisKind.concept),
    n('ostinato', 'Ostinato', axis: MusicAxisKind.concept),
    n('drone_concept', 'Drone', axis: MusicAxisKind.concept),
    n('backbeat', 'Backbeat', axis: MusicAxisKind.concept),
    n('tresillo', 'Tresillo', axis: MusicAxisKind.concept),
    n('habanera', 'Habanera Rhythm', axis: MusicAxisKind.concept),
    n('tumbao', 'Tumbao', axis: MusicAxisKind.concept),
    n('montuno', 'Montuno', axis: MusicAxisKind.concept),
    n('walking_bass', 'Walking Bass', axis: MusicAxisKind.concept),
    n('standard_pattern', 'Standard Timeline Pattern', axis: MusicAxisKind.concept),
    n('shuffle', 'Shuffle', axis: MusicAxisKind.concept),
    n('half_time', 'Half-Time', axis: MusicAxisKind.concept),
    n('functional_harmony', 'Functional Harmony', axis: MusicAxisKind.concept),
    n('quartal', 'Quartal Harmony', axis: MusicAxisKind.concept),
    n('blues_scale', 'Blues Scale', axis: MusicAxisKind.concept),
    n('tala', 'Tala', axis: MusicAxisKind.concept),
    n('maqam_concept', 'Maqam', axis: MusicAxisKind.concept),
    n('pelog', 'Pelog', axis: MusicAxisKind.concept),
    n('slendro', 'Slendro', axis: MusicAxisKind.concept),
    n('colotomic', 'Colotomic Structure', axis: MusicAxisKind.concept),
    n('phasing', 'Phasing', axis: MusicAxisKind.concept),
], prefix: 'concept', defaultAxis: MusicAxisKind.concept);

List<MusicTaxonLink> canonLinks() => linksFor([
  (MusicTaxonLinkKind.derivedFrom, 'punk.punk', 'rock.garage'),
  (MusicTaxonLinkKind.fusedWith, 'jazz.fusion', 'rock'),
  (MusicTaxonLinkKind.influencedBy, 'jazz.fusion', 'rock'),
  (MusicTaxonLinkKind.siblingOf, 'jazz.bebop', 'jazz.hard_bop'),
  (MusicTaxonLinkKind.historicallyPrecedes, 'reggae.rocksteady', 'reggae.early'),
  (MusicTaxonLinkKind.regionalVariantOf, 'jazz.latin.brazilian', 'jazz'),
  (MusicTaxonLinkKind.revivalOf, 'rock.alt.psych_pop', 'rock.psych'),
  (MusicTaxonLinkKind.sceneAssociatedWith, 'rock.alt.grunge', 'scene.seattle_grunge'),
  (MusicTaxonLinkKind.movementAssociatedWith, 'brazilian.tropicalia', 'movement.tropicalismo'),
  (MusicTaxonLinkKind.commonlyOverlaps, 'rock.alt.dream_pop', 'rock.alt.shoegaze'),
  (MusicTaxonLinkKind.historicallyPrecedes, 'electronic.jungle', 'electronic.dnb'),
  (MusicTaxonLinkKind.historicallyPrecedes, 'electronic.breaks.hardcore', 'electronic.jungle'),
  (MusicTaxonLinkKind.derivedFrom, 'metal.trad', 'rock.hard'),
  (MusicTaxonLinkKind.fusedWith, 'jazz.fusion.jazz_funk', 'funk'),
  (MusicTaxonLinkKind.influencedBy, 'soul', 'gospel'),
  (MusicTaxonLinkKind.derivedFrom, 'soul', 'rnb'),
  (MusicTaxonLinkKind.derivedFrom, 'funk', 'soul'),
  (MusicTaxonLinkKind.historicallyPrecedes, 'reggae.ska', 'reggae.rocksteady'),
  (MusicTaxonLinkKind.commonlyOverlaps, 'metal.black.blackgaze', 'rock.alt.shoegaze'),
  (MusicTaxonLinkKind.sceneAssociatedWith, 'rock.prog.canterbury', 'scene.canterbury'),
  (MusicTaxonLinkKind.sceneAssociatedWith, 'rock.prog.krautrock', 'scene.krautrock'),
  (MusicTaxonLinkKind.sceneAssociatedWith, 'brazilian.clube_da_esquina', 'scene.clube_da_esquina'),
  (MusicTaxonLinkKind.sceneAssociatedWith, 'electronic.techno.detroit', 'scene.detroit_techno'),
  (MusicTaxonLinkKind.sceneAssociatedWith, 'electronic.house.chicago', 'scene.chicago_house'),
  (MusicTaxonLinkKind.commonlyOverlaps, 'brazilian.funk_br', 'electronic.club.baile'),
  (MusicTaxonLinkKind.regionalVariantOf, 'brazilian.funk_br', 'funk'),
  (MusicTaxonLinkKind.siblingOf, 'african.afrobeat', 'african.afrobeats'),
  (MusicTaxonLinkKind.influencedBy, 'hiphop.grime', 'electronic.garage'),
  (MusicTaxonLinkKind.derivedFrom, 'punk.postpunk', 'punk.punk'),
  (MusicTaxonLinkKind.revivalOf, 'rock.psych.neo', 'rock.psych'),
]);

