#!/usr/bin/env python3
"""Generate Fallhub Terminal pixel-art chrome, icons, portraits and textures.

Original kit (not RimWorld / not Fallout). 1px outlines, shared palette,
nearest-neighbour scale. Re-run:

    python3 tool/generate_fallhub_terminal_assets.py
"""

from __future__ import annotations

import math
import os
from pathlib import Path

from PIL import Image, ImageDraw, ImageEnhance, ImageFilter

ROOT = Path(__file__).resolve().parents[1]
DS = ROOT / "packages/colony_design_system/assets/ui"
TERM = DS / "terminal"
CHROME = DS / "chrome"
CATALOG = ROOT / "docs/produto/assets/generated/fallhub_terminal"
PORTRAIT_SRC = Path("/opt/cursor/artifacts/assets/pawn_portrait_pixel.png")
PORTRAIT_REPO = ROOT / "docs/produto/assets/generated/fallhub_terminal/pawn_src.png"
METAL_SRC = Path("/opt/cursor/artifacts/assets/metal_grain_tile.png")
METAL_REPO = ROOT / "docs/produto/assets/generated/fallhub_terminal/hull_plates_src.png"

# Shared terminal palette (sampled + designed).
K = (10, 10, 12, 255)  # outline
W = (232, 224, 212, 255)  # warm white
M = (138, 144, 152, 255)  # metal
MH = (188, 192, 196, 255)  # metal hi
MD = (58, 62, 68, 255)
MG = (90, 96, 102, 255)
BR = (196, 164, 106, 255)  # brass
BH = (240, 208, 144, 255)
BD = (140, 112, 64, 255)
CU = (107, 69, 50, 255)  # copper
CH = (130, 88, 62, 255)
CYAN = (90, 212, 236, 255)
CYAN_D = (32, 140, 168, 255)
BLUE = (90, 158, 208, 255)
BLUE_D = (42, 90, 140, 255)
GREEN = (90, 176, 110, 255)
GREEN_D = (36, 96, 64, 255)
PURP = (168, 118, 196, 255)
PURP_D = (72, 48, 96, 255)
BROWN = (176, 122, 70, 255)
NAVY = (26, 42, 74, 255)
SKIN = (214, 168, 126, 255)
SKIN_D = (176, 118, 86, 255)
HAIR = (28, 22, 20, 255)
SHIRT = (62, 132, 78, 255)
RED = (196, 74, 70, 255)
VOID = (14, 17, 20, 255)
PANEL = (26, 30, 34, 255)


def _rgba(c, a=255):
    if len(c) == 4:
        return c
    return (c[0], c[1], c[2], a)


class Sprite:
    def __init__(self, w: int, h: int):
        self.w = w
        self.h = h
        self.px = [[None] * w for _ in range(h)]

    def put(self, x, y, c):
        if 0 <= x < self.w and 0 <= y < self.h and c is not None:
            self.px[y][x] = _rgba(c)

    def fill(self, x, y, w, h, c):
        for yy in range(y, y + h):
            for xx in range(x, x + w):
                self.put(xx, yy, c)

    def rect(self, x, y, w, h, c):
        for xx in range(x, x + w):
            self.put(xx, y, c)
            self.put(xx, y + h - 1, c)
        for yy in range(y, y + h):
            self.put(x, yy, c)
            self.put(x + w - 1, yy, c)

    def line(self, x0, y0, x1, y1, c):
        dx, dy = abs(x1 - x0), abs(y1 - y0)
        sx = 1 if x0 < x1 else -1
        sy = 1 if y0 < y1 else -1
        err = dx - dy
        while True:
            self.put(x0, y0, c)
            if x0 == x1 and y0 == y1:
                break
            e2 = 2 * err
            if e2 > -dy:
                err -= dy
                x0 += sx
            if e2 < dx:
                err += dx
                y0 += sy

    def circle(self, cx, cy, r, c, fill=True):
        for y in range(cy - r, cy + r + 1):
            for x in range(cx - r, cx + r + 1):
                d2 = (x - cx) ** 2 + (y - cy) ** 2
                if fill:
                    if d2 <= r * r + r * 0.2:
                        self.put(x, y, c)
                else:
                    if abs(math.sqrt(d2) - r) < 0.7:
                        self.put(x, y, c)

    def stamp(self, x, y, rows, pal):
        for j, row in enumerate(rows):
            for i, ch in enumerate(row):
                if ch in pal and pal[ch] is not None:
                    self.put(x + i, y + j, pal[ch])

    def image(self, scale=1) -> Image.Image:
        im = Image.new("RGBA", (self.w, self.h), (0, 0, 0, 0))
        p = im.load()
        for y in range(self.h):
            for x in range(self.w):
                if self.px[y][x]:
                    p[x, y] = self.px[y][x]
        if scale > 1:
            im = im.resize((self.w * scale, self.h * scale), Image.Resampling.NEAREST)
        return im

    def save(self, path: Path, scale=2):
        path.parent.mkdir(parents=True, exist_ok=True)
        self.image(scale).save(path, "PNG")


def save_scaled(im: Image.Image, path: Path, scale=1):
    path.parent.mkdir(parents=True, exist_ok=True)
    if scale != 1:
        im = im.resize((im.width * scale, im.height * scale), Image.Resampling.NEAREST)
    im.save(path, "PNG")


def rivet(draw: ImageDraw.ImageDraw, x, y, r=2):
    draw.ellipse((x - r, y - r, x + r, y + r), fill=MD)
    draw.ellipse((x - r + 1, y - r + 1, x + r - 1, y + r - 1), fill=M)
    draw.point((x - 1, y - 1), fill=MH)


def make_panel_9(size=36, fill=PANEL, inset=False) -> Image.Image:
    im = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    r = 5
    box = [0, 0, size - 1, size - 1]
    d.rounded_rectangle(box, radius=r, fill=K)
    inner = [1, 1, size - 2, size - 2]
    face = (20, 22, 26, 255) if inset else fill
    d.rounded_rectangle(inner, radius=r - 1, fill=face)
    # bevel
    hi = (70, 74, 80, 255) if not inset else (40, 44, 48, 255)
    sh = (8, 9, 11, 255)
    for i in range(2, size - 2):
        im.putpixel((i, 2), hi)
        im.putpixel((i, size - 3), sh)
        im.putpixel((2, i), hi)
        im.putpixel((size - 3, i), sh)
    rivet(d, 6, 6, 2)
    rivet(d, size - 7, 6, 2)
    rivet(d, 6, size - 7, 2)
    rivet(d, size - 7, size - 7, 2)
    return im


def make_button_9(size=(48, 24), pressed=False) -> Image.Image:
    w, h = size
    im = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)
    face = (84, 52, 38, 255) if pressed else CU
    d.rounded_rectangle([0, 0, w - 1, h - 1], radius=3, fill=K)
    d.rounded_rectangle([1, 1, w - 2, h - 2], radius=3, fill=face)
    hi = (48, 32, 24, 255) if pressed else (156, 108, 78, 255)
    sh = (40, 24, 18, 255)
    for x in range(2, w - 2):
        im.putpixel((x, 2), hi)
        im.putpixel((x, h - 3), sh)
    return im


def make_grain(size=64) -> Image.Image:
    im = Image.new("RGB", (size, size), VOID[:3])
    p = im.load()
    for y in range(size):
        for x in range(size):
            n = ((x * 17 + y * 31) ^ (x * 13 + y * 7)) & 255
            v = 14 + (n % 11)
            # faint horizontal grain
            if y % 4 == 0:
                v -= 3
            p[x, y] = (v, v + 1, v + 2)
            if (x + y * 3) % 19 == 0:
                p[x, y] = (v + 8, v + 8, v + 9)
    if METAL_SRC.exists():
        src = Image.open(METAL_SRC).convert("RGB").resize((size, size), Image.Resampling.BOX)
        src = ImageEnhance.Contrast(src).enhance(0.45)
        src = ImageEnhance.Brightness(src).enhance(0.55)
        im = Image.blend(im, src, 0.35)
    return im.convert("RGBA")


# --- Icon definitions (16x16, letters -> palette) ---------------------------

P = {
    ".": None,
    "k": K,
    "w": W,
    "m": M,
    "h": MH,
    "d": MD,
    "g": BR,
    "G": BH,
    "b": BLUE,
    "B": BLUE_D,
    "e": GREEN,
    "E": GREEN_D,
    "c": CYAN,
    "C": CYAN_D,
    "p": PURP,
    "P": PURP_D,
    "r": BROWN,
    "n": NAVY,
    "s": SKIN,
    "S": SKIN_D,
    "a": HAIR,
    "t": SHIRT,
    "u": CU,
    "R": RED,
    "v": VOID,
}


def ico(rows: str) -> list[str]:
    lines = [ln for ln in rows.strip("\n").split("\n")]
    # pad/trim to 16
    out = []
    for ln in lines[:16]:
        ln = ln[:16].ljust(16, ".")
        out.append(ln)
    while len(out) < 16:
        out.append("." * 16)
    return out


ICONS: dict[str, str] = {}

ICONS["person"] = """
......kkkk......
.....kcccck.....
....kcchhcck....
....kchsscck....
....k.sSSs.k....
.....kssssk.....
......kssk......
....kkcccckk....
...kccwwccwck...
...kccwwccwck...
...kcccccccck...
...kcck..kcck...
...kcck..kcck...
....kk....kk....
................
................
"""

ICONS["people"] = """
................
...kk....kk.....
..kbbk..kggk....
..kbhk..kgGk....
..kssk..kssk....
...kk....kk.....
.kkttkk.kkuukk..
.kttttk.kuuuuk..
.kttttk.kuuuuk..
.kttkkkkkuuukk..
.kttk..kuuuk....
..kk....kk......
......kkkk......
.....kbbbbk.....
.....kttttk.....
......kkkk......
"""

ICONS["flag"] = """
................
...k............
...kGGGGGGk.....
...kGgGgGgk.....
...kGgggggk.....
...kGGGGGGk.....
...k............
...k............
...k............
...k............
...k............
...k............
...kkkkkk.......
..kmmmmmmk......
...kkkkkk.......
................
"""

ICONS["heart"] = """
................
................
...kk....kk.....
..keeek.keeek...
.keeeeekeeeeeek.
.keeeeeeeeeeeek.
.keeeeeeeeeeeek.
.keeeeecceeeeek.
.keeeccccceeeek.
..keeccccceek...
...keeccccek....
....keeccek.....
.....kecek......
......kek.......
.......k........
................
"""

ICONS["coin"] = """
................
.....kkkkk......
....kGGGGGk.....
...kGgwwwgGk....
..kGgwwwwwgGk...
..kGgwkgkgwGk...
..kGgwkggkwGk...
..kGgwkgkgwGk...
..kGgwwwwwgGk...
..kGggwwwwgGk...
...kGgggggGk....
....kGGGGGk.....
.....kkkkk......
................
................
................
"""

ICONS["house"] = """
................
.......k........
......kbk.......
.....kbbbk......
....kbbbbbk.....
...kbbbbbbbk....
..kbbbbbbbbbk...
..kkkkkkkkkkkk..
...kwwk..kwwk...
...kwck..kcwk...
...kwwk..kwwk...
...kwwkkkkwwk...
...kwwkuuukwk...
...kwwkuuukwk...
...kkkkkkkkkk...
................
"""

ICONS["book"] = """
................
....kkkkkkk.....
...krrrrrwrk....
...krrrrrwrk....
...krrGGrwrk....
...krrrrrwrk....
...krrrrrwrk....
...krrrrrwrk....
...krrrrrwrk....
...krrrrrwrk....
...krrrrrwgk....
...krrrrrwgk....
....kkkkkkk.....
.....k...k......
................
................
"""

ICONS["moon"] = """
................
......kkkkk.....
.....kcwwwk.....
....kcwwwk......
....kwwwk.......
...kwwwk........
...kwwwk........
...kcwwk........
....kcwwwk......
....kccwwwk.....
.....kcccck.....
......kkkk......
................
................
................
................
"""

ICONS["moon_sleep"] = """
................
......kkkk......
.....kccwwk.kk..
....kcwwwk.kwk..
....kwwwk..kwk..
...kwwwk....k...
...kwwwk........
...kwwwk........
....kwwwk.......
....kcwwwk......
.....kcccck.....
......kkkk......
................
................
................
................
"""

ICONS["crosshair"] = """
................
.......kk.......
......keeek.....
.......ee.......
.......ee.......
...k...ee...k...
.keeekkeeekkeek.
.keeekkeeekkeek.
...k...ee...k...
.......ee.......
.......ee.......
......keeek.....
.......kk.......
................
................
................
"""

ICONS["cap"] = """
................
................
.....kkkkk......
....kpppppk.....
...kppwwwppk....
..kpppppppppk...
.kkkkkkkkkkkkk..
.kpppppppppppk..
..kkkkkkkkkkk...
......kp........
......kpk.......
......kpk.......
.......k........
................
................
................
"""

ICONS["utensils"] = """
................
..k..k...k......
..k..k..krk.....
..k..k..krk.....
..k..k..krk.....
..k..k..krk.....
..kkkk...k......
...kk....k......
...kk....k......
...kk....k......
...kk....k......
...kk....k......
...kk....k......
...kk...kk......
................
................
"""

ICONS["star"] = """
................
.......k........
......kmk.......
......kmk.......
..kkkkmmmkkkk...
...kmmmmmmmk....
....kmmmmmmk....
.....kmmmmk.....
....kmmkmmmk....
...kmmk..kmmk...
..kmk......kmk..
..kk........kk..
................
................
................
................
"""

ICONS["scroll"] = """
................
....kkkkkkk.....
...krrrrrwrk....
...krrwwwrrk....
...krrrrrwrk....
...krwwwrrrk....
...krrrrrwrk....
...krrwwwrrk....
...krrrrrwrk....
...krrwwwrrk....
...krrrrrwrk....
...krrrrrwrk....
....kkkkkkk.....
................
................
................
"""

ICONS["envelope"] = """
................
................
..kkkkkkkkkkk...
..kwwwwwwwwwk...
..kwkkkkkkkwk...
..kwwkwwwkwwk...
..kwwwkwkwwwk...
..kwwwwkwwwwk...
..kwwwwwwwwwk...
..kwwwwwwwwwk...
..kkkkkkkkkkk...
................
................
................
................
................
"""

ICONS["briefcase"] = """
................
.....kkkkk......
....kmmmmmk.....
..kkkkkkkkkkk...
..kmmmmmmmmmk...
..kmmkkkkkmmk...
..kmmmmmmmmmk...
..kmmmmmmmmmk...
..kmmmmmmmmmk...
..kmmmmmmmmmk...
..kkkkkkkkkkk...
................
................
................
................
................
"""

ICONS["more"] = """
................
................
................
................
................
................
..kk..kk..kk....
..kwwkwwkwwk....
..kwwkwwkwwk....
..kk..kk..kk....
................
................
................
................
................
................
"""

ICONS["menu"] = """
................
................
..kkkkkkkkkkk...
..kwwwwwwwwwk...
..kkkkkkkkkkk...
................
..kkkkkkkkkkk...
..kwwwwwwwwwk...
..kkkkkkkkkkk...
................
..kkkkkkkkkkk...
..kwwwwwwwwwk...
..kkkkkkkkkkk...
................
................
................
"""

ICONS["calendar"] = """
................
...kk....kk.....
..kkkkkkkkkkk...
..kwwwwwwwwwk...
..kwwkkkkkwwk...
..kwkwkwkwkwk...
..kwkwkwkwkwk...
..kwkwkckwkwk...
..kwkwkwkwkwk...
..kwkwkwkwkwk...
..kwwwwwwwwwk...
..kkkkkkkkkkk...
................
................
................
................
"""

ICONS["grid"] = """
................
..kk.kk.kk......
..kwwkmkwwk.....
..kk.kk.kk......
................
..kk.kk.kk......
..kwwkmkwwk.....
..kk.kk.kk......
................
..kk.kk.kk......
..kwwkmkwwk.....
..kk.kk.kk......
................
................
................
................
"""

ICONS["warning"] = """
................
.......k........
......kGk.......
......kGk.......
.....kGGGk......
.....kGwGk......
....kGGwGGk.....
....kGGwGGk.....
...kGGGwGGGk....
...kGGGwGGGk....
..kGGGkkGGGGk...
..kGGGkkGGGGk...
..kGGGGGGGGGk...
...kkkkkkkkk....
................
................
"""

ICONS["flask"] = """
................
......kkkk......
......kwwk......
......kwwk......
......kwwk......
.....kcccck.....
....kcccccck....
...kcccccccck...
...kccckcccck...
...kcccccccck...
...kcccccccck...
....kcccccck....
.....kkkkkk.....
................
................
................
"""

ICONS["crate"] = """
................
....kkkkkkkk....
...krrrrrrrrk...
..krrrrrrrrrrk..
..krrkkkkkkrrk..
..krrkrrrrkrrk..
..krrkrrrrkrrk..
..krrkkkkkkrrk..
..krrrrrrrrrrk..
..krrrrrrrrrrk..
..krrkkkkkkrrk..
..kkkkkkkkkkkk..
................
................
................
................
"""

ICONS["bag"] = """
................
.....kkkk.......
....kmmmmk......
...kmmmmmmk.....
..kkkkkkkkkk....
..kbbbbbbbbk....
..kbwwwwwwbk....
..kbwbbbbwbk....
..kbwbbbbwbk....
..kbwwwwwwbk....
..kbbbbbbbbk....
..kkkkkkkkkk....
................
................
................
................
"""

ICONS["gear"] = """
................
......kmmk......
...kk.kmmk.kk...
...kmmmmmmmmk...
..kkmmkwwkmmkk..
...kmmwwwwmmk...
...kmwwwwwwmk...
...kmwwkkwmk....
...kmmwwwwmmk...
..kkmmkwwkmmkk..
...kmmmmmmmmk...
...kk.kmmk.kk...
......kmmk......
................
................
................
"""

ICONS["cards"] = """
................
....kkkkkkk.....
...kwwwwwwwk....
...kwkkkkkkwk...
..kkkkkkkkwk....
..kwwwwwwkwk....
..kwkkkkkwk.....
.kkkkkkkwk......
.kwwwwwwk.......
.kwkkkkkk.......
.kwwwwwwk.......
.kkkkkkk........
................
................
................
................
"""

ICONS["gavel"] = """
................
.........kkkk...
........krrrrk..
.......krrrrk...
......krrrrk....
.....krrrk......
....krrrk.......
...kgggk........
...kggk.........
...kggk.........
...kggk.........
..kkkkk.........
.kmmmmmk........
.kkkkkkk........
................
................
"""

ICONS["folder"] = """
................
..kkkkk.........
..kggggkkkkk....
..kgggggggggk...
..kgggggggggk...
..kgggggggggk...
..kgggggggggk...
..kgggggggggk...
..kgggggggggk...
..kgggggggggk...
..kkkkkkkkkkk...
................
................
................
................
................
"""

ICONS["pin"] = """
................
......kkkk......
.....kRRRRk.....
....kRRwwRRk....
....kRRwwRRk....
....kRRRRRRk....
.....kRRRRk.....
......kRRk......
.......kk.......
.......kk.......
.......kk.......
.......kk.......
.......kk.......
........k.......
................
................
"""

ICONS["wrench"] = """
................
....kk..........
...kmmk.........
...kmmkkkk......
....kkmmmmk.....
.....kmmmmk.....
......kmmk......
.....kmmk.......
....kmmk........
...kmmk.........
..kmmk..........
..kmk...........
..kk............
................
................
................
"""

ICONS["sync"] = """
................
......kkkk......
....kkcccckk....
...kc......ck...
..kc........ck..
..kc...kk...ck..
..kc...kc...ck..
..kckkkkc...ck..
...kccccc..ck...
....kkkk...k....
......kckkk.....
......kccc......
.......kk.......
................
................
................
"""

ICONS["plug"] = """
................
....k..k........
....k..k........
....k..k........
...kkkkkk.......
...kpppkk.......
...kppppk.......
...kppppk.......
...kppppk.......
....kppk........
....kppk........
....kppk........
.....kk.........
................
................
................
"""

ICONS["walk"] = """
................
......kk........
.....kssk.......
.....kssk.......
......kk........
.....ktttk......
....ktktktk.....
....ktk.k.k.....
....ktt.ttk.....
.....kk.k.......
....k...kk......
....k...k.k.....
...kk...k.k.....
................
................
................
"""

ICONS["album"] = """
................
.....kkkkk......
....kbbbbbbk....
...kbwwwwwbk....
...kbwkkkwbk....
...kbwkbkwbk....
...kbwkkkwbk....
...kbwwwwwbk....
...kbbbbbbbk....
....kkkkkkk.....
................
................
................
................
................
................
"""

ICONS["clock"] = """
................
.....kkkkk......
....kwwwwwk.....
...kwwkwkwwk....
...kwwkwkwwk....
...kwwkwkwwk....
...kwwkkkkwwk...
...kwwwwwkwwk...
...kwwwwwwwwk...
....kwwwwwk.....
.....kkkkk......
................
................
................
................
................
"""

ICONS["handshake"] = """
................
................
.kkkk....kkkk...
.ksssk..ksssk...
.kssssk.ksssk...
..ksssskksssk...
...ksssssssk....
....kssssssk....
.....kkkkkk.....
......kttk......
......kttk......
................
................
................
................
................
"""

ICONS["building"] = """
................
....kkkkkkkk....
....kwwkwwwwk...
....kwckwcwwk...
....kwwkwwwwk...
....kwckwcwwk...
....kwwkwwwwk...
....kwckwcwwk...
....kwwkwwwwk...
....kkkkkkkkk...
....kmmk.kmmk...
....kmmk.kmmk...
....kkkkkkkkk...
................
................
................
"""

ICONS["task"] = """
................
..kkkkkkkk......
..kwwwwwwwk.....
..kwkkkkkwk.....
..kwwwwwwwk.....
..kwk.kewwk.....
..kwwwwwwwk.....
..kwk.kewwk.....
..kwwwwwwwk.....
..kwk.kewwk.....
..kwwwwwwwk.....
..kkkkkkkkk.....
................
................
................
................
"""

ICONS["sun"] = """
................
.......k........
...k...g...k....
....k.gGg.k.....
.....kGGGk......
...k.gGGGg.k....
..kgGGGGGGGgk...
...k.gGGGg.k....
.....kGGGk......
....k.gGg.k.....
...k...g...k....
.......k........
................
................
................
................
"""

ICONS["bed"] = """
................
................
..kk............
..knk...........
..knnkkkkkkkkk..
..knnnnnnnnnnk..
..kkkkkkkkkkkk..
..kmmkkkkkkmmk..
..kmmk....kmmk..
..kkkk....kkkk..
................
................
................
................
................
................
"""

ICONS["search"] = """
................
....kkkk........
...kwwwwk.......
..kww..wwk......
..kww..wwk......
...kwwwwk.k.....
....kkkk.kwk....
.........kwk....
..........kk....
................
................
................
................
................
................
................
"""

ICONS["plus"] = """
................
................
......kk........
......kwwk......
......kwwk......
..kkkkkwwkkkk...
..kwwwwwwwwwk...
..kkkkkwwkkkk...
......kwwk......
......kwwk......
......kk........
................
................
................
................
................
"""

ICONS["check"] = """
................
................
.............k..
............kek.
...........kek..
..........kek...
...k.....kek....
..kek...kek.....
...kek.kek......
....kekek.......
.....kek........
......k.........
................
................
................
................
"""

ICONS["close"] = """
................
................
...kk.....kk....
...kRk...kRk....
....kRk.kRk.....
.....kRkRk......
......kRk.......
.....kRkRk......
....kRk.kRk.....
...kRk...kRk....
...kk.....kk....
................
................
................
................
................
"""

ICONS["inbox"] = """
................
....kkkkkkk.....
...kwwwwwwwk....
...kwkkkkkkwk...
...kwwwwwwwk....
..kkkkkkkkkkk...
..kwwwwwwwwwk...
..kwwkkkkkwwk...
..kwwwwwwwwwk...
..kwwwwwwwwwk...
..kkkkkkkkkkk...
................
................
................
................
................
"""

ICONS["shield"] = """
................
.....kkkkkk.....
....kwwwwwwk....
...kwggggggwk...
...kwggwwggwk...
...kwggwwggwk...
...kwggggggwk...
...kwggggggwk...
....kwggggwk....
....kwggggwk....
.....kwggwk.....
......kwwk......
.......kk.......
................
................
................
"""

ICONS["waypoint"] = """
................
......kkkk......
.....kRRRRk.....
....kRRwwRRk....
....kRRwwRRk....
.....kRRRRk.....
......kRRk......
.......kk.......
.......kk.......
.......kk.......
......kwwk......
.....kwwwwk.....
......kkkk......
................
................
................
"""

ICONS["protocol"] = """
................
..kkkkkkkkkkk...
..kwwwwwwwwwk...
..kwkkkkkkw.k...
..kwwwwwwww.k...
..kwk.kewww.k...
..kwwwwwwww.k...
..kwk.kewww.k...
..kwwwwwwwwwk...
..kkkkkkkkkkk...
......kmmk......
......kmmk......
.....kkkkkk.....
................
................
................
"""

ICONS["radio"] = """
................
.............k..
............kmk.
...........kmmk.
..kkkkkkkkkkk...
..kmmmmmmmmmk...
..kmwwkwwkwmk...
..kmmmmmmmmmk...
..kmmkkkkkmmk...
..kmmmmmmmmmk...
..kkkkkkkkkkk...
....kk...kk.....
................
................
................
................
"""

ICONS["map"] = """
................
..kkkkkkkkkkk...
..keeegggbbbk...
..keeegggbbbk...
..kgggeeebbbk...
..kgggeeerrrk...
..kbbbeeerrrk...
..kbbbrrrgggk...
..krrrgggeeek...
..kkkkkkkkkkk...
................
................
................
................
................
"""

ICONS["compass"] = """
................
.....kkkkk......
....kwwwwwk.....
...kwwkRRwwk....
...kwwkRRwwk....
...kwwkkkkwwk...
...kwwwwRRwwk...
...kwwwwRRwwk...
...kwwwwwwwwk...
....kwwwwwk.....
.....kkkkk......
................
................
................
................
................
"""

ICONS["key"] = """
................
................
....kkkk........
...kggggk.......
...kggwggk......
...kggggk.......
....kkggkkkkkk..
.....kggk..k.k..
......kk........
................
................
................
................
................
................
"""

ICONS["terminal"] = """
................
..kkkkkkkkkkk...
..kccccccccck...
..kc......kck...
..kc.kk...kck...
..kc......kck...
..kccccccccck...
..kkkkkkkkkkk...
..kmmmmmmmmmk...
..kmmkkkkkmmk...
..kmmmmmmmmmk...
..kkkkkkkkkkk...
................
................
................
................
"""

ICONS["satellite"] = """
................
.kk.........kk.
.kck.......kck.
..kck.....kck..
...kckkkkkck...
....kccccck....
.....kccck.....
......kkk......
.......k.......
......kmk......
.....kmmmk.....
......kkk......
................
................
................
"""

ICONS["battery"] = """
................
.....kkkk.......
....kwwwwk......
...kwwwwwwk.....
...kweeeeewk....
...kweeeeewk....
...kweeeeewk....
...kwwwwwwk.....
...kwwwwwwk.....
....kwwwwk......
.....kkkk.......
................
................
................
................
"""

ICONS["droplet"] = """
................
.......k........
......kck.......
.....kccck......
....kccccck.....
...kccccccck....
...kcccwwcck....
...kccccccck....
....kccccck.....
.....kccck......
......kkk.......
................
................
................
................
"""

ICONS["pill"] = """
................
................
.....kkkkkkk....
....kwwwwwcck...
...kwwwwwccck...
...kwwwwwccck...
....kwwwwcck....
.....kkkkkkk....
................
................
................
................
................
................
................
"""

ICONS["tent"] = """
................
.......k........
......krk.......
.....krrrkk.....
....krrrrrkk....
...krrrrrrrkk...
..krrrrrrrrrkk..
..kkkkkkkkkkkk..
..kwwk....kwwk..
..kwwk....kwwk..
..kkkk....kkkk..
................
................
................
................
"""

ICONS["antenna"] = """
................
.......k........
.......k........
......kmk.......
.....kmmmk......
......kmk.......
.......k........
....kkkkkkk.....
...kmmmmmmmk....
...kmmk.kmmk....
...kmmk.kmmk....
...kkkkkkkk.....
................
................
................
"""

ICONS["hammer"] = """
................
........kkkkkk..
.......kmmmmmk..
......kmmmmmmk..
.....kmmkkkkk...
....kmmk........
...kmmk.........
..kmmk..........
.kmmk...........
.kmk............
.kk.............
................
................
................
................
"""

ICONS["leaf"] = """
................
.........kk.....
........keek....
.......keeek....
......keeeek....
.....keeeek.....
....keeeek......
...keeeek.......
..keeek.........
.keek...........
.kkk............
................
................
................
................
"""

ICONS["chip"] = """
................
..k.k.k.k.k.k...
.kkkkkkkkkkkkk..
.kmmwwwwwwwmmk..
.kmmwwkkwkwmmk..
.kmmwwwwwwwmmk..
.kmmwwkkwkwmmk..
.kmmwwwwwwwmmk..
.kkkkkkkkkkkkk..
..k.k.k.k.k.k...
................
................
................
................
................
"""

ICONS["constellation"] = """
................
..kk............
..kck....kk.....
...k....kck.....
....k....k......
.....k.kk.......
......kck.......
...kk..k........
..kck...........
...k.....kk.....
.........kck....
..........k.....
................
................
................
"""

ICONS["flashlight"] = """
................
.............kk.
............kGk.
...kkkkkkkkkkGk.
...kmmmmmmmmkGk.
...kmmmmmmmmkkk.
...kkkkkkkkkk...
................
................
................
................
................
................
................
................
"""

ICONS["medal"] = """
................
....kk....kk....
.....kkkkkk.....
......kggk......
.....kGGGGk.....
....kGGwwGGk....
....kGGwwGGk....
....kGGGGGGk....
.....kGGGGk.....
......kkkk......
................
................
................
................
................
"""

ICONS["bolt"] = """
................
.......kk.......
......kGGk......
.....kGGGk......
....kGGGk.......
...kGGGGGkk.....
......kGGk......
.....kGGk.......
....kGGk........
....kGk.........
.....k..........
................
................
................
................
"""

ICONS["thermometer"] = """
................
......kkkk......
.....kwwwwk.....
.....kwkkwk.....
.....kwkkwk.....
.....kwRRwk.....
.....kwRRwk.....
....kRRRRkk.....
....kRRRRwk.....
.....kRRRk......
......kkkk......
................
................
................
................
"""

ICONS["wallet"] = """
................
................
..kkkkkkkkkkk...
..krrrrrrrrrk...
..krrrrrrrrrk...
..krrkkkkkkkk...
..krrkGGGGGgk...
..krrkGwwwGgk...
..krrkGGGGGgk...
..krrkkkkkkkk...
..kkkkkkkkkkk...
................
................
................
................
"""

ICONS["chart"] = """
................
................
.k...........k..
.k......kk...k..
.k.....kee...k..
.k..kk.kee...k..
.k.kee.kee.kkk..
.k.kee.kee.keek.
.k.kee.kee.keek.
.kkkkkkkkkkkkkk.
................
................
................
................
................
"""

ICONS["truck"] = """
................
................
.....kkkkkkk....
....kmmmmmmmk...
.kkkkmmwwwmmk...
.kmmmmmmmmmmk...
.kmmmmmmmmmmk...
.kkkkkkkkkkkk...
..kk.kk...kk....
..kmkkmk.kmmk...
...kkk....kk....
................
................
................
................
"""

ICONS["plane"] = """
................
.......k........
......kmk.......
.kkkkkkmmkkkkk..
....kmmmmmmk....
.....kmmmmk.....
......kmmk......
.....kmmmmk.....
....kmk..kmk....
...kk......kk...
................
................
................
................
................
"""

ICONS["coffee"] = """
................
........kk......
.......k..k.....
..kkkkkkkkkkk...
..kwwwwwwwwwk...
..kwwrrrrrwwk...
..kwwrrrrrwwk...
..kwwwwwwwwwk...
...kkkkkkkkk....
....kmmmmmk.....
.....kkkkk......
................
................
................
................
"""

ICONS["dumbbell"] = """
................
................
..kk......kk....
..kmk....kmk....
..kmmkkkkmmk....
..kmmmmmmmmk....
..kmmkkkkmmk....
..kmk....kmk....
..kk......kk....
................
................
................
................
................
................
"""

ICONS["diary"] = """
................
....kkkkkkkk....
...krrrrrrwrk...
...krrwwwrwrk...
...krrrrrrwrk...
...krrwwwrwrk...
...krrrrrrwrk...
...krrwwwrwrk...
...krrrrrrwrk...
...krrrrrrwrk...
....kkkkkkkk....
.....k....k.....
................
................
................
"""

ICONS["bandage"] = """
................
................
.....kkkkkkk....
....kwwwwwwwk...
...kwwkkkkkwwk..
...kwwkwwwkwwk..
...kwwkkkkkwwk..
....kwwwwwwwk...
.....kkkkkkk....
................
................
................
................
................
"""

ICONS["target"] = """
................
.....kkkkk......
....kccccck.....
...kc....kck....
..kc..kk..kck...
..kc.kRRk.kck...
..kc.kRRk.kck...
..kc..kk..kck...
...kc....kck....
....kccccck.....
.....kkkkk......
................
................
................
................
"""

ICONS["activation"] = ICONS["walk"]
ICONS["health"] = ICONS["heart"]
ICONS["finance"] = ICONS["coin"]
ICONS["habitat"] = ICONS["house"]
ICONS["chronicle"] = ICONS["book"]
ICONS["quests"] = ICONS["flag"]
ICONS["profile"] = ICONS["person"]
ICONS["work"] = ICONS["briefcase"]
ICONS["colony"] = ICONS["people"]
ICONS["research"] = ICONS["flask"]
ICONS["inventory"] = ICONS["crate"]
ICONS["travel"] = ICONS["bag"]
ICONS["settings"] = ICONS["gear"]
ICONS["flashcards"] = ICONS["cards"]
ICONS["decisions"] = ICONS["gavel"]
ICONS["projects"] = ICONS["folder"]
ICONS["zones"] = ICONS["pin"]
ICONS["home"] = ICONS["wrench"]
ICONS["integrations"] = ICONS["plug"]
ICONS["music"] = ICONS["album"]
ICONS["schedule"] = ICONS["clock"]
ICONS["commitments"] = ICONS["handshake"]
ICONS["organizations"] = ICONS["building"]
ICONS["tasks"] = ICONS["task"]
ICONS["today"] = ICONS["sun"]
ICONS["sleep"] = ICONS["moon"]
ICONS["focus"] = ICONS["crosshair"]
ICONS["class"] = ICONS["cap"]
ICONS["meal"] = ICONS["utensils"]
ICONS["free"] = ICONS["star"]
ICONS["exercise"] = """
................
......kk........
.....kssk.......
.....kssk.......
......kk........
...kkttttkk.....
..kttkkkkttk....
..ktk....ktk....
..ktk....ktk....
...kk....kk.....
...k.k..k.k.....
..kk.k..k.kk....
................
................
................
................
"""
ICONS["commute"] = """
................
................
....kkkkkkk.....
...kmmmmmmmk....
..kmmwwwwwmmk...
..kmwwkkkkkwmk..
..kmwkk..kkwmk..
..kmmwwwwwmmk...
..kmmmmmmmmmk...
..kkkkkkkkkkk...
..k.kk...kk.k...
...kk.....kk....
................
................
................
................
"""
ICONS["meeting"] = ICONS["people"]
ICONS["social"] = ICONS["handshake"]
ICONS["recovery"] = ICONS["bed"]
ICONS["routine"] = ICONS["clock"]
ICONS["unavailable"] = ICONS["close"]
ICONS["friendships"] = ICONS["heart"]
ICONS["people_nav"] = ICONS["people"]
ICONS["circles"] = """
................
.....kkkkk......
....kccccck.....
...kc....kck....
..kc..kk..kck...
..kc.kccck.ck...
..kc.kc.ck.ck...
..kc.kccck.ck...
..kc..kk..kck...
...kc....kck....
....kccccck.....
.....kkkkk......
................
................
................
................
"""
ICONS["encounters"] = ICONS["calendar"]
ICONS["pawn_create"] = ICONS["person"]
ICONS["info"] = """
................
......kkkk......
.....kwwwwk.....
....kwwkkwwk....
....kwwkkwwk....
.....kwwwwk.....
......kkkk......
......kwwk......
......kwwk......
......kwwk......
......kwwk......
......kwwk......
......kkkk......
................
................
................
"""
ICONS["alert"] = ICONS["warning"]
ICONS["lock"] = """
................
.....kkkkk......
....kmmmmmk.....
....km...mk.....
....km...mk.....
...kkkkkkkkk....
...kgggggggk....
...kggwggggk....
...kggwggggk....
...kgggggggk....
...kgggggggk....
...kkkkkkkkk....
................
................
................
................
"""
ICONS["chevron"] = """
................
................
....kk..........
....kmk.........
.....kmk........
......kmk.......
.......kmk......
......kmk.......
.....kmk........
....kmk.........
....kk..........
................
................
................
................
................
"""


def render_icon(name: str, scale=3) -> Image.Image:
    rows = ico(ICONS[name])
    sp = Sprite(16, 16)
    sp.stamp(0, 0, rows, P)
    return sp.image(scale)


def make_mono(im: Image.Image, color=W) -> Image.Image:
    out = Image.new("RGBA", im.size, (0, 0, 0, 0))
    src = im.load()
    dst = out.load()
    for y in range(im.height):
        for x in range(im.width):
            a = src[x, y][3]
            if a > 20:
                dst[x, y] = (color[0], color[1], color[2], a)
    return out


def process_portrait() -> Image.Image:
    src_path = next((p for p in (PORTRAIT_SRC, PORTRAIT_REPO) if p.exists()), None)
    canvas = Image.new("RGBA", (64, 64), (18, 20, 24, 255))
    if src_path is None:
        sp = Sprite(32, 32)
        sp.stamp(8, 4, ico(ICONS["person"]), P)
        return sp.image(2)

    src = Image.open(src_path).convert("RGBA")
    # drop near-black so the inset well shows through at the corners
    px = src.load()
    for y in range(src.height):
        for x in range(src.width):
            r, g, b, a = px[x, y]
            if r < 18 and g < 18 and b < 18:
                px[x, y] = (0, 0, 0, 0)
    bbox = src.getbbox()
    if bbox:
        src = src.crop(bbox)
    # chunky pixels: box-down then nearest up
    small = src.resize((40, 48), Image.Resampling.BOX)
    pal = small.convert("P", palette=Image.Palette.ADAPTIVE, colors=16)
    small = pal.convert("RGBA")
    pixel = small.resize((48, 56), Image.Resampling.NEAREST)
    canvas.paste(pixel, (8, 4), pixel)
    return canvas


def make_hull_plates() -> Image.Image:
    src = METAL_SRC if METAL_SRC.exists() else METAL_REPO
    if src.exists():
        im = Image.open(src).convert("RGBA")
        im = im.resize((64, 64), Image.Resampling.BOX)
        return ImageEnhance.Brightness(im).enhance(0.55)
    return make_grain(64)


def make_catalog(icons: dict[str, Image.Image]) -> Image.Image:
    names = sorted(icons)
    cols = 8
    rows = math.ceil(len(names) / cols)
    cell = 72
    im = Image.new("RGBA", (cols * cell, rows * cell + 24), (*VOID[:3], 255))
    d = ImageDraw.Draw(im)
    for i, name in enumerate(names):
        x = (i % cols) * cell
        y = (i // cols) * cell
        icon = icons[name].resize((48, 48), Image.Resampling.NEAREST)
        im.paste(icon, (x + 12, y + 4), icon)
        d.text((x + 4, y + 54), name[:10], fill=W)
    return im


def main():
    for p in (TERM / "icons", TERM / "chrome", TERM / "portraits", TERM / "textures", CHROME, CATALOG):
        p.mkdir(parents=True, exist_ok=True)

    grain = make_grain(64)
    grain.save(TERM / "textures/metal_grain.png")
    grain.save(CHROME / "void_fill.png")
    hull = make_hull_plates()
    hull.save(TERM / "textures/hull_plates.png")

    panel = make_panel_9(36, PANEL, inset=False)
    inset = make_panel_9(36, (18, 20, 24, 255), inset=True)
    panel.save(CHROME / "panel_base.9.png")
    inset.save(CHROME / "menu_section.9.png")
    panel.save(TERM / "chrome/panel_rivet.png")
    inset.save(TERM / "chrome/panel_inset.png")

    btn = make_button_9((48, 24), False)
    btn_p = make_button_9((48, 24), True)
    btn.save(CHROME / "button_text_normal.9.png")
    btn.save(CHROME / "button_text_hover.9.png")
    btn_p.save(CHROME / "button_text_pressed.9.png")
    btn_p.save(CHROME / "button_text_disabled.9.png")
    btn.save(TERM / "chrome/button_copper.png")
    btn_p.save(TERM / "chrome/button_copper_pressed.png")

    # needs bar fill — cyan pixel grain
    bar = Image.new("RGBA", (8, 8), CYAN)
    bp = bar.load()
    for y in range(8):
        for x in range(8):
            if (x + y) % 3 == 0:
                bp[x, y] = CYAN_D
    bar.save(CHROME / "needs_bar_fill.png")
    Image.new("RGBA", (8, 8), (255, 255, 255, 18)).save(CHROME / "light_highlight.png")
    Image.new("RGBA", (8, 8), (8, 10, 12, 255)).save(CHROME / "alt_row.png")

    rendered = {}
    for name in sorted(set(ICONS)):
        img = render_icon(name, scale=3)  # 48x48
        img.save(TERM / "icons" / f"{name}.png")
        rendered[name] = img
        make_mono(img).save(TERM / "icons" / f"{name}_mono.png")

    portrait = process_portrait()
    portrait.save(TERM / "portraits/pawn_default.png")
    # also 32px nearest for tiny
    portrait.resize((32, 32), Image.Resampling.NEAREST).save(
        TERM / "portraits/pawn_default_32.png"
    )

    cat = make_catalog(rendered)
    cat.save(CATALOG / "icon_catalog.png")
    cat.save(TERM / "catalog/icon_catalog.png")

    portrait.resize((128, 128), Image.Resampling.NEAREST).save(CATALOG / "pawn_default.png")
    grain.save(CATALOG / "metal_grain.png")
    hull.resize((128, 128), Image.Resampling.NEAREST).save(CATALOG / "hull_plates.png")
    panel.resize((144, 144), Image.Resampling.NEAREST).save(CATALOG / "panel_rivet.png")
    (CATALOG / "ICON_INDEX.txt").write_text("\n".join(sorted(rendered)) + "\n")

    print(f"wrote {len(rendered)} icons -> {TERM / 'icons'}")
    print("chrome + portraits + catalog ok")


if __name__ == "__main__":
    main()
