part of 'habitat_social_dialogue.dart';

/// Banco grande de falas e conversas longas (SpeakUp-lite content pack).
///
/// Placeholders: `{named}`, `{namedLead}`, `{phase}`, `{temp}`, `{venue}`,
/// `{beauty}`, `{light}`.
abstract final class SocialDialoguePack {
  static List<SocialDialogueRule> get rules => _rules;
  static List<DialogueThread> get threads => _threads;
}

// ---------------------------------------------------------------------------
// Rules — open / reply / follow / farewell
// ---------------------------------------------------------------------------

final List<SocialDialogueRule> _rules = [
  // ===== roomBeauty =====
  SocialDialogueRule(
    id: 'ob1',
    role: SocialDialogueRole.open,
    topic: SocialTopic.roomBeauty,
    replyTag: 'beauty_ok',
    priority: 2,
    template: 'Aqui tá {beauty}{named}.',
    when: (c) => c.beautyBand != 'low',
  ),
  SocialDialogueRule(
    id: 'ob2',
    role: SocialDialogueRole.open,
    topic: SocialTopic.roomBeauty,
    replyTag: 'beauty_ok',
    template: '{namedLead}gosto desse canto.',
    when: (c) => c.beautyBand == 'high',
  ),
  SocialDialogueRule(
    id: 'ob3',
    role: SocialDialogueRole.open,
    topic: SocialTopic.roomBeauty,
    replyTag: 'beauty_ok',
    template: 'Esse espaço respira melhor hoje.',
    when: (c) => c.beautyBand == 'high' && c.cleanBand != 'low',
  ),
  SocialDialogueRule(
    id: 'ob4',
    role: SocialDialogueRole.open,
    topic: SocialTopic.roomBeauty,
    replyTag: 'beauty_ask',
    template: 'Você também sente que ficou mais leve aqui?',
    when: (c) => c.beautyBand != 'low',
  ),
  SocialDialogueRule(
    id: 'ob5',
    role: SocialDialogueRole.open,
    topic: SocialTopic.roomBeauty,
    replyTag: 'beauty_ok',
    template: 'Olha a luz batendo na parede…',
    when: (c) => c.lightBand != 'dark' && c.beautyBand == 'high',
  ),
  SocialDialogueRule(
    id: 'rb1',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.roomBeauty,
    replyTag: 'beauty_ok',
    template: 'Pois é{named}.',
  ),
  SocialDialogueRule(
    id: 'rb2',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.roomBeauty,
    replyTag: 'beauty_ok',
    template: 'Dá pra relaxar.',
  ),
  SocialDialogueRule(
    id: 'rb3',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.roomBeauty,
    replyTag: 'beauty_ok',
    template: 'Eu também notei.',
  ),
  SocialDialogueRule(
    id: 'rb4',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.roomBeauty,
    replyTag: 'beauty_ok',
    template: 'Fica bom demais assim.',
  ),
  SocialDialogueRule(
    id: 'rb5',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.roomBeauty,
    replyTag: 'beauty_ask',
    template: 'Sinto. Menos peso no peito.',
  ),
  SocialDialogueRule(
    id: 'rb6',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.roomBeauty,
    replyTag: 'beauty_ask',
    template: 'Sim. Parece outra sala.',
  ),
  SocialDialogueRule(
    id: 'fb1',
    role: SocialDialogueRole.follow,
    topic: SocialTopic.roomBeauty,
    replyTag: 'beauty_ok',
    template: 'Vale a pena cuidar disso.',
  ),
  SocialDialogueRule(
    id: 'fb2',
    role: SocialDialogueRole.follow,
    topic: SocialTopic.roomBeauty,
    replyTag: 'beauty_ok',
    template: 'Quando tá assim, o dia rende.',
  ),
  SocialDialogueRule(
    id: 'fb3',
    role: SocialDialogueRole.follow,
    topic: SocialTopic.roomBeauty,
    replyTag: 'beauty_ask',
    template: 'A gente merece um canto assim.',
  ),

  // ===== lampLight =====
  SocialDialogueRule(
    id: 'ol1',
    role: SocialDialogueRole.open,
    topic: SocialTopic.lampLight,
    replyTag: 'lamp_ok',
    priority: 2,
    template: 'Essa luz ajuda{named}.',
    when: (c) => c.hasLamp && c.lightBand != 'dark',
  ),
  SocialDialogueRule(
    id: 'ol2',
    role: SocialDialogueRole.open,
    topic: SocialTopic.lampLight,
    replyTag: 'lamp_ok',
    template: 'Prefiro assim do que no escuro.',
    when: (c) => c.hasLamp,
  ),
  SocialDialogueRule(
    id: 'ol3',
    role: SocialDialogueRole.open,
    topic: SocialTopic.lampLight,
    replyTag: 'lamp_soft',
    template: 'A lâmpada deixa tudo mais manso.',
    when: (c) => c.hasLamp && c.phaseLabel != 'Dia',
  ),
  SocialDialogueRule(
    id: 'ol4',
    role: SocialDialogueRole.open,
    topic: SocialTopic.lampLight,
    replyTag: 'lamp_ok',
    template: 'Sem luz eu já estaria perdido.',
    when: (c) => c.hasLamp && c.lightBand == 'dim',
  ),
  SocialDialogueRule(
    id: 'rl1',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.lampLight,
    replyTag: 'lamp_ok',
    template: 'Verdade.',
  ),
  SocialDialogueRule(
    id: 'rl2',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.lampLight,
    replyTag: 'lamp_ok',
    template: 'Muito melhor.',
  ),
  SocialDialogueRule(
    id: 'rl3',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.lampLight,
    replyTag: 'lamp_soft',
    template: 'Acalma um pouco, né?',
  ),
  SocialDialogueRule(
    id: 'rl4',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.lampLight,
    replyTag: 'lamp_soft',
    template: 'Gosto desse tom.',
  ),
  SocialDialogueRule(
    id: 'fl1',
    role: SocialDialogueRole.follow,
    topic: SocialTopic.lampLight,
    replyTag: 'lamp_ok',
    template: 'Quem inventou lâmpada merece estátua.',
  ),
  SocialDialogueRule(
    id: 'fl2',
    role: SocialDialogueRole.follow,
    topic: SocialTopic.lampLight,
    replyTag: 'lamp_soft',
    template: 'Às vezes é só isso que falta.',
  ),

  // ===== filth =====
  SocialDialogueRule(
    id: 'of1',
    role: SocialDialogueRole.open,
    topic: SocialTopic.filth,
    replyTag: 'filth_floor',
    priority: 3,
    template: 'O chão tá pedindo vassoura{named}.',
    when: (c) => c.cleanBand == 'low',
  ),
  SocialDialogueRule(
    id: 'of2',
    role: SocialDialogueRole.open,
    topic: SocialTopic.filth,
    replyTag: 'filth_floor',
    template: 'Tem sujeira demais pra ignorar.',
    when: (c) => c.cleanBand == 'low',
  ),
  SocialDialogueRule(
    id: 'of3',
    role: SocialDialogueRole.open,
    topic: SocialTopic.filth,
    replyTag: 'filth_floor',
    template: 'Passar a vassoura ia mudar o humor da sala.',
    when: (c) => c.cleanBand == 'low',
  ),
  SocialDialogueRule(
    id: 'rf1',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.filth,
    replyTag: 'filth_floor',
    template: 'Concordo.',
  ),
  SocialDialogueRule(
    id: 'rf2',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.filth,
    replyTag: 'filth_floor',
    template: 'Eu também notei.',
  ),
  SocialDialogueRule(
    id: 'rf3',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.filth,
    replyTag: 'filth_floor',
    template: 'Depois a gente resolve.',
  ),
  SocialDialogueRule(
    id: 'ff1',
    role: SocialDialogueRole.follow,
    topic: SocialTopic.filth,
    replyTag: 'filth_floor',
    template: 'Não dá pra pensar direito assim.',
  ),

  // ===== weatherOut =====
  SocialDialogueRule(
    id: 'ow1',
    role: SocialDialogueRole.open,
    topic: SocialTopic.weatherOut,
    replyTag: 'weather_out',
    template: 'Lá fora tá {temp}{named}.',
    when: (c) => c.isOutdoor || c.phaseLabel == 'Entardecer',
  ),
  SocialDialogueRule(
    id: 'ow2',
    role: SocialDialogueRole.open,
    topic: SocialTopic.weatherOut,
    replyTag: 'weather_out',
    template: 'O {phase} lá fora tem cara de história.',
    when: (c) => c.phaseLabel == 'Entardecer' || c.phaseLabel == 'Noite',
  ),
  SocialDialogueRule(
    id: 'ow3',
    role: SocialDialogueRole.open,
    topic: SocialTopic.weatherOut,
    replyTag: 'weather_breeze',
    template: 'Sente esse ar?',
    when: (c) => c.isOutdoor,
  ),
  SocialDialogueRule(
    id: 'ow4',
    role: SocialDialogueRole.open,
    topic: SocialTopic.weatherOut,
    replyTag: 'weather_out',
    template: 'O céu tá falando mais alto que a gente.',
    when: (c) => c.isOutdoor && c.phaseLabel != 'Dia',
  ),
  SocialDialogueRule(
    id: 'rw1',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.weatherOut,
    replyTag: 'weather_out',
    template: 'Pois é.',
  ),
  SocialDialogueRule(
    id: 'rw2',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.weatherOut,
    replyTag: 'weather_out',
    template: 'Dá pra sentir.',
  ),
  SocialDialogueRule(
    id: 'rw3',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.weatherOut,
    replyTag: 'weather_breeze',
    template: 'Hmm. Bom.',
  ),
  SocialDialogueRule(
    id: 'rw4',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.weatherOut,
    replyTag: 'weather_breeze',
    template: 'Melhor que parede.',
  ),
  SocialDialogueRule(
    id: 'fw1',
    role: SocialDialogueRole.follow,
    topic: SocialTopic.weatherOut,
    replyTag: 'weather_out',
    template: 'Às vezes o lado de fora salva o dia.',
  ),

  // ===== mealTable =====
  SocialDialogueRule(
    id: 'ot1',
    role: SocialDialogueRole.open,
    topic: SocialTopic.mealTable,
    replyTag: 'table_chat',
    priority: 2,
    template: 'Mesa boa pra conversar{named}.',
    when: (c) => c.venue == SocialVenue.table,
  ),
  SocialDialogueRule(
    id: 'ot2',
    role: SocialDialogueRole.open,
    topic: SocialTopic.mealTable,
    replyTag: 'table_chat',
    template: 'Sentar aqui já muda o ritmo.',
    when: (c) => c.venue == SocialVenue.table,
  ),
  SocialDialogueRule(
    id: 'ot3',
    role: SocialDialogueRole.open,
    topic: SocialTopic.mealTable,
    replyTag: 'table_slow',
    template: 'Sem pressa nessa mesa, né?',
    when: (c) => c.venue == SocialVenue.table,
  ),
  SocialDialogueRule(
    id: 'rt1',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.mealTable,
    replyTag: 'table_chat',
    template: 'Concordo.',
  ),
  SocialDialogueRule(
    id: 'rt2',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.mealTable,
    replyTag: 'table_chat',
    template: 'É o melhor canto.',
  ),
  SocialDialogueRule(
    id: 'rt3',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.mealTable,
    replyTag: 'table_slow',
    template: 'Sem pressa.',
  ),
  SocialDialogueRule(
    id: 'rt4',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.mealTable,
    replyTag: 'table_slow',
    template: 'Pode ficar.',
  ),
  SocialDialogueRule(
    id: 'ft1',
    role: SocialDialogueRole.follow,
    topic: SocialTopic.mealTable,
    replyTag: 'table_chat',
    template: 'Comida e papo — combo clássico.',
  ),

  // ===== workDesk =====
  SocialDialogueRule(
    id: 'od1',
    role: SocialDialogueRole.open,
    topic: SocialTopic.workDesk,
    replyTag: 'work_desk',
    template: 'A mesa de trabalho tá te cobrando{named}?',
    when: (c) => c.isOffice,
  ),
  SocialDialogueRule(
    id: 'od2',
    role: SocialDialogueRole.open,
    topic: SocialTopic.workDesk,
    replyTag: 'work_desk',
    template: 'Trabalho puxa, mas o corpo também.',
    when: (c) => c.isOffice,
  ),
  SocialDialogueRule(
    id: 'od3',
    role: SocialDialogueRole.open,
    topic: SocialTopic.workDesk,
    replyTag: 'work_pause',
    template: 'Pausa rápida conta como progresso?',
    when: (c) => c.isOffice,
  ),
  SocialDialogueRule(
    id: 'rd1',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.workDesk,
    replyTag: 'work_desk',
    template: 'Um pouco, sim.',
  ),
  SocialDialogueRule(
    id: 'rd2',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.workDesk,
    replyTag: 'work_desk',
    template: 'Sempre cobra.',
  ),
  SocialDialogueRule(
    id: 'rd3',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.workDesk,
    replyTag: 'work_pause',
    template: 'Conta. E salva.',
  ),
  SocialDialogueRule(
    id: 'rd4',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.workDesk,
    replyTag: 'work_pause',
    template: 'Eu voto que sim.',
  ),
  SocialDialogueRule(
    id: 'fd1',
    role: SocialDialogueRole.follow,
    topic: SocialTopic.workDesk,
    replyTag: 'work_desk',
    template: 'Depois a gente volta pra ela.',
  ),

  // ===== nightQuiet =====
  SocialDialogueRule(
    id: 'on1',
    role: SocialDialogueRole.open,
    topic: SocialTopic.nightQuiet,
    replyTag: 'night_quiet',
    priority: 2,
    template: 'A {phase} pede voz baixa{named}.',
    when: (c) => c.phaseLabel == 'Noite' || c.phaseLabel == 'Madrugada',
  ),
  SocialDialogueRule(
    id: 'on2',
    role: SocialDialogueRole.open,
    topic: SocialTopic.nightQuiet,
    replyTag: 'night_quiet',
    template: 'Tá quieto demais… gostei.',
    when: (c) => c.phaseLabel == 'Noite' || c.phaseLabel == 'Madrugada',
  ),
  SocialDialogueRule(
    id: 'on3',
    role: SocialDialogueRole.open,
    topic: SocialTopic.nightQuiet,
    replyTag: 'night_soft',
    template: 'Nesse silêncio a gente pensa melhor.',
    when: (c) => c.phaseLabel == 'Noite' || c.phaseLabel == 'Madrugada',
  ),
  SocialDialogueRule(
    id: 'rn1',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.nightQuiet,
    replyTag: 'night_quiet',
    template: 'É. Fica bom.',
  ),
  SocialDialogueRule(
    id: 'rn2',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.nightQuiet,
    replyTag: 'night_quiet',
    template: 'Shh… brincadeira.',
  ),
  SocialDialogueRule(
    id: 'rn3',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.nightQuiet,
    replyTag: 'night_soft',
    template: 'Ou pensa demais.',
  ),
  SocialDialogueRule(
    id: 'rn4',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.nightQuiet,
    replyTag: 'night_soft',
    template: 'Eu também sinto isso.',
  ),
  SocialDialogueRule(
    id: 'fn1',
    role: SocialDialogueRole.follow,
    topic: SocialTopic.nightQuiet,
    replyTag: 'night_quiet',
    template: 'Não precisa encher o ar.',
  ),

  // ===== crowding =====
  SocialDialogueRule(
    id: 'oc1',
    role: SocialDialogueRole.open,
    topic: SocialTopic.crowding,
    replyTag: 'crowd_tight',
    priority: 2,
    template: 'Aqui apertou{named}.',
    when: (c) => c.spaceTight,
  ),
  SocialDialogueRule(
    id: 'oc2',
    role: SocialDialogueRole.open,
    topic: SocialTopic.crowding,
    replyTag: 'crowd_tight',
    template: 'Falta um passo de folga.',
    when: (c) => c.spaceTight,
  ),
  SocialDialogueRule(
    id: 'rc1',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.crowding,
    replyTag: 'crowd_tight',
    template: 'Senti também.',
  ),
  SocialDialogueRule(
    id: 'rc2',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.crowding,
    replyTag: 'crowd_tight',
    template: 'Vamos abrir um pouco.',
  ),
  SocialDialogueRule(
    id: 'fc1',
    role: SocialDialogueRole.follow,
    topic: SocialTopic.crowding,
    replyTag: 'crowd_tight',
    template: 'Espaço é luxo.',
  ),

  // ===== cozyWarm =====
  SocialDialogueRule(
    id: 'oz1',
    role: SocialDialogueRole.open,
    topic: SocialTopic.cozyWarm,
    replyTag: 'cozy_ok',
    template: 'Tá aconchegante{named}.',
    when: (c) => c.comfortOk,
  ),
  SocialDialogueRule(
    id: 'oz2',
    role: SocialDialogueRole.open,
    topic: SocialTopic.cozyWarm,
    replyTag: 'cozy_ok',
    template: 'Dá vontade de ficar {venue}.',
    when: (c) => c.comfortOk,
  ),
  SocialDialogueRule(
    id: 'oz3',
    role: SocialDialogueRole.open,
    topic: SocialTopic.cozyWarm,
    replyTag: 'cozy_soft',
    template: 'Esse canto segura o cansaço.',
    when: (c) => c.comfortOk && c.beautyBand != 'low',
  ),
  SocialDialogueRule(
    id: 'rz1',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.cozyWarm,
    replyTag: 'cozy_ok',
    template: 'Concordo.',
  ),
  SocialDialogueRule(
    id: 'rz2',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.cozyWarm,
    replyTag: 'cozy_ok',
    template: 'Fica bom assim.',
  ),
  SocialDialogueRule(
    id: 'rz3',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.cozyWarm,
    replyTag: 'cozy_soft',
    template: 'Eu precisava disso.',
  ),
  SocialDialogueRule(
    id: 'fz1',
    role: SocialDialogueRole.follow,
    topic: SocialTopic.cozyWarm,
    replyTag: 'cozy_ok',
    template: 'Guardar esse momento.',
  ),

  // ===== idleLife =====
  SocialDialogueRule(
    id: 'oi1',
    role: SocialDialogueRole.open,
    topic: SocialTopic.idleLife,
    replyTag: 'idle_ok',
    template: 'E aí{named}.',
  ),
  SocialDialogueRule(
    id: 'oi2',
    role: SocialDialogueRole.open,
    topic: SocialTopic.idleLife,
    replyTag: 'idle_ok',
    template: 'Tudo bem por aí?',
  ),
  SocialDialogueRule(
    id: 'oi3',
    role: SocialDialogueRole.open,
    topic: SocialTopic.idleLife,
    replyTag: 'idle_day',
    template: 'Como tá o {phase}?',
  ),
  SocialDialogueRule(
    id: 'oi4',
    role: SocialDialogueRole.open,
    topic: SocialTopic.idleLife,
    replyTag: 'idle_ok',
    template: 'Te vejo {venue}.',
  ),
  SocialDialogueRule(
    id: 'oi5',
    role: SocialDialogueRole.open,
    topic: SocialTopic.idleLife,
    replyTag: 'idle_check',
    template: '{namedLead}parado um segundo?',
  ),
  SocialDialogueRule(
    id: 'oi6',
    role: SocialDialogueRole.open,
    topic: SocialTopic.idleLife,
    replyTag: 'idle_day',
    template: 'O dia tá andando… ou arrastando?',
  ),
  SocialDialogueRule(
    id: 'ri1',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.idleLife,
    replyTag: 'idle_ok',
    template: 'Tudo bem.',
  ),
  SocialDialogueRule(
    id: 'ri2',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.idleLife,
    replyTag: 'idle_ok',
    template: 'Na medida.',
  ),
  SocialDialogueRule(
    id: 'ri3',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.idleLife,
    replyTag: 'idle_ok',
    template: 'E você?',
  ),
  SocialDialogueRule(
    id: 'ri4',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.idleLife,
    replyTag: 'idle_day',
    template: 'Andando. Devagar.',
  ),
  SocialDialogueRule(
    id: 'ri5',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.idleLife,
    replyTag: 'idle_day',
    template: 'Mais arrastando, pra ser sincero.',
  ),
  SocialDialogueRule(
    id: 'ri6',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.idleLife,
    replyTag: 'idle_check',
    template: 'Pode ser.',
  ),
  SocialDialogueRule(
    id: 'ri7',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.idleLife,
    replyTag: 'idle_check',
    template: 'Claro.',
  ),
  SocialDialogueRule(
    id: 'fi1',
    role: SocialDialogueRole.follow,
    topic: SocialTopic.idleLife,
    replyTag: 'idle_ok',
    template: 'Bom te achar por aqui.',
  ),
  SocialDialogueRule(
    id: 'fi2',
    role: SocialDialogueRole.follow,
    topic: SocialTopic.idleLife,
    replyTag: 'idle_day',
    template: 'Se precisar, tô por perto.',
  ),

  // ===== humorBanter =====
  SocialDialogueRule(
    id: 'oh1',
    role: SocialDialogueRole.open,
    topic: SocialTopic.humorBanter,
    replyTag: 'humor_ok',
    template: 'Se eu sumir, foi a preguiça{named}.',
    when: (c) => c.affinity >= 0.35,
  ),
  SocialDialogueRule(
    id: 'oh2',
    role: SocialDialogueRole.open,
    topic: SocialTopic.humorBanter,
    replyTag: 'humor_ok',
    template: 'Notícia: ainda estou de pé.',
    when: (c) => c.affinity >= 0.35,
  ),
  SocialDialogueRule(
    id: 'oh3',
    role: SocialDialogueRole.open,
    topic: SocialTopic.humorBanter,
    replyTag: 'humor_dry',
    template: 'Prometi não reclamar. Já estou falhando.',
    when: (c) => c.affinity >= 0.4,
  ),
  SocialDialogueRule(
    id: 'oh4',
    role: SocialDialogueRole.open,
    topic: SocialTopic.humorBanter,
    replyTag: 'humor_ok',
    template: 'Se o chão pudesse julgar, a gente perdia.',
    when: (c) => c.affinity >= 0.35 && c.cleanBand == 'low',
  ),
  SocialDialogueRule(
    id: 'oh5',
    role: SocialDialogueRole.open,
    topic: SocialTopic.humorBanter,
    replyTag: 'humor_soft',
    template: 'Teu olhar diz “não me puxa assunto”.',
    when: (c) => c.affinity >= 0.45,
  ),
  SocialDialogueRule(
    id: 'rh1',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.humorBanter,
    replyTag: 'humor_ok',
    template: 'Ha. Bom.',
  ),
  SocialDialogueRule(
    id: 'rh2',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.humorBanter,
    replyTag: 'humor_ok',
    template: 'Clássico.',
  ),
  SocialDialogueRule(
    id: 'rh3',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.humorBanter,
    replyTag: 'humor_dry',
    template: 'Pelo menos é honesto.',
  ),
  SocialDialogueRule(
    id: 'rh4',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.humorBanter,
    replyTag: 'humor_soft',
    template: 'Mentira. Puxa.',
  ),
  SocialDialogueRule(
    id: 'fh1',
    role: SocialDialogueRole.follow,
    topic: SocialTopic.humorBanter,
    replyTag: 'humor_ok',
    template: 'Rir um pouco não quebra o dia.',
  ),
  SocialDialogueRule(
    id: 'fh2',
    role: SocialDialogueRole.follow,
    topic: SocialTopic.humorBanter,
    replyTag: 'humor_dry',
    template: 'Vou tentar reclamar menos. Talvez.',
  ),

  // ===== plansFuture =====
  SocialDialogueRule(
    id: 'op1',
    role: SocialDialogueRole.open,
    topic: SocialTopic.plansFuture,
    replyTag: 'plans_ok',
    template: 'O que você quer fazer depois{named}?',
    when: (c) => c.phaseLabel == 'Dia' || c.phaseLabel == 'Amanhecer',
  ),
  SocialDialogueRule(
    id: 'op2',
    role: SocialDialogueRole.open,
    topic: SocialTopic.plansFuture,
    replyTag: 'plans_ok',
    template: 'Tem plano pro resto do {phase}?',
  ),
  SocialDialogueRule(
    id: 'op3',
    role: SocialDialogueRole.open,
    topic: SocialTopic.plansFuture,
    replyTag: 'plans_soft',
    template: 'Eu preciso de um plano… ou de um sofá.',
  ),
  SocialDialogueRule(
    id: 'op4',
    role: SocialDialogueRole.open,
    topic: SocialTopic.plansFuture,
    replyTag: 'plans_ok',
    template: 'Se der, a gente resolve uma coisa pequena hoje.',
  ),
  SocialDialogueRule(
    id: 'rp1',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.plansFuture,
    replyTag: 'plans_ok',
    template: 'Ainda estou decidindo.',
  ),
  SocialDialogueRule(
    id: 'rp2',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.plansFuture,
    replyTag: 'plans_ok',
    template: 'Algo leve, espero.',
  ),
  SocialDialogueRule(
    id: 'rp3',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.plansFuture,
    replyTag: 'plans_soft',
    template: 'Sofá ganha no momento.',
  ),
  SocialDialogueRule(
    id: 'rp4',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.plansFuture,
    replyTag: 'plans_ok',
    template: 'Uma coisa pequena já basta.',
  ),
  SocialDialogueRule(
    id: 'fp1',
    role: SocialDialogueRole.follow,
    topic: SocialTopic.plansFuture,
    replyTag: 'plans_ok',
    template: 'Me conta se mudar de ideia.',
  ),

  // ===== restSleep =====
  SocialDialogueRule(
    id: 'ors1',
    role: SocialDialogueRole.open,
    topic: SocialTopic.restSleep,
    replyTag: 'rest_ok',
    template: 'O corpo já pediu cama{named}.',
    when: (c) => c.phaseLabel == 'Noite' || c.phaseLabel == 'Madrugada',
  ),
  SocialDialogueRule(
    id: 'ors2',
    role: SocialDialogueRole.open,
    topic: SocialTopic.restSleep,
    replyTag: 'rest_ok',
    template: 'Dormir bem é o plano secreto.',
    when: (c) => c.phaseLabel == 'Noite' || c.phaseLabel == 'Madrugada',
  ),
  SocialDialogueRule(
    id: 'ors3',
    role: SocialDialogueRole.open,
    topic: SocialTopic.restSleep,
    replyTag: 'rest_soft',
    template: 'Mais um pouco e eu desligo.',
    when: (c) => c.phaseLabel == 'Noite' || c.phaseLabel == 'Madrugada',
  ),
  SocialDialogueRule(
    id: 'rrs1',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.restSleep,
    replyTag: 'rest_ok',
    template: 'Eu também.',
  ),
  SocialDialogueRule(
    id: 'rrs2',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.restSleep,
    replyTag: 'rest_ok',
    template: 'Merecido.',
  ),
  SocialDialogueRule(
    id: 'rrs3',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.restSleep,
    replyTag: 'rest_soft',
    template: 'Vai. Descansa.',
  ),
  SocialDialogueRule(
    id: 'frs1',
    role: SocialDialogueRole.follow,
    topic: SocialTopic.restSleep,
    replyTag: 'rest_ok',
    template: 'Amanhã a gente continua.',
  ),

  // ===== foodTalk =====
  SocialDialogueRule(
    id: 'ofo1',
    role: SocialDialogueRole.open,
    topic: SocialTopic.foodTalk,
    replyTag: 'food_ok',
    template: 'Tô pensando em comida{named}.',
  ),
  SocialDialogueRule(
    id: 'ofo2',
    role: SocialDialogueRole.open,
    topic: SocialTopic.foodTalk,
    replyTag: 'food_ok',
    template: 'Algo quente ia cair bem.',
  ),
  SocialDialogueRule(
    id: 'ofo3',
    role: SocialDialogueRole.open,
    topic: SocialTopic.foodTalk,
    replyTag: 'food_crave',
    template: 'Se tiver pão, o dia melhora.',
  ),
  SocialDialogueRule(
    id: 'ofo4',
    role: SocialDialogueRole.open,
    topic: SocialTopic.foodTalk,
    replyTag: 'food_ok',
    template: 'Comer sem pressa… isso é luxo.',
    when: (c) => c.venue == SocialVenue.table,
  ),
  SocialDialogueRule(
    id: 'rfo1',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.foodTalk,
    replyTag: 'food_ok',
    template: 'Eu também.',
  ),
  SocialDialogueRule(
    id: 'rfo2',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.foodTalk,
    replyTag: 'food_ok',
    template: 'Faz sentido.',
  ),
  SocialDialogueRule(
    id: 'rfo3',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.foodTalk,
    replyTag: 'food_crave',
    template: 'Pão resolve muita coisa.',
  ),
  SocialDialogueRule(
    id: 'rfo4',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.foodTalk,
    replyTag: 'food_crave',
    template: 'Ou queijo. Ou os dois.',
  ),
  SocialDialogueRule(
    id: 'ffo1',
    role: SocialDialogueRole.follow,
    topic: SocialTopic.foodTalk,
    replyTag: 'food_ok',
    template: 'Depois a gente vê o que tem.',
  ),

  // ===== memoryPast =====
  SocialDialogueRule(
    id: 'om1',
    role: SocialDialogueRole.open,
    topic: SocialTopic.memoryPast,
    replyTag: 'memory_ok',
    template: 'Lembra daquele dia bagunçado{named}?',
    when: (c) => c.affinity >= 0.35,
  ),
  SocialDialogueRule(
    id: 'om2',
    role: SocialDialogueRole.open,
    topic: SocialTopic.memoryPast,
    replyTag: 'memory_ok',
    template: 'Tem coisa antiga que ainda aquece.',
    when: (c) => c.affinity >= 0.4,
  ),
  SocialDialogueRule(
    id: 'om3',
    role: SocialDialogueRole.open,
    topic: SocialTopic.memoryPast,
    replyTag: 'memory_soft',
    template: 'Às vezes o passado bate na porta sem avisar.',
    when: (c) => c.affinity >= 0.4,
  ),
  SocialDialogueRule(
    id: 'rm1',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.memoryPast,
    replyTag: 'memory_ok',
    template: 'Lembro. Meio confuso.',
  ),
  SocialDialogueRule(
    id: 'rm2',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.memoryPast,
    replyTag: 'memory_ok',
    template: 'Lembro sim.',
  ),
  SocialDialogueRule(
    id: 'rm3',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.memoryPast,
    replyTag: 'memory_soft',
    template: 'Deixa entrar um pouco.',
  ),
  SocialDialogueRule(
    id: 'fm1',
    role: SocialDialogueRole.follow,
    topic: SocialTopic.memoryPast,
    replyTag: 'memory_ok',
    template: 'Bom que a gente passou.',
  ),

  // ===== colonyLife =====
  SocialDialogueRule(
    id: 'ocol1',
    role: SocialDialogueRole.open,
    topic: SocialTopic.colonyLife,
    replyTag: 'colony_ok',
    template: 'Essa colônia anda com cara de casa{named}.',
  ),
  SocialDialogueRule(
    id: 'ocol2',
    role: SocialDialogueRole.open,
    topic: SocialTopic.colonyLife,
    replyTag: 'colony_ok',
    template: 'A gente tá construindo algo, né?',
  ),
  SocialDialogueRule(
    id: 'ocol3',
    role: SocialDialogueRole.open,
    topic: SocialTopic.colonyLife,
    replyTag: 'colony_soft',
    template: 'Entre tarefas, ainda dá pra ser gente.',
  ),
  SocialDialogueRule(
    id: 'ocol4',
    role: SocialDialogueRole.open,
    topic: SocialTopic.colonyLife,
    replyTag: 'colony_ok',
    template: 'O habitat muda quando a gente fala.',
  ),
  SocialDialogueRule(
    id: 'rcol1',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.colonyLife,
    replyTag: 'colony_ok',
    template: 'Concordo.',
  ),
  SocialDialogueRule(
    id: 'rcol2',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.colonyLife,
    replyTag: 'colony_ok',
    template: 'Sinto isso também.',
  ),
  SocialDialogueRule(
    id: 'rcol3',
    role: SocialDialogueRole.reply,
    topic: SocialTopic.colonyLife,
    replyTag: 'colony_soft',
    template: 'Precisamos disso.',
  ),
  SocialDialogueRule(
    id: 'fcol1',
    role: SocialDialogueRole.follow,
    topic: SocialTopic.colonyLife,
    replyTag: 'colony_ok',
    template: 'Um tijolo de cada vez.',
  ),

  // ===== farewells (shared across topics) =====
  SocialDialogueRule(
    id: 'bye1',
    role: SocialDialogueRole.farewell,
    topic: SocialTopic.idleLife,
    template: 'Até{named}.',
  ),
  SocialDialogueRule(
    id: 'bye2',
    role: SocialDialogueRole.farewell,
    topic: SocialTopic.idleLife,
    template: 'Depois a gente continua.',
  ),
  SocialDialogueRule(
    id: 'bye3',
    role: SocialDialogueRole.farewell,
    topic: SocialTopic.idleLife,
    template: 'Fica bem.',
  ),
  SocialDialogueRule(
    id: 'bye4',
    role: SocialDialogueRole.farewell,
    topic: SocialTopic.idleLife,
    template: 'Até logo.',
  ),
  SocialDialogueRule(
    id: 'bye5',
    role: SocialDialogueRole.farewell,
    topic: SocialTopic.idleLife,
    template: 'Vou andando.',
  ),
  SocialDialogueRule(
    id: 'bye6',
    role: SocialDialogueRole.farewell,
    topic: SocialTopic.roomBeauty,
    template: 'Até{named}.',
  ),
  SocialDialogueRule(
    id: 'bye7',
    role: SocialDialogueRole.farewell,
    topic: SocialTopic.nightQuiet,
    template: 'Boa noite.',
    when: (c) => c.phaseLabel == 'Noite' || c.phaseLabel == 'Madrugada',
  ),
  SocialDialogueRule(
    id: 'bye8',
    role: SocialDialogueRole.farewell,
    topic: SocialTopic.restSleep,
    template: 'Vai descansar.',
  ),
  SocialDialogueRule(
    id: 'bye9',
    role: SocialDialogueRole.farewell,
    topic: SocialTopic.mealTable,
    template: 'Bom papo.',
  ),
  SocialDialogueRule(
    id: 'bye10',
    role: SocialDialogueRole.farewell,
    topic: SocialTopic.humorBanter,
    template: 'Valeu o sorriso.',
  ),
  SocialDialogueRule(
    id: 'bye11',
    role: SocialDialogueRole.farewell,
    topic: SocialTopic.colonyLife,
    template: 'A colônia continua.',
  ),
  SocialDialogueRule(
    id: 'bye12',
    role: SocialDialogueRole.farewell,
    topic: SocialTopic.plansFuture,
    template: 'Me conta depois.',
  ),
  SocialDialogueRule(
    id: 'bye13',
    role: SocialDialogueRole.farewell,
    topic: SocialTopic.foodTalk,
    template: 'Bora pensar na comida.',
  ),
  SocialDialogueRule(
    id: 'bye14',
    role: SocialDialogueRole.farewell,
    topic: SocialTopic.memoryPast,
    template: 'Bom lembrar juntos.',
  ),
  SocialDialogueRule(
    id: 'bye15',
    role: SocialDialogueRole.farewell,
    topic: SocialTopic.workDesk,
    template: 'Volto pro batente.',
  ),
  SocialDialogueRule(
    id: 'bye16',
    role: SocialDialogueRole.farewell,
    topic: SocialTopic.cozyWarm,
    template: 'Fica nesse aconchego.',
  ),
  SocialDialogueRule(
    id: 'bye17',
    role: SocialDialogueRole.farewell,
    topic: SocialTopic.weatherOut,
    template: 'Cuida do tempo.',
  ),
  SocialDialogueRule(
    id: 'bye18',
    role: SocialDialogueRole.farewell,
    topic: SocialTopic.lampLight,
    template: 'Deixa a luz aí.',
  ),
  SocialDialogueRule(
    id: 'bye19',
    role: SocialDialogueRole.farewell,
    topic: SocialTopic.filth,
    template: 'A vassoura espera.',
  ),
  SocialDialogueRule(
    id: 'bye20',
    role: SocialDialogueRole.farewell,
    topic: SocialTopic.crowding,
    template: 'Vou dar espaço.',
  ),
];

// ---------------------------------------------------------------------------
// Longer subject threads (A→B→A→B… then farewell)
// ---------------------------------------------------------------------------

final List<DialogueThread> _threads = [
  // --- Beauty / space ---
  DialogueThread(
    id: 'th_beauty_long1',
    topic: SocialTopic.roomBeauty,
    replyTag: 'beauty_ok',
    priority: 2,
    when: (c) => c.beautyBand != 'low',
    beats: [
      'Olha esse canto{named}. Mudou, né?',
      'Mudou. Antes era só passagem.',
      'Agora dá vontade de parar um pouco.',
      'Parar sem culpa. Isso é raro.',
      'Acho que o espaço também cansa… ou descansa.',
    ],
  ),
  DialogueThread(
    id: 'th_beauty_long2',
    topic: SocialTopic.roomBeauty,
    replyTag: 'beauty_ask',
    when: (c) => c.beautyBand == 'high',
    beats: [
      'Você sente quando um lugar “aceita” a gente?',
      'Sinto. O peito baixa um pouco.',
      'Aqui hoje aceitou.',
      'Então vamos aproveitar enquanto dura.',
    ],
  ),
  DialogueThread(
    id: 'th_beauty_light',
    topic: SocialTopic.roomBeauty,
    replyTag: 'beauty_ok',
    when: (c) => c.beautyBand == 'high' && c.lightBand != 'dark',
    beats: [
      'A luz e o espaço combinaram hoje.',
      'Combinaram demais.',
      'Se a gente bagunçar, aviso.',
      'Avisa. Eu ajudo a desbagunçar.',
    ],
  ),

  // --- Lamp / night light ---
  DialogueThread(
    id: 'th_lamp_long1',
    topic: SocialTopic.lampLight,
    replyTag: 'lamp_soft',
    when: (c) => c.hasLamp && c.phaseLabel != 'Dia',
    beats: [
      'Essa luz mansa salva o fim do dia.',
      'Salva. Sem ela eu ficava irritado.',
      'Clareza demais também cansa, né?',
      'Cansa. Prefiro esse tom.',
      'Então a lâmpada vira companhia.',
    ],
  ),
  DialogueThread(
    id: 'th_lamp_office',
    topic: SocialTopic.lampLight,
    replyTag: 'lamp_ok',
    when: (c) => c.hasLamp && c.isOffice,
    beats: [
      'No escritório a luz decide o humor.',
      'Decide mais que o café.',
      'Quase. Quase.',
      'Quase é o máximo que eu admito.',
    ],
  ),

  // --- Filth ---
  DialogueThread(
    id: 'th_filth_long1',
    topic: SocialTopic.filth,
    replyTag: 'filth_floor',
    priority: 3,
    minAffinity: 0.25,
    when: (c) => c.cleanBand == 'low',
    beats: [
      'Não dá pra fingir que o chão tá ok.',
      'Não dá. Já tentei.',
      'Uma vassoura e o humor sobe.',
      'Sobe mais que café, às vezes.',
      'Então… plano: limpar sem drama.',
    ],
  ),

  // --- Weather / outdoors ---
  DialogueThread(
    id: 'th_weather_long1',
    topic: SocialTopic.weatherOut,
    replyTag: 'weather_out',
    when: (c) => c.isOutdoor || c.phaseLabel == 'Entardecer',
    beats: [
      'Lá fora o ar tá {temp}. Dá pra sentir.',
      'Dá. Muda a cabeça.',
      'Às vezes o problema era só parede demais.',
      'Parede demais é praga.',
      'Então respira. Um minuto.',
    ],
  ),
  DialogueThread(
    id: 'th_weather_dusk',
    topic: SocialTopic.weatherOut,
    replyTag: 'weather_out',
    when: (c) => c.phaseLabel == 'Entardecer',
    beats: [
      'Entardecer tem cheiro de “quase acabou”.',
      'Quase. Mas ainda dá tempo.',
      'Tempo pra o quê?',
      'Pra não correr. Só isso.',
    ],
  ),
  DialogueThread(
    id: 'th_weather_breeze',
    topic: SocialTopic.weatherOut,
    replyTag: 'weather_breeze',
    when: (c) => c.isOutdoor,
    beats: [
      'Sente? O ar passou limpo.',
      'Passei a mão no nada e gostei.',
      'Poesia barata, mas funciona.',
      'Funciona. Guarda.',
    ],
  ),

  // --- Table / meal ---
  DialogueThread(
    id: 'th_table_long1',
    topic: SocialTopic.mealTable,
    replyTag: 'table_slow',
    when: (c) => c.venue == SocialVenue.table,
    beats: [
      'Mesa é trégua oficial{named}.',
      'Oficial. Sem prazos por um minuto.',
      'Se alguém trouxer problema, a gente come primeiro.',
      'Prioridades certas.',
      'Então: senta, respira, fala baixo.',
    ],
  ),
  DialogueThread(
    id: 'th_table_stories',
    topic: SocialTopic.mealTable,
    replyTag: 'table_chat',
    when: (c) => c.venue == SocialVenue.table && c.affinity >= 0.4,
    beats: [
      'História boa começa em mesa, não em reunião.',
      'Verdade. Reunião come história viva.',
      'Então conta uma coisa sem começo certo.',
      'Uma vez quase queimei água. Quase.',
      'Isso já é clássico da colônia.',
    ],
  ),

  // --- Work ---
  DialogueThread(
    id: 'th_work_long1',
    topic: SocialTopic.workDesk,
    replyTag: 'work_pause',
    when: (c) => c.isOffice,
    beats: [
      'O trabalho não some se a gente piscar.',
      'Não some. Mas o corpo some se a gente não piscar.',
      'Pausa estratégica, então.',
      'Estratégica. Com cara de preguiça.',
      'Preguiça com propósito. Aceito.',
    ],
  ),
  DialogueThread(
    id: 'th_work_desk2',
    topic: SocialTopic.workDesk,
    replyTag: 'work_desk',
    when: (c) => c.isOffice,
    beats: [
      'Às vezes a mesa parece mais alta que eu.',
      'Ela cresce quando a gente está cansado.',
      'Então a gente abaixa a expectativa um pouco.',
      'Um pouco. Não a dignidade.',
    ],
  ),

  // --- Night quiet ---
  DialogueThread(
    id: 'th_night_long1',
    topic: SocialTopic.nightQuiet,
    replyTag: 'night_soft',
    when: (c) => c.phaseLabel == 'Noite' || c.phaseLabel == 'Madrugada',
    beats: [
      'A noite deixa as frases mais honestas.',
      'Mais honestas… ou mais longas.',
      'As duas. Sem plateia.',
      'Sem plateia é luxo.',
      'Então fala o que quiser. Eu escuto.',
    ],
  ),
  DialogueThread(
    id: 'th_night_quiet2',
    topic: SocialTopic.nightQuiet,
    replyTag: 'night_quiet',
    when: (c) => c.phaseLabel == 'Noite' || c.phaseLabel == 'Madrugada',
    beats: [
      'Silêncio bom não é vazio.',
      'É cheio de “não precisa”.',
      'Gosto disso.',
      'Eu também. Fica.',
    ],
  ),

  // --- Cozy ---
  DialogueThread(
    id: 'th_cozy_long1',
    topic: SocialTopic.cozyWarm,
    replyTag: 'cozy_soft',
    when: (c) => c.comfortOk,
    beats: [
      'Tem cantos que abraçam sem braço.',
      'Esse é um deles.',
      'Se eu cochilar aqui, não julga.',
      'Julgo só se roncar alto.',
      'Combinado. Quase.',
    ],
  ),

  // --- Crowding ---
  DialogueThread(
    id: 'th_crowd_long1',
    topic: SocialTopic.crowding,
    replyTag: 'crowd_tight',
    when: (c) => c.spaceTight,
    beats: [
      'Quando aperta, até o pensamento encolhe.',
      'Encolhe. E a paciência também.',
      'Vamos abrir um corredor mental.',
      'E um físico, se der.',
    ],
  ),

  // --- Idle / check-in longer ---
  DialogueThread(
    id: 'th_idle_checkin',
    topic: SocialTopic.idleLife,
    replyTag: 'idle_day',
    beats: [
      'Como tá o {phase} de verdade{named}?',
      'Mais ou menos. Não tá ruim.',
      '“Não tá ruim” já é vitória?',
      'Hoje é. Aceito.',
      'Então marca na parede: sobrevivemos.',
    ],
  ),
  DialogueThread(
    id: 'th_idle_presence',
    topic: SocialTopic.idleLife,
    replyTag: 'idle_check',
    minAffinity: 0.32,
    beats: [
      '{namedLead}só queria te achar um segundo.',
      'Me achou. O que tem?',
      'Nada urgente. Só presença.',
      'Presença resolve mais do que parece.',
      'Então fica. Um minuto.',
    ],
  ),
  DialogueThread(
    id: 'th_idle_wander',
    topic: SocialTopic.idleLife,
    replyTag: 'idle_ok',
    beats: [
      'Andei sem destino e parei em você.',
      'Bom destino, então.',
      'Às vezes o mapa mente e o pé acerta.',
      'Guarda essa frase.',
    ],
  ),

  // --- Humor ---
  DialogueThread(
    id: 'th_humor_long1',
    topic: SocialTopic.humorBanter,
    replyTag: 'humor_ok',
    minAffinity: 0.38,
    beats: [
      'Teoria: se a gente rir, o dia perde pontos.',
      'Teoria falsa. Mas engraçada.',
      'Então rimos e o dia se vira.',
      'O dia que se vire.',
      'Ótimo plano estratégico.',
    ],
  ),
  DialogueThread(
    id: 'th_humor_dry',
    topic: SocialTopic.humorBanter,
    replyTag: 'humor_dry',
    minAffinity: 0.42,
    beats: [
      'Prometi ser positivo. Já estou negociando.',
      'Negociar positividade é o meu hobby.',
      'Quanto custa um “tá tudo bem” convincente?',
      'Barato. Mas não aceito cartão.',
    ],
  ),
  DialogueThread(
    id: 'th_humor_soft',
    topic: SocialTopic.humorBanter,
    replyTag: 'humor_soft',
    minAffinity: 0.45,
    beats: [
      'Você tem cara de quem aguenta uma piada ruim.',
      'Aguento. Com cara feia.',
      'Perfeito. Piada ruim chegando…',
      'Espera. Ainda não.',
      'Ok. Guardei no bolso.',
    ],
  ),

  // --- Plans ---
  DialogueThread(
    id: 'th_plans_long1',
    topic: SocialTopic.plansFuture,
    replyTag: 'plans_ok',
    when: (c) => c.phaseLabel == 'Dia' || c.phaseLabel == 'Amanhecer',
    beats: [
      'Se o dia fosse um mapa, onde você iria primeiro?',
      'Pra algo pequeno que fecha.',
      'Fechar uma coisa já muda o humor.',
      'Muda. E evita a lista infinita.',
      'Então: uma coisa. Só uma.',
    ],
  ),
  DialogueThread(
    id: 'th_plans_soft',
    topic: SocialTopic.plansFuture,
    replyTag: 'plans_soft',
    beats: [
      'Plano A: produtividade. Plano B: sofá.',
      'Plano B tá com cara de vencedor.',
      'Negociamos: sofá com intenção.',
      'Intenção de não se culpar. Aceito.',
    ],
  ),
  DialogueThread(
    id: 'th_plans_together',
    topic: SocialTopic.plansFuture,
    replyTag: 'plans_ok',
    minAffinity: 0.4,
    beats: [
      'Tem algo que a gente possa fazer junto depois?',
      'Tem. Até varrer conta.',
      'Varrer junto é bonding moderno.',
      'Moderno e sem romantizar demais.',
      'Perfeito. Sem discurso.',
    ],
  ),

  // --- Rest ---
  DialogueThread(
    id: 'th_rest_long1',
    topic: SocialTopic.restSleep,
    replyTag: 'rest_ok',
    when: (c) => c.phaseLabel == 'Noite' || c.phaseLabel == 'Madrugada',
    beats: [
      'O sono anda pedindo com educação.',
      'Com educação e urgência.',
      'Se eu ignorar, ele cobra juros.',
      'Juros de humor ruim. Péssimo.',
      'Então vou pagar adiantado: dormir.',
    ],
  ),
  DialogueThread(
    id: 'th_rest_soft',
    topic: SocialTopic.restSleep,
    replyTag: 'rest_soft',
    when: (c) => c.phaseLabel == 'Noite' || c.phaseLabel == 'Madrugada',
    beats: [
      'Mais um pouco e eu viro fantasma educado.',
      'Fantasma que ainda fala “até”.',
      'Até. E boa noite de verdade.',
      'De verdade. Vai.',
    ],
  ),

  // --- Food ---
  DialogueThread(
    id: 'th_food_long1',
    topic: SocialTopic.foodTalk,
    replyTag: 'food_ok',
    beats: [
      'Comida boa rearrange o cérebro.',
      'Rearrange e pede bis.',
      'Qual o prato que salva teu dia?',
      'Qualquer coisa quente com nome simples.',
      'Simples salva. Gourmet cansa.',
    ],
  ),
  DialogueThread(
    id: 'th_food_crave',
    topic: SocialTopic.foodTalk,
    replyTag: 'food_crave',
    beats: [
      'Pão. Só pão. Não me julga.',
      'Não julgo. Julgo quem julga pão.',
      'Filosofia da padaria.',
      'A única que importa agora.',
    ],
  ),
  DialogueThread(
    id: 'th_food_table',
    topic: SocialTopic.foodTalk,
    replyTag: 'food_ok',
    when: (c) => c.venue == SocialVenue.table,
    beats: [
      'Comer {venue} sem pressa é ritual.',
      'Ritual contra o caos.',
      'Então mastiga. O mundo espera.',
      'O mundo que espere na fila.',
    ],
  ),

  // --- Memory ---
  DialogueThread(
    id: 'th_memory_long1',
    topic: SocialTopic.memoryPast,
    replyTag: 'memory_ok',
    minAffinity: 0.4,
    beats: [
      'Tem um dia antigo que ainda aparece{named}.',
      'Aparece em mim também.',
      'Não precisa ser triste. Só… presente.',
      'Presente. Como visita educada.',
      'Então deixa a visita sentar um pouco.',
    ],
  ),
  DialogueThread(
    id: 'th_memory_soft',
    topic: SocialTopic.memoryPast,
    replyTag: 'memory_soft',
    minAffinity: 0.45,
    beats: [
      'Às vezes o passado bate leve.',
      'Leve é melhor que porta arrombada.',
      'A gente ficou, né?',
      'Ficou. E isso conta.',
    ],
  ),
  DialogueThread(
    id: 'th_memory_mess',
    topic: SocialTopic.memoryPast,
    replyTag: 'memory_ok',
    minAffinity: 0.38,
    beats: [
      'Lembra quando tudo era improvisado?',
      'Lembro. E ainda é, um pouco.',
      'Improviso com cariño é método.',
      'Método questionável. Mas nosso.',
    ],
  ),

  // --- Colony life ---
  DialogueThread(
    id: 'th_colony_long1',
    topic: SocialTopic.colonyLife,
    replyTag: 'colony_ok',
    beats: [
      'Essa colônia não é só teto{named}.',
      'É gente andando com intenção.',
      'Às vezes a intenção é só não cair.',
      'Já vale. Não cair é projeto.',
      'Projeto contínuo, então.',
    ],
  ),
  DialogueThread(
    id: 'th_colony_soft',
    topic: SocialTopic.colonyLife,
    replyTag: 'colony_soft',
    minAffinity: 0.35,
    beats: [
      'Entre tarefa e tarefa, a gente ainda é gente.',
      'Ainda. Importante lembrar.',
      'Se esquecer, me puxa a orelha.',
      'Puxo com carinho.',
      'Aceito o carinho. E a orelha.',
    ],
  ),
  DialogueThread(
    id: 'th_colony_build',
    topic: SocialTopic.colonyLife,
    replyTag: 'colony_ok',
    beats: [
      'A gente constrói o lugar… e o lugar constrói a gente.',
      'Ciclo estranho. Funciona.',
      'Hoje o lugar tá pedindo conversa.',
      'Então conversa é manutenção.',
    ],
  ),
  DialogueThread(
    id: 'th_colony_gather',
    topic: SocialTopic.colonyLife,
    replyTag: 'colony_ok',
    when: (c) => c.venue == SocialVenue.gatheringSpot,
    beats: [
      'Esse ponto de encontro funciona, né?',
      'Funciona. Atrai sem forçar.',
      'Gosto quando o mapa sugere, não manda.',
      'Sugestão com cara de casa.',
    ],
  ),

  // --- Doorway / sofa flavored via idle+venue in when ---
  DialogueThread(
    id: 'th_doorway_chat',
    topic: SocialTopic.idleLife,
    replyTag: 'idle_ok',
    when: (c) => c.venue == SocialVenue.doorwayChat,
    beats: [
      'Porta é o limbo das conversas boas.',
      'Nem dentro, nem fora. Perfeito.',
      'Se alguém passar, a gente finje que era só “oi”.',
      'Oi estratégico. Domino.',
    ],
  ),
  DialogueThread(
    id: 'th_sofa_chat',
    topic: SocialTopic.cozyWarm,
    replyTag: 'cozy_ok',
    when: (c) => c.venue == SocialVenue.sofa && c.comfortOk,
    beats: [
      'Sofá é diplomacia mole.',
      'Mole e eficiente.',
      'Se eu afundar, me joga uma almofada.',
      'Almofada e silêncio. Pacote completo.',
    ],
  ),

  // --- Temperature / comfort hybrids on idle ---
  DialogueThread(
    id: 'th_temp_hot',
    topic: SocialTopic.idleLife,
    replyTag: 'idle_day',
    when: (c) => c.tempBand == 'hot',
    beats: [
      'Tá {temp} demais pra pensamento longo.',
      'Pensamento curto, então.',
      'Tipo: água. Sombra. Pausa.',
      'Programa completo.',
    ],
  ),
  DialogueThread(
    id: 'th_temp_cold',
    topic: SocialTopic.idleLife,
    replyTag: 'idle_ok',
    when: (c) => c.tempBand == 'cold',
    beats: [
      'Frio aperta os ombros, né?',
      'Aperta. E pede cobertor mental.',
      'Cobertor mental: conversa baixa.',
      'Aceito. Sem vento no meio.',
    ],
  ),

  // --- Deep-ish affinity talks ---
  DialogueThread(
    id: 'th_affinity_trust',
    topic: SocialTopic.colonyLife,
    replyTag: 'colony_soft',
    minAffinity: 0.55,
    priority: 2,
    beats: [
      'É estranho… mas confio em falar contigo{named}.',
      'Não é estranho. É raro.',
      'Raro e bom. Não quero estragar.',
      'Não estraga. Só continua.',
      'Então continuo. Sem pressa.',
    ],
  ),
  DialogueThread(
    id: 'th_affinity_day',
    topic: SocialTopic.idleLife,
    replyTag: 'idle_day',
    minAffinity: 0.5,
    beats: [
      'Tem dias que a gente só precisa ser visto.',
      'Eu te vejo.',
      'Isso já desamarra um nó.',
      'Então fica o nó desamarrado um pouco.',
    ],
  ),
  DialogueThread(
    id: 'th_affinity_humor',
    topic: SocialTopic.humorBanter,
    replyTag: 'humor_ok',
    minAffinity: 0.5,
    beats: [
      'Se a gente virar estátua, pelo menos lado a lado.',
      'Estátua com expressão de “quase rindo”.',
      'Perfeito. Arte moderna.',
      'Arte barata. Mas nossa.',
    ],
  ),

  // --- Morning / dawn ---
  DialogueThread(
    id: 'th_dawn_plans',
    topic: SocialTopic.plansFuture,
    replyTag: 'plans_ok',
    when: (c) => c.phaseLabel == 'Amanhecer',
    beats: [
      'Amanhecer ainda tem cheiro de chance.',
      'Chance e sono residual.',
      'Mistura perigosa. Ou boa.',
      'Boa se a gente não forçar o motor.',
      'Motor em marcha lenta, então.',
    ],
  ),

  // --- Gathering spot ---
  DialogueThread(
    id: 'th_gather_idle',
    topic: SocialTopic.idleLife,
    replyTag: 'idle_ok',
    when: (c) => c.venue == SocialVenue.gatheringSpot,
    beats: [
      'Aqui o mapa sussurra “fica”.',
      'E a gente obedece sem drama.',
      'Obediência seletiva. Gosto.',
      'A melhor espécie.',
    ],
  ),
];
